import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml'

/**
 * Lessons: what agents on a project learned the hard way, kept as one file each.
 *
 * They used to be entries appended to `.opencastle/LESSONS-LEARNED.md`, each
 * numbered one past the highest number in the file. On a team that is the
 * shape of a merge conflict: two branches each append at the end and each
 * call theirs LES-042. One file per lesson, named by date and title, merges
 * like any other new file, and the index agents read first is compiled from
 * them — rewritten by every `sync`, checked by `sync --check`, never edited.
 *
 * A lesson can cite the code it is about. Copilot Memory showed the value of
 * that: a memory checked against the current code before use does not mislead
 * an agent after a refactor. Here each cited file's fingerprint, taken when the
 * lesson was last verified, lets `doctor` say which lessons the code has moved
 * under — without git history, which a shallow CI clone does not have.
 */

export const LESSON_CATEGORIES = [
  'task-management',
  'jira',
  'mcp-tools',
  'codebase-tool',
  'terminal',
  'framework',
  'cms',
  'database',
  'git',
  'deployment',
  'browser-testing',
  'general',
] as const
export type LessonCategory = (typeof LESSON_CATEGORIES)[number]

export const LESSON_SEVERITIES = ['high', 'medium', 'low'] as const
export type LessonSeverity = (typeof LESSON_SEVERITIES)[number]

/** Relative to `.opencastle/`. */
export const LESSONS_DIR = 'lessons'
export const LESSONS_INDEX = 'LESSONS-LEARNED.md'

/** The first line of a compiled index; a file without it is the old single-file log. */
export const INDEX_MARKER =
  '<!-- Generated by OpenCastle from the files in lessons/. Add a lesson with "opencastle lesson"; this index is rewritten by every sync. -->'

export interface Lesson {
  id: string
  title: string
  category: string
  severity: string
  /** YYYY-MM-DD. */
  added: string
  /** Project-relative paths, optionally `:line`, the lesson is about. */
  citations: string[]
  /** YYYY-MM-DD of the last check that the lesson still holds. */
  verified?: string
  /** Each cited file's content fingerprint at that check, by path. */
  fingerprints?: Record<string, string>
  status: 'active' | 'archived'
  /** The skill or instruction file an archived lesson was merged into. */
  mergedInto?: string
  /** Where a lesson came from, when not from `opencastle lesson`. */
  source?: string
  /** Markdown: Problem, Wrong approach, Correct approach, Why. */
  body: string
  /** File name within `lessons/`. */
  file: string
}

export function isLessonCategory(s: string): s is LessonCategory {
  return (LESSON_CATEGORIES as ReadonlyArray<string>).includes(s)
}

export function isLessonSeverity(s: string): s is LessonSeverity {
  return (LESSON_SEVERITIES as ReadonlyArray<string>).includes(s)
}

export function today(): string {
  return new Date().toISOString().slice(0, 10)
}

/** `quote shell variables` → `quote-shell-variables`, cut at a word under 50 characters. */
export function slugOf(title: string): string {
  const words = title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
  let slug = ''
  for (const w of words) {
    const next = slug ? `${slug}-${w}` : w
    if (next.length > 50) break
    slug = next
  }
  return slug || 'lesson'
}

/** A new lesson's id: its date and title, made unique among `taken`. */
export function newLessonId(title: string, date: string, taken: Set<string>): string {
  const base = `${date}-${slugOf(title)}`
  let id = base
  for (let n = 2; taken.has(id); n++) id = `${base}-${n}`
  return id
}

// ── One lesson file ──────────────────────────────────────────

export function renderLesson(lesson: Omit<Lesson, 'file'>): string {
  const meta: Record<string, unknown> = {
    id: lesson.id,
    title: lesson.title,
    category: lesson.category,
    severity: lesson.severity,
    added: lesson.added,
  }
  if (lesson.citations.length > 0) meta.citations = lesson.citations
  if (lesson.verified) meta.verified = lesson.verified
  if (lesson.fingerprints && Object.keys(lesson.fingerprints).length > 0) meta.fingerprints = lesson.fingerprints
  if (lesson.status === 'archived') meta.status = 'archived'
  if (lesson.mergedInto) meta.mergedInto = lesson.mergedInto
  if (lesson.source) meta.source = lesson.source
  // Strings stay strings: an unquoted date would come back from YAML as a Date.
  const yaml = stringifyYaml(meta, { defaultStringType: 'QUOTE_DOUBLE', defaultKeyType: 'PLAIN', lineWidth: 0 })
  return `---\n${yaml}---\n\n${lesson.body.trim()}\n`
}

/** The body for a lesson written from its parts. */
export function lessonBody(parts: { problem: string; wrong?: string; correct?: string; why?: string }): string {
  const out = [`**Problem:** ${parts.problem.trim()}`]
  if (parts.wrong) out.push(`**Wrong approach:** ${parts.wrong.trim()}`)
  if (parts.correct) out.push(`**Correct approach:** ${parts.correct.trim()}`)
  if (parts.why) out.push(`**Why:** ${parts.why.trim()}`)
  return out.join('\n\n')
}

const FRONTMATTER = /^\uFEFF?---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/

/** Parse one lesson file. Returns an error string for one that cannot be read as a lesson. */
export function parseLesson(text: string, file: string): Lesson | string {
  const m = FRONTMATTER.exec(text)
  if (!m) return 'has no frontmatter'
  let meta: Record<string, unknown>
  try {
    meta = (parseYaml(m[1]) ?? {}) as Record<string, unknown>
  } catch (err) {
    return `has frontmatter that is not valid YAML — ${(err as Error).message}`
  }
  const str = (k: string): string | undefined => {
    const v = meta[k]
    if (v instanceof Date) return v.toISOString().slice(0, 10)
    return typeof v === 'string' || typeof v === 'number' ? String(v) : undefined
  }
  const id = str('id') ?? file.replace(/\.md$/, '')
  const title = str('title')
  if (!title) return 'has no title'
  const citations = Array.isArray(meta.citations) ? meta.citations.filter((c): c is string => typeof c === 'string') : []
  const prints = meta.fingerprints && typeof meta.fingerprints === 'object' && !Array.isArray(meta.fingerprints)
    ? Object.fromEntries(Object.entries(meta.fingerprints).filter((e): e is [string, string] => typeof e[1] === 'string'))
    : undefined
  return {
    id,
    title,
    category: str('category') ?? 'general',
    severity: str('severity') ?? 'medium',
    added: str('added') ?? '',
    citations,
    verified: str('verified'),
    ...(prints && Object.keys(prints).length > 0 && { fingerprints: prints }),
    status: str('status') === 'archived' ? 'archived' : 'active',
    mergedInto: str('mergedInto'),
    source: str('source'),
    body: m[2].trim(),
    file,
  }
}

/** Every lesson in `<customizations>/lessons/`, and the files that could not be read as one. */
export function readLessons(customizationsDir: string): { lessons: Lesson[]; problems: string[] } {
  const dir = join(customizationsDir, LESSONS_DIR)
  const lessons: Lesson[] = []
  const problems: string[] = []
  let names: string[]
  try {
    names = readdirSync(dir)
  } catch {
    return { lessons, problems }
  }
  for (const name of names.sort()) {
    if (!name.endsWith('.md') || name.startsWith('.')) continue
    let text: string
    try {
      text = readFileSync(join(dir, name), 'utf8')
    } catch (err) {
      problems.push(`${LESSONS_DIR}/${name} cannot be read — ${(err as Error).message}`)
      continue
    }
    const parsed = parseLesson(text, name)
    if (typeof parsed === 'string') problems.push(`${LESSONS_DIR}/${name} ${parsed}`)
    else lessons.push(parsed)
  }
  return { lessons, problems }
}

export function findLesson(lessons: Lesson[], idOrFile: string): Lesson | undefined {
  const want = idOrFile.replace(/^.*[\\/]/, '').replace(/\.md$/, '')
  return lessons.find((l) => l.id === want || l.file.replace(/\.md$/, '') === want)
}

// ── The index agents read ────────────────────────────────────

const byDate = (a: Lesson, b: Lesson): number =>
  a.added < b.added ? -1 : a.added > b.added ? 1 : a.id < b.id ? -1 : a.id > b.id ? 1 : 0

/** One line of Markdown, whatever a title holds. */
function inline(text: string): string {
  return text.replace(/[\r\n]+/g, ' ').trim()
}

export function renderIndex(lessons: Lesson[]): string {
  const active = lessons.filter((l) => l.status === 'active')
  const archived = lessons.filter((l) => l.status === 'archived')
  const out: string[] = [
    INDEX_MARKER,
    '',
    '# Lessons Learned',
    '',
    'What agents on this project learned the hard way: a command that failed, a',
    'tool quirk, a convention written down nowhere else. **Read this before you',
    'start work**, then open the lessons that match your task.',
    '',
    'Each lesson is a file in [`lessons/`](lessons/). Add one with',
    '`opencastle lesson --title ... --category ... --severity ... --problem ...`',
    '(and `--cite <path>` for the code it is about). Do not edit this index:',
    'it is rewritten from those files by every `opencastle sync`.',
  ]
  if (active.length === 0) out.push('', 'No lessons yet.')
  const categories = [...new Set(active.map((l) => l.category))].sort()
  for (const category of categories) {
    out.push('', `## ${category}`, '')
    for (const l of active.filter((x) => x.category === category).sort(byDate)) {
      const cites = l.citations.length > 0 ? ` · cites ${l.citations.map((c) => `\`${c}\``).join(', ')}` : ''
      out.push(`- **${inline(l.title)}** — \`${l.severity}\` · ${l.added || 'undated'}${cites} · [${LESSONS_DIR}/${l.file}](${LESSONS_DIR}/${l.file})`)
    }
  }
  if (archived.length > 0) {
    out.push('', '## Archived', '', 'Merged into a skill or instruction file, where agents now meet them. Kept for the record.', '')
    for (const l of archived.sort(byDate)) {
      const into = l.mergedInto ? ` → \`${l.mergedInto}\`` : ''
      out.push(`- **${inline(l.title)}**${into} · [${LESSONS_DIR}/${l.file}](${LESSONS_DIR}/${l.file})`)
    }
  }
  return out.join('\n') + '\n'
}

export function isCompiledIndex(text: string): boolean {
  return text.replace(/^\uFEFF/, '').trimStart().startsWith(INDEX_MARKER)
}

// ── The old single-file log ──────────────────────────────────

/**
 * The shipped template, whitespace-normalised and hashed, in every version a
 * release copied into projects. A file that is still exactly one of these has
 * nothing of the team's in it, so moving to the new index needs no backup.
 */
const LEGACY_TEMPLATES = new Set([
  '575e04ca16faf38f222e8d367c18f829de34f15131aa97a48ed30eeb32bf6fb2',
  '81360338e425d73813368b4d15c950da7b48f858df3c364e461223f766599b11',
])

function templateHash(text: string): string {
  return createHash('sha256').update(text.replace(/\s+/g, ' ').trim()).digest('hex')
}

/**
 * The lessons in an old `LESSONS-LEARNED.md`, wherever in the file they are.
 *
 * Agents appended them wherever they saw fit — after the index as often as
 * before it — and with categories and severities the CLI never offered, so
 * this reads each `### LES-NNN:` block on its own and keeps what it says.
 */
export function parseLegacyLessons(text: string): Array<Omit<Lesson, 'file'>> {
  const lines = text.replace(/\r\n/g, '\n').split('\n')
  const out: Array<Omit<Lesson, 'file'>> = []
  for (let i = 0; i < lines.length; i++) {
    const head = /^###\s+(LES-\d+)\s*:\s*(.+?)\s*$/.exec(lines[i])
    if (!head) continue
    const block: string[] = []
    let j = i + 1
    for (; j < lines.length; j++) {
      if (/^#{1,3}\s/.test(lines[j])) break
      block.push(lines[j])
    }
    i = j - 1
    const field = (name: string): string | undefined => {
      for (const line of block) {
        const m = new RegExp(`^\\|\\s*\\*\\*${name}\\*\\*\\s*\\|\\s*(.*?)\\s*\\|\\s*$`).exec(line)
        if (m) return m[1]
      }
      return undefined
    }
    const firstWord = (v: string | undefined): string | undefined => {
      if (!v) return undefined
      const ticked = /`([^`]+)`/.exec(v)
      return (ticked ? ticked[1] : v.split(/\s+/)[0]).trim() || undefined
    }
    const body = block
      .filter((l) => !/^\s*\|.*\|\s*$/.test(l))
      .filter((l) => !/^\s*`{3,}\s*(markdown)?\s*$/.test(l))
      .join('\n')
      .replace(/(\n\s*---\s*)+\s*$/, '')
      .trim()
    out.push({
      id: head[1],
      title: head[2],
      category: firstWord(field('Category')) ?? 'general',
      severity: firstWord(field('Severity')) ?? 'medium',
      added: firstWord(field('Added')) ?? '',
      citations: [],
      status: 'active',
      body,
    })
  }
  return out
}

export interface LessonsSync {
  /** Lessons moved out of the old single file. */
  migrated: number
  /** Where the old file was kept, when it held anything of the team's. */
  backup?: string
  index: 'created' | 'updated' | 'unchanged' | 'absent'
  problems: string[]
}

/**
 * Bring `.opencastle/` to the current shape: lessons in the old single file
 * moved into `lessons/`, and the index rewritten from the files. Run by `sync`
 * and by every `opencastle lesson` that writes.
 *
 * A project with neither an index nor a `lessons/` directory is left as it is:
 * someone removed the file, and putting it back is not ours to decide.
 */
export function syncLessons(customizationsDir: string): LessonsSync {
  const indexPath = join(customizationsDir, LESSONS_INDEX)
  const dir = join(customizationsDir, LESSONS_DIR)
  const result: LessonsSync = { migrated: 0, index: 'absent', problems: [] }
  let current: string | null = null
  try {
    current = readFileSync(indexPath, 'utf8')
  } catch {
    current = null
  }

  if (current !== null && !isCompiledIndex(current)) {
    const legacy = parseLegacyLessons(current)
    const { lessons: existing } = readLessons(customizationsDir)
    const taken = new Set(existing.map((l) => l.id))
    for (const lesson of legacy) {
      // Run twice — an interrupted sync, or a teammate's sync merged in — and
      // the lesson is already there under its number.
      if (taken.has(lesson.id)) continue
      mkdirSync(dir, { recursive: true })
      writeFileSync(join(dir, `${lesson.id}-${slugOf(lesson.title)}.md`), renderLesson(lesson))
      taken.add(lesson.id)
      result.migrated++
    }
    if (legacy.length > 0 || !LEGACY_TEMPLATES.has(templateHash(current))) {
      const backup = `${indexPath}.opencastle-backup`
      if (!existsSync(backup)) writeFileSync(backup, current)
      result.backup = relative(dirname(customizationsDir), backup).split(sep).join('/')
    }
  }

  if (current === null && !existsSync(dir)) return result
  const { lessons, problems } = readLessons(customizationsDir)
  result.problems = problems
  const next = renderIndex(lessons)
  if (current === next) {
    result.index = 'unchanged'
  } else {
    writeFileSync(indexPath, next)
    result.index = current === null ? 'created' : 'updated'
  }
  return result
}

/**
 * What `sync --check` and `doctor` say about the index, or null when it is
 * current. Never writes.
 */
export function lessonsIndexDrift(customizationsDir: string): string | null {
  const indexPath = join(customizationsDir, LESSONS_INDEX)
  const dir = join(customizationsDir, LESSONS_DIR)
  let current: string | null
  try {
    current = readFileSync(indexPath, 'utf8')
  } catch {
    current = null
  }
  if (current !== null && !isCompiledIndex(current)) {
    const n = parseLegacyLessons(current).length
    return n > 0
      ? `holds ${n} lesson(s) in the old single-file format; sync moves each into ${LESSONS_DIR}/`
      : 'is the old single-file log; sync replaces it with an index of lessons/'
  }
  if (current === null) return existsSync(dir) ? `is missing, while ${LESSONS_DIR}/ has lessons to list` : null
  const { lessons } = readLessons(customizationsDir)
  return current === renderIndex(lessons) ? null : `does not list what is in ${LESSONS_DIR}/ — a lesson was added, changed or merged in`
}

// ── Citations ────────────────────────────────────────────────

/** The path part of a citation: `src/a.ts:12` and `src/a.ts#L12` both cite `src/a.ts`. */
export function citedPath(citation: string): string {
  return citation.replace(/#L\d+(-L?\d+)?$/, '').replace(/:\d+(-\d+)?$/, '').replace(/^\.\//, '')
}

/** Why a citation cannot be recorded, or null when it can. */
export function citationProblem(projectRoot: string, citation: string): string | null {
  const path = citedPath(citation)
  if (!path || isAbsolute(path) || /^[A-Za-z]:[\\/]/.test(path)) return `cite a path relative to the project root, not ${citation}`
  const abs = resolve(projectRoot, path)
  if (relative(projectRoot, abs).startsWith('..')) return `${citation} is outside the project`
  if (!existsSync(abs)) return `${citation} does not exist`
  return null
}

/**
 * A short digest of a file's content, line endings normalised so a checkout
 * with `core.autocrlf` does not read as a change. Null for what is not a file.
 */
export function fingerprintOf(projectRoot: string, path: string): string | null {
  try {
    const text = readFileSync(resolve(projectRoot, path), 'utf8').replace(/\r\n/g, '\n')
    return createHash('sha256').update(text).digest('hex').slice(0, 12)
  } catch {
    return null
  }
}

/** The fingerprint of every file a lesson cites, by path. */
export function fingerprintsOf(projectRoot: string, citations: string[]): Record<string, string> {
  const out: Record<string, string> = {}
  for (const c of citations) {
    const path = citedPath(c)
    const print = fingerprintOf(projectRoot, path)
    if (print) out[path] = print
  }
  return out
}

export interface StaleCitation {
  lesson: Lesson
  citation: string
  why: 'missing' | 'changed'
}

/**
 * Citations whose file is gone, or whose content differs from its fingerprint
 * when the lesson was last verified. A citation recorded with no fingerprint —
 * a directory, or a lesson written by hand — is checked for existence only.
 */
export function staleCitations(projectRoot: string, lessons: Lesson[]): StaleCitation[] {
  const out: StaleCitation[] = []
  for (const lesson of lessons) {
    if (lesson.status !== 'active') continue
    for (const citation of lesson.citations) {
      const path = citedPath(citation)
      const abs = resolve(projectRoot, path)
      if (!existsSync(abs)) {
        out.push({ lesson, citation, why: 'missing' })
        continue
      }
      if (!statSync(abs).isFile()) continue
      const want = lesson.fingerprints?.[path]
      if (want && fingerprintOf(projectRoot, path) !== want) out.push({ lesson, citation, why: 'changed' })
    }
  }
  return out
}

/** The check `doctor` runs on a project's lessons. */
export function checkLessons(projectRoot: string): {
  ok: boolean
  label: string
  detail?: string
  warning?: boolean
  fix?: string
} {
  const label = 'Lessons'
  const dir = join(projectRoot, '.opencastle')
  const drift = lessonsIndexDrift(dir)
  if (drift) {
    return { ok: true, warning: true, label, detail: `.opencastle/${LESSONS_INDEX} ${drift}`, fix: 'opencastle sync' }
  }
  const { lessons, problems } = readLessons(dir)
  if (problems.length > 0) {
    return {
      ok: true,
      warning: true,
      label,
      detail: problems.map((p) => `.opencastle/${p}`).join('; '),
      fix: 'fix the frontmatter of each, or delete it',
    }
  }
  const active = lessons.filter((l) => l.status === 'active')
  if (active.length === 0) return { ok: true, label, detail: 'none recorded yet' }
  const stale = staleCitations(projectRoot, active)
  if (stale.length > 0) {
    const said = stale.map((s) =>
      s.why === 'missing'
        ? `${s.lesson.id} cites ${s.citation}, which no longer exists`
        : `${s.lesson.id} cites ${s.citation}, which has changed since it was verified${s.lesson.verified ? ` on ${s.lesson.verified}` : ''}`,
    )
    const ids = [...new Set(stale.map((s) => s.lesson.id))]
    return {
      ok: true,
      warning: true,
      label,
      detail: said.join('; '),
      fix:
        `check that each still holds, then opencastle lesson verify ${ids[0]}${ids.length > 1 ? ' (and the others)' : ''} — ` +
        'with --cite <path> for a file that moved — or retire it with opencastle lesson archive <id> --into <file>',
    }
  }
  const cited = active.filter((l) => l.citations.length > 0).length
  return {
    ok: true,
    label,
    detail: `${active.length} lesson(s)${cited > 0 ? `; the ${cited} that cite code match it` : ''}`,
  }
}
