import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'

/**
 * Merge generated content into a file the user may already own.
 *
 * Root instruction files — CLAUDE.md, AGENTS.md, GEMINI.md,
 * .github/copilot-instructions.md — are the one place where the user's own
 * writing and the compiler's output share a file. The adapters used to resolve
 * that by skipping: if the file existed, nothing was written. On the exact repo
 * this tool is pitched at — one that already has a CLAUDE.md — that meant the
 * instructions layer silently never installed.
 *
 * A marked block fixes both halves. The user's content is never touched, and
 * the generated section can be replaced on every sync without diffing prose.
 * Same convention as the .gitignore block, so there is one idea to learn.
 */

export const BLOCK_START = '<!-- >>> OpenCastle managed — regenerated by `opencastle sync`, edits here are lost >>> -->'
export const BLOCK_END = '<!-- <<< OpenCastle managed <<< -->'

export type MergeAction = 'created' | 'updated' | 'appended' | 'unchanged'

export interface MergeResult {
  action: MergeAction
  /** True when the file held content the user wrote. */
  preservedUserContent: boolean
}

/** Extract whatever sits outside the managed block. */
export function stripManagedBlock(content: string): string {
  const start = content.indexOf(BLOCK_START)
  if (start === -1) return content
  const end = content.indexOf(BLOCK_END, start)
  if (end === -1) return content.slice(0, start)
  return content.slice(0, start) + content.slice(end + BLOCK_END.length)
}

export function hasManagedBlock(content: string): boolean {
  return content.includes(BLOCK_START)
}

function wrap(body: string): string {
  return `${BLOCK_START}\n\n${body.trim()}\n\n${BLOCK_END}\n`
}

/**
 * Write `body` into `path` as a managed block.
 *
 * - No file: write the block alone.
 * - File without a block: keep it verbatim, append the block.
 * - File with a block: replace only the block.
 */
export async function writeManagedBlock(path: string, body: string): Promise<MergeResult> {
  const block = wrap(body)

  if (!existsSync(path)) {
    await writeFile(path, block)
    return { action: 'created', preservedUserContent: false }
  }

  const existing = await readFile(path, 'utf8')

  if (hasManagedBlock(existing)) {
    const start = existing.indexOf(BLOCK_START)
    const endIdx = existing.indexOf(BLOCK_END, start)
    const end = endIdx === -1 ? existing.length : endIdx + BLOCK_END.length
    const next = existing.slice(0, start) + block.trimEnd() + existing.slice(end)
    if (next === existing) {
      return { action: 'unchanged', preservedUserContent: stripManagedBlock(existing).trim().length > 0 }
    }
    await writeFile(path, next)
    return { action: 'updated', preservedUserContent: stripManagedBlock(existing).trim().length > 0 }
  }

  // The user's file predates OpenCastle. Keep every byte of it and add the block
  // underneath, with a line explaining what the block is.
  const userContent = existing.trimEnd()
  const preamble = userContent.length > 0
    ? `${userContent}\n\n---\n\n`
    : ''
  await writeFile(path, preamble + block)
  return { action: 'appended', preservedUserContent: userContent.length > 0 }
}
