import { readFile, writeFile, rm } from 'node:fs/promises'
import { existsSync } from 'node:fs'

/**
 * Merge generated content into a file the user may already own.
 *
 * Root instruction files — CLAUDE.md, AGENTS.md, GEMINI.md,
 * .github/copilot-instructions.md — are the one place where the user's own
 * writing and the compiler's output share a file. The adapters used to resolve
 * that by skipping: if the file existed, nothing was written. On the exact repo
 * this tool is pitched at — one that already has a CLAUDE.md — that meant the
 * instructions layer silently never installed.
 *
 * A marked block fixes both halves. The user's content is never touched, and
 * the generated section can be replaced on every sync without diffing prose.
 * Same convention as the .gitignore block, so there is one idea to learn.
 */

export const BLOCK_START = '<!-- >>> OpenCastle managed — regenerated by `opencastle sync`, edits here are lost >>> -->'
export const BLOCK_END = '<!-- <<< OpenCastle managed <<< -->'

export type MergeAction = 'created' | 'updated' | 'appended' | 'adopted' | 'unchanged'

export interface MergeResult {
  action: MergeAction
  /** True when the file held content the user wrote. */
  preservedUserContent: boolean
}

/**
 * Fingerprints of a root file that an OpenCastle release before the markers
 * generated in full.
 *
 * Without this, every existing install's first `sync` would treat its own old
 * output as the user's writing, keep it, and append a second copy underneath —
 * leaving a doubled file whose stale half still advertises agents and skills
 * that no longer exist. These strings only ever came out of this tool.
 */
const LEGACY_GENERATED_MARKERS = [
  'This file is managed by OpenCastle',
  'All conventions, architecture, and project context are embedded below',
  'All conventions, architecture, and project context live in',
]

/** Headers those releases opened the file with. */
const LEGACY_GENERATED_HEADERS = ['# Project Instructions', '# Copilot Instructions']

/** First line with content, ignoring comments that are not our own banner. */
function firstMeaningfulLine(content: string): string {
  for (const raw of content.split('\n')) {
    const line = raw.trim()
    if (!line) continue
    if (line.startsWith('<!--')) {
      if (LEGACY_GENERATED_MARKERS.some((m) => line.includes(m))) return line
      continue
    }
    return line
  }
  return ''
}

/**
 * True only when the file is generated all the way through.
 *
 * Matching a fingerprint anywhere is not enough, in two directions. People edit
 * their generated CLAUDE.md to add house rules at the top — adopting that file
 * deletes the rules, which is the loss the markers exist to prevent wearing a
 * narrower disguise. And a hand-written file can quote "This file is managed by
 * OpenCastle" in a note to teammates without being ours at all. A file that
 * opens with someone else's writing is theirs: the block is appended instead,
 * and the stale generated text stays visible, which is untidy but recoverable.
 */
function looksLikeLegacyGenerated(content: string): boolean {
  const first = firstMeaningfulLine(content)
  const startsGenerated =
    LEGACY_GENERATED_HEADERS.includes(first) ||
    LEGACY_GENERATED_MARKERS.some((m) => first.includes(m))
  return startsGenerated && LEGACY_GENERATED_MARKERS.some((m) => content.includes(m))
}

/** Extract whatever sits outside the managed block. */
export function stripManagedBlock(content: string): string {
  const start = content.indexOf(BLOCK_START)
  if (start === -1) return content
  const end = content.indexOf(BLOCK_END, start)
  // A hand edit or a merge conflict can lose the end marker. Dropping everything
  // after the start marker in that case would delete whatever the user had written
  // below the block, so keep it: only the marker line itself is removed.
  if (end === -1) return content.slice(0, start) + content.slice(start + BLOCK_START.length)
  return content.slice(0, start) + content.slice(end + BLOCK_END.length)
}

export function hasManagedBlock(content: string): boolean {
  return content.includes(BLOCK_START)
}

function wrap(body: string): string {
  return `${BLOCK_START}\n\n${body.trim()}\n\n${BLOCK_END}\n`
}

/**
 * Everything outside the block, exactly as the user left it.
 *
 * There used to be two edits here, and both were mistakes. Collapsing runs of
 * three or more newlines reflowed prose the tool never wrote, including the
 * blank lines inside a fenced code block. Stripping a trailing `---` deleted a
 * horizontal rule the user may well have written themselves — indistinguishable,
 * once the block is gone, from the separator we used to insert. So we no longer
 * insert one: `BLOCK_START` is already a visible delimiter, and not writing the
 * rule is the only way to be sure we never delete someone else's.
 *
 * The one byte that is not round-tripped: a file that did not end in a newline
 * gains one, because the block has to start on its own line.
 */
function outsideTheBlock(content: string): string {
  const start = content.indexOf(BLOCK_START)
  if (start === -1) return content

  const endIdx = content.indexOf(BLOCK_END, start)
  const end = endIdx === -1 ? start + BLOCK_START.length : endIdx + BLOCK_END.length

  // Exactly the inverse of what the append path writes: it puts one newline
  // between the user's content and BLOCK_START, and one after BLOCK_END. Take
  // back those two and nothing else, positionally, so no regex has to guess
  // which blank line belonged to whom.
  const before = content.slice(0, start).replace(/\n$/, '')
  const after = content.slice(end).replace(/^\n/, '')
  return before + after
}

/**
 * Write `body` into `path` as a managed block.
 *
 * - No file: write the block alone.
 * - File with a block: replace only the block.
 * - File this tool generated before markers existed: replace it wholesale.
 * - Any other file: keep it verbatim, append the block.
 */
export async function writeManagedBlock(path: string, body: string): Promise<MergeResult> {
  const block = wrap(body)

  if (!existsSync(path)) {
    await writeFile(path, block)
    return { action: 'created', preservedUserContent: false }
  }

  const existing = await readFile(path, 'utf8')

  if (hasManagedBlock(existing)) {
    const start = existing.indexOf(BLOCK_START)
    const endIdx = existing.indexOf(BLOCK_END, start)
    const end = endIdx === -1 ? start + BLOCK_START.length : endIdx + BLOCK_END.length
    const next = existing.slice(0, start) + block.trimEnd() + existing.slice(end)
    const hadUserContent = outsideTheBlock(existing).trim().length > 0
    if (next === existing) {
      return { action: 'unchanged', preservedUserContent: hadUserContent }
    }
    await writeFile(path, next)
    return { action: 'updated', preservedUserContent: hadUserContent }
  }

  if (looksLikeLegacyGenerated(existing)) {
    await writeFile(path, block)
    return { action: 'adopted', preservedUserContent: false }
  }

  // The user's file predates OpenCastle. Keep every byte of it — no trimming, no
  // reflowing — and start the block on the next line.
  const preamble = existing.length > 0 ? (existing.endsWith('\n') ? existing : `${existing}\n`) + '\n' : ''
  await writeFile(path, preamble + block)
  return { action: 'appended', preservedUserContent: existing.trim().length > 0 }
}

/**
 * Undo only our half of a co-owned file.
 *
 * Removes the managed block. If the user wrote nothing else, the file is deleted;
 * otherwise their content is kept. This is what `init` re-run, the orphaned-install
 * overwrite, and `remove --all` must call instead of unlinking — those three paths
 * treated merged files as wholly generated and destroyed people's own writing.
 */
export async function stripManagedBlockFromFile(
  path: string,
): Promise<'deleted' | 'stripped' | 'absent'> {
  if (!existsSync(path)) return 'absent'
  const existing = await readFile(path, 'utf8')
  if (!hasManagedBlock(existing) && looksLikeLegacyGenerated(existing)) {
    await rm(path, { force: true })
    return 'deleted'
  }
  const remainder = outsideTheBlock(existing)
  if (remainder.trim().length === 0) {
    await rm(path, { force: true })
    return 'deleted'
  }
  await writeFile(path, remainder.endsWith('\n') ? remainder : `${remainder}\n`)
  return 'stripped'
}
