import { readFile, writeFile, rm } from 'node:fs/promises'
import { existsSync } from 'node:fs'

/**
 * Merge generated content into a file the user may already own.
 *
 * Root instruction files — CLAUDE.md, AGENTS.md, GEMINI.md,
 * .github/copilot-instructions.md — are the one place where the user's own
 * writing and the compiler's output share a file. The adapters used to resolve
 * that by skipping: if the file existed, nothing was written. On the exact repo
 * this tool is pitched at — one that already has a CLAUDE.md — that meant the
 * instructions layer silently never installed.
 *
 * A marked block fixes both halves. The user's content is never touched, and
 * the generated section can be replaced on every sync without diffing prose.
 * Same convention as the .gitignore block, so there is one idea to learn.
 */

export const BLOCK_START = '<!-- >>> OpenCastle managed — regenerated by `opencastle sync`, edits here are lost >>> -->'
export const BLOCK_END = '<!-- <<< OpenCastle managed <<< -->'

export type MergeAction =
  | 'created'
  | 'updated'
  | 'appended'
  | 'adopted'
  /** The end marker was missing; the block was rebuilt and the old file backed up. */
  | 'repaired'
  | 'unchanged'

export interface MergeResult {
  action: MergeAction
  /** True when the file held content the user wrote. */
  preservedUserContent: boolean
  /**
   * The file keeps output from an older release above our block, which we could
   * not safely remove because the user's own writing came first.
   */
  staleGeneratedContent?: boolean
}

/**
 * Fingerprints of a root file that an OpenCastle release before the markers
 * generated in full.
 *
 * Without this, every existing install's first `sync` would treat its own old
 * output as the user's writing, keep it, and append a second copy underneath —
 * leaving a doubled file whose stale half still advertises agents and skills
 * that no longer exist. These strings only ever came out of this tool.
 */
const LEGACY_GENERATED_MARKERS = [
  'This file is managed by OpenCastle',
  'All conventions, architecture, and project context are embedded below',
  'All conventions, architecture, and project context live in',
]

/** Headers those releases opened the file with. */
const LEGACY_GENERATED_HEADERS = ['# Project Instructions', '# Copilot Instructions']

/** First line with content, ignoring comments that are not our own banner. */
function firstMeaningfulLine(content: string): string {
  for (const raw of content.split('\n')) {
    const line = raw.trim()
    if (!line) continue
    if (line.startsWith('<!--')) {
      if (LEGACY_GENERATED_MARKERS.some((m) => line.includes(m))) return line
      continue
    }
    return line
  }
  return ''
}

/**
 * True only when the file is generated all the way through.
 *
 * Matching a fingerprint anywhere is not enough, in two directions. People edit
 * their generated CLAUDE.md to add house rules at the top — adopting that file
 * deletes the rules, which is the loss the markers exist to prevent wearing a
 * narrower disguise. And a hand-written file can quote "This file is managed by
 * OpenCastle" in a note to teammates without being ours at all. A file that
 * opens with someone else's writing is theirs: the block is appended instead,
 * and the stale generated text stays visible, which is untidy but recoverable.
 */
function looksLikeLegacyGenerated(content: string): boolean {
  const first = firstMeaningfulLine(content)
  const startsGenerated =
    LEGACY_GENERATED_HEADERS.includes(first) ||
    LEGACY_GENERATED_MARKERS.some((m) => first.includes(m))
  return startsGenerated && LEGACY_GENERATED_MARKERS.some((m) => content.includes(m))
}

/** Extract whatever sits outside the managed block. */
export function stripManagedBlock(content: string): string {
  const start = findBlockStart(content)
  if (start === -1) return content
  const end = content.indexOf(BLOCK_END, start)
  // A hand edit or a merge conflict can lose the end marker. Dropping everything
  // after the start marker in that case would delete whatever the user had written
  // below the block, so keep it: only the marker line itself is removed.
  if (end === -1) return content.slice(0, start) + content.slice(start + BLOCK_START.length)
  return content.slice(0, start) + content.slice(end + BLOCK_END.length)
}

/**
 * Index of the real start marker, or -1.
 *
 * A plain `includes` matched the marker wherever it appeared, including inside a
 * fenced code block — and `docs/quickstart.md` shows readers that exact string,
 * so a CLAUDE.md documenting the convention had the generated block written
 * inside its own code fence.
 */
function findBlockStart(content: string): number {
  let from = 0
  for (;;) {
    const at = content.indexOf(BLOCK_START, from)
    if (at === -1) return -1
    const fencesBefore = (content.slice(0, at).match(/^\s*```/gm) ?? []).length
    if (fencesBefore % 2 === 0) return at
    from = at + BLOCK_START.length
  }
}

export function hasManagedBlock(content: string): boolean {
  return findBlockStart(content) !== -1
}

function wrap(body: string): string {
  return `${BLOCK_START}\n\n${body.trim()}\n\n${BLOCK_END}\n`
}

/**
 * Everything outside the block, exactly as the user left it.
 *
 * There used to be two edits here, and both were mistakes. Collapsing runs of
 * three or more newlines reflowed prose the tool never wrote, including the
 * blank lines inside a fenced code block. Stripping a trailing `---` deleted a
 * horizontal rule the user may well have written themselves — indistinguishable,
 * once the block is gone, from the separator we used to insert. So we no longer
 * insert one: `BLOCK_START` is already a visible delimiter, and not writing the
 * rule is the only way to be sure we never delete someone else's.
 *
 * The one byte that is not round-tripped: a file that did not end in a newline
 * gains one, because the block has to start on its own line.
 */
function outsideTheBlock(content: string): string {
  const start = findBlockStart(content)
  if (start === -1) return content

  const endIdx = content.indexOf(BLOCK_END, start)
  const end = endIdx === -1 ? start + BLOCK_START.length : endIdx + BLOCK_END.length

  // Exactly the inverse of what the append path writes: it puts one newline
  // between the user's content and BLOCK_START, and one after BLOCK_END. Take
  // back those two and nothing else, positionally, so no regex has to guess
  // which blank line belonged to whom.
  const before = content.slice(0, start).replace(/\n$/, '')
  const after = content.slice(end).replace(/^\n/, '')
  return before + after
}

export const BACKUP_SUFFIX = '.opencastle-backup'

/**
 * Keep the previous contents beside a file we are about to replace or delete.
 *
 * Used by both paths that act on a root file generated before the markers
 * existed. They used to make the same judgement — "a previous release wrote all
 * of this" — and only one of them kept a copy.
 */
async function backUp(path: string, contents: string): Promise<void> {
  await writeFile(`${path}${BACKUP_SUFFIX}`, contents)
}

/**
 * Write `body` into `path` as a managed block.
 *
 * - No file: write the block alone.
 * - File with a block: replace only the block.
 * - File this tool generated before markers existed: replace it wholesale.
 * - Any other file: keep it verbatim, append the block.
 */
export async function writeManagedBlock(path: string, body: string): Promise<MergeResult> {
  const block = wrap(body)

  if (!existsSync(path)) {
    await writeFile(path, block)
    return { action: 'created', preservedUserContent: false }
  }

  const existing = await readFile(path, 'utf8')

  if (hasManagedBlock(existing)) {
    const start = findBlockStart(existing)
    const endIdx = existing.indexOf(BLOCK_END, start)

    // With the end marker gone we cannot tell our stale body from anything the
    // user wrote below it. Inserting a fresh block and leaving the old one in
    // place doubled the file permanently — two full copies of the instructions,
    // the stale half still naming deleted agents — and `sync --check` then
    // certified it, because it only ever compares the block. So: keep the
    // remainder, but move it into a backup rather than leaving it to rot inline.
    if (endIdx === -1) {
      await backUp(path, existing)
      const below = existing.slice(start + BLOCK_START.length)
      const above = existing.slice(0, start).replace(/\n$/, '')
      const preamble = above.length > 0 ? `${above}\n\n` : ''
      await writeFile(path, preamble + block)
      return {
        action: 'repaired',
        preservedUserContent: above.trim().length > 0 || below.trim().length > 0,
      }
    }

    const end = endIdx + BLOCK_END.length
    const next = existing.slice(0, start) + block.trimEnd() + existing.slice(end)
    const hadUserContent = outsideTheBlock(existing).trim().length > 0
    if (next === existing) {
      return { action: 'unchanged', preservedUserContent: hadUserContent }
    }
    await writeFile(path, next)
    return { action: 'updated', preservedUserContent: hadUserContent }
  }

  if (looksLikeLegacyGenerated(existing)) {
    // The one operation here that discards anything: a previous release wrote
    // this whole file, so replacing it is right — but if someone appended notes
    // below the generated part, there is no marker to tell us where theirs
    // began. Keep a copy next to it rather than being clever, and let the user
    // decide.
    await backUp(path, existing)
    await writeFile(path, block)
    return { action: 'adopted', preservedUserContent: false }
  }

  // The user's file predates OpenCastle. Keep every byte of it — no trimming, no
  // reflowing — and start the block on the next line.
  const preamble = existing.length > 0 ? (existing.endsWith('\n') ? existing : `${existing}\n`) + '\n' : ''
  await writeFile(path, preamble + block)
  return {
    action: 'appended',
    preservedUserContent: existing.trim().length > 0,
    // Their own writing came first, so we appended rather than adopting — but
    // the file also carries our old output somewhere below, and that stale half
    // still names agents and skills that no longer exist. The agent reads both.
    // Adoption exists to prevent exactly that, so when we decline to adopt, the
    // user has to be told what is now doubled.
    ...(LEGACY_GENERATED_MARKERS.some((m) => existing.includes(m)) && { staleGeneratedContent: true }),
  }
}

/**
 * Undo only our half of a co-owned file.
 *
 * Removes the managed block. If the user wrote nothing else, the file is deleted;
 * otherwise their content is kept. This is what `init` re-run, the orphaned-install
 * overwrite, and `remove --all` must call instead of unlinking — those three paths
 * treated merged files as wholly generated and destroyed people's own writing.
 */
/**
 * What `stripManagedBlockFromFile` will do to this content, without doing it.
 *
 * Exists so `remove`'s preview and `remove` itself cannot disagree. They did:
 * the preview assumed every co-owned file survives and printed "your own
 * writing stays" over files that were about to be deleted.
 */
export function predictStrip(content: string): {
  outcome: 'stripped' | 'deleted'
  /** True when the file is ours from an older release, so a backup is written. */
  legacyGenerated: boolean
} {
  if (!hasManagedBlock(content) && looksLikeLegacyGenerated(content)) {
    return { outcome: 'deleted', legacyGenerated: true }
  }
  const remainder = outsideTheBlock(content)
  return {
    outcome: remainder.trim().length === 0 ? 'deleted' : 'stripped',
    legacyGenerated: false,
  }
}

export async function stripManagedBlockFromFile(
  path: string,
): Promise<'deleted' | 'stripped' | 'absent'> {
  if (!existsSync(path)) return 'absent'
  const existing = await readFile(path, 'utf8')
  if (!hasManagedBlock(existing) && looksLikeLegacyGenerated(existing)) {
    // Identical input, identical judgement, so identical care as the adopt path:
    // this file has no marker to say where anything appended below the generated
    // part begins. `sync` backed it up and these two callers did not, so one
    // input got two answers and `remove --all` deleted prose one line after
    // printing "your own writing stays".
    await backUp(path, existing)
    await rm(path, { force: true })
    return 'deleted'
  }
  const remainder = outsideTheBlock(existing)
  if (remainder.trim().length === 0) {
    await rm(path, { force: true })
    return 'deleted'
  }
  await writeFile(path, remainder.endsWith('\n') ? remainder : `${remainder}\n`)
  return 'stripped'
}
