import { resolve } from 'node:path'
import { unlink, readFile, rename } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { readManifest } from './manifest.js'
import { removeDirIfExists } from './copy.js'
import { removeGitignoreBlock } from './gitignore.js'
import { confirm, select, closePrompts, c } from './prompt.js'
import { stripManagedBlockFromFile, predictStrip } from './managed-block.js'
import { resolveManagedPaths } from './managed-paths.js'
import { stripManagedMcpServers, getMcpConfigRelPath, willKeepSomethingAfterStrip } from './mcp.js'
import { IDE_ADAPTERS } from './adapters/index.js'
import type { CliContext, IdeChoice } from './types.js'

/**
 * Removal, with the destructive choice made explicit rather than encoded in the
 * command name.
 *
 * Previously this was two commands whose names gave no hint which one deleted
 * your files: "eject" dropped the manifest and kept everything, "destroy"
 * deleted every generated path. Users had to know the vocabulary before they
 * could safely run either. Now one command asks, and always previews first.
 */

const REMOVE_HELP = `
  opencastle remove [options]

  Remove OpenCastle from this project. Asks whether to keep the generated
  files (so they become standalone) or delete everything.

  Options:
    --keep-files    Keep generated files; only drop the manifest
    --all           Delete every generated file
    --dry-run       Preview without changing anything
    --yes           Skip the confirmation prompt
    --help, -h      Show this help
`

type Mode = 'keep-files' | 'all'

interface CoOwnedPreview {
  path: string
  outcome: 'stripped' | 'deleted'
  note: string
}

/**
 * What removal will do to each co-owned file.
 *
 * Deliberately reads the same content `stripManagedBlockFromFile` and
 * `stripManagedMcpServers` will read, so the preview cannot claim one thing and
 * the command do another. It is still two code paths agreeing rather than one
 * path used twice, which is why `remove.test.ts` asserts the agreement.
 */
async function previewCoOwned(
  projectRoot: string,
  mergedPaths: string[],
  mcpPaths: Set<string>,
): Promise<CoOwnedPreview[]> {
  const out: CoOwnedPreview[] = []

  for (const p of mergedPaths) {
    const abs = resolve(projectRoot, p)
    if (!existsSync(abs)) continue
    const { outcome, legacyGenerated } = predictStrip(await readFile(abs, 'utf8'))
    if (outcome === 'stripped') {
      out.push({ path: p, outcome, note: 'the OpenCastle block; your own writing stays' })
    } else {
      out.push({
        path: p,
        outcome,
        note: legacyGenerated
          ? 'generated by an earlier version; a .opencastle-backup is kept'
          : 'it holds nothing but the OpenCastle block',
      })
    }
  }

  for (const p of mcpPaths) {
    const abs = resolve(projectRoot, p)
    if (!existsSync(abs)) continue
    let keepsSomething = true
    try {
      const parsed = JSON.parse(await readFile(abs, 'utf8')) as Record<string, unknown>
      keepsSomething = willKeepSomethingAfterStrip(parsed)
    } catch {
      // Unreadable JSON is left alone entirely, so it certainly survives.
      out.push({ path: p, outcome: 'stripped', note: 'nothing — the file could not be parsed' })
      continue
    }
    out.push(
      keepsSomething
        ? { path: p, outcome: 'stripped', note: 'our MCP servers; the rest of the file stays' }
        : { path: p, outcome: 'deleted', note: 'it holds only our MCP servers' },
    )
  }

  return out
}

export default async function remove({ args }: CliContext): Promise<void> {
  if (args.includes('--help') || args.includes('-h')) {
    console.log(REMOVE_HELP)
    return
  }

  const projectRoot = process.cwd()
  const dryRun = args.includes('--dry-run')
  const assumeYes = args.includes('--yes')

  const manifest = await readManifest(projectRoot)
  if (!manifest) {
    console.error(`\n  ${c.red('✗')} No OpenCastle installation found here.`)
    console.error(`  ${c.dim('Run')} ${c.cyan('opencastle')} ${c.dim('to see project status.')}\n`)
    process.exit(1)
  }

  let mode: Mode | undefined
  if (args.includes('--all')) mode = 'all'
  else if (args.includes('--keep-files')) mode = 'keep-files'

  if (!mode) {
    const answer = await select('What should happen to the generated files?', [
      {
        label: 'Keep them (make them standalone)',
        hint: 'removes the manifest only — you can then uninstall the package',
        value: 'keep-files',
      },
      {
        label: 'Delete everything OpenCastle created',
        hint: 'cannot be undone',
        value: 'all',
      },
    ])
    mode = answer as Mode
  }

  // Not `manifest.managedPaths` directly: a manifest written before root files
  // became co-owned filed them under `framework`, and that list gets unlinked.
  const managed = await resolveManagedPaths(manifest)
  const ides = (manifest.ides?.length ? manifest.ides : [manifest.ide]).filter(
    (id): id is IdeChoice => Boolean(id) && id in IDE_ADAPTERS,
  )
  const mcpPaths = new Set(ides.map((ide) => getMcpConfigRelPath(ide)))
  const frameworkPaths = managed.framework.filter((p) => !mcpPaths.has(p))
  // `.opencastle/` is handled explicitly below, so drop it here — listing it in
  // both places printed it twice and counted it twice in "Removed N path(s)".
  const customizablePaths = managed.customizable.filter(
    (p) => !mcpPaths.has(p) && p !== '.opencastle/',
  )
  const mergedPaths = managed.merged
  const legacyManifestPath = resolve(projectRoot, '.opencastle.json')
  const hasLegacy = existsSync(legacyManifestPath)

  console.log(`\n  🏰 ${c.bold('OpenCastle remove')}\n`)

  if (mode === 'keep-files') {
    console.log('  Will remove:')
    console.log(`    ${c.dim('.opencastle/manifest.json')}`)
    console.log('\n  Every generated file stays exactly where it is.')
    console.log(`  Afterwards: ${c.bold('npm uninstall opencastle')}\n`)
  } else {
    console.log(`  ${c.bold('Deleted')}\n`)
    for (const p of [...frameworkPaths, ...customizablePaths]) {
      console.log(`    ${c.red('-')} ${c.dim(p)}`)
    }
    // Named plainly: this is the one path in the list that holds writing of the
    // user's own, and the command spends the rest of its effort preserving
    // exactly that kind of content elsewhere.
    console.log(
      `    ${c.yellow('→')} ${c.dim('.opencastle/')} ${c.yellow('moved to .opencastle.removed/ — your conventions and lessons')}`,
    )
    if (hasLegacy) console.log(`    ${c.red('-')} ${c.dim('.opencastle.json')}`)

    // Co-owned files are only *sometimes* kept: one holding nothing but our
    // block is deleted. Announcing "your own writing stays" over a file about to
    // disappear is the preview lying, so each outcome is predicted rather than
    // assumed. `previewCoOwned` reads the same files the strip functions will.
    const coOwned = await previewCoOwned(projectRoot, mergedPaths, mcpPaths)
    const alsoDeleted = coOwned.filter((e) => e.outcome === 'deleted')
    const kept = coOwned.filter((e) => e.outcome === 'stripped')

    for (const e of alsoDeleted) {
      console.log(`    ${c.red('-')} ${c.dim(e.path)} ${c.dim(`— ${e.note}`)}`)
    }

    if (kept.length > 0) {
      console.log(`\n  ${c.bold('Edited, not deleted')}\n`)
      for (const e of kept) {
        console.log(`    ${c.yellow('~')} ${c.dim(e.path)} ${c.dim(`— removes ${e.note}`)}`)
      }
    }
    if (existsSync(resolve(projectRoot, '.gitignore'))) {
      if (kept.length === 0) console.log(`\n  ${c.bold('Edited, not deleted')}\n`)
      console.log(`    ${c.yellow('~')} ${c.dim('.gitignore')} ${c.dim('— removes the OpenCastle block')}`)
    }
    console.log()
  }

  if (dryRun) {
    console.log(`  ${c.dim('[dry-run] Nothing was changed.')}\n`)
    closePrompts()
    return
  }

  if (!assumeYes) {
    const proceed = await confirm(
      mode === 'all' ? 'Go ahead?' : 'Continue?',
      mode !== 'all',
    )
    if (!proceed) {
      console.log('  Aborted.\n')
      closePrompts()
      return
    }
  }

  if (mode === 'keep-files') {
    await unlink(resolve(projectRoot, '.opencastle', 'manifest.json')).catch(() => {})
    // An install old enough to use the flat manifest keeps being found by
    // `readManifest`, so dropping only the new path left the project still
    // reporting as installed under a heading that said otherwise.
    if (hasLegacy) await unlink(legacyManifestPath).catch(() => {})
    console.log(`\n  ${c.green('✓')} Files are now standalone.`)
    console.log(`  You can uninstall: ${c.bold('npm uninstall opencastle')}\n`)
    closePrompts()
    return
  }

  let removed = 0
  for (const p of [...frameworkPaths, ...customizablePaths]) {
    if (p.endsWith('/')) {
      await removeDirIfExists(resolve(projectRoot, p))
      removed++
    } else {
      const file = resolve(projectRoot, p)
      if (existsSync(file)) {
        await unlink(file)
        removed++
      }
    }
  }

  // Co-owned files hold the user's own writing above our block. Take back the
  // block; delete the file only if nothing of theirs remains.
  let stripped = 0
  for (const p of mergedPaths) {
    const outcome = await stripManagedBlockFromFile(resolve(projectRoot, p))
    if (outcome === 'deleted') removed++
    else if (outcome === 'stripped') stripped++
  }

  // MCP config is co-owned the same way: we merge our servers into a file that
  // may be the assistant's entire project config. Take back the servers, not
  // the file.
  const unreadable: string[] = []
  for (const ide of ides) {
    const outcome = await stripManagedMcpServers(projectRoot, ide)
    if (outcome === 'deleted') removed++
    else if (outcome === 'stripped') stripped++
    else if (outcome === 'unreadable') unreadable.push(getMcpConfigRelPath(ide))
  }

  // `.opencastle/` holds prose the user wrote — conventions, decisions, lessons —
  // and this same command writes a backup for a root file it merely replaces.
  // `--yes` skips the confirmation, so "previewed and confirmed" is not a
  // standard that actually holds here: `remove --all --yes` is what the help
  // text and CI both use. Renamed rather than deleted, so it is one `mv` back.
  const opencastleDir = resolve(projectRoot, '.opencastle')
  let keptDir: string | undefined
  if (existsSync(opencastleDir)) {
    const parked = resolve(projectRoot, '.opencastle.removed')
    await removeDirIfExists(parked)
    await rename(opencastleDir, parked)
    keptDir = '.opencastle.removed'
  }
  removed++

  if (hasLegacy) {
    await unlink(legacyManifestPath)
    removed++
  }

  const gitignoreResult = await removeGitignoreBlock(projectRoot)

  console.log(
    `\n  ${c.green('✓')} Removed ${removed} path(s)` +
      `${stripped > 0 ? `, kept your content in ${stripped} file(s)` : ''}` +
      `${gitignoreResult === 'removed' ? ' + .gitignore block' : ''}.`,
  )
  for (const p of unreadable) {
    console.log(`  ${c.yellow('!')} Left ${p} alone — it is not valid JSON.`)
  }
  if (keptDir) {
    console.log(
      `  ${c.dim('Your conventions and lessons are in')} ${c.bold(keptDir)}${c.dim(' — delete it when you are sure.')}`,
    )
  }
  console.log(`  You can uninstall: ${c.bold('npm uninstall opencastle')}\n`)

  closePrompts()
}
