import { resolve, relative, dirname } from 'node:path'
import { unlink, readFile, rename } from 'node:fs/promises'
import { existsSync, readdirSync, rmdirSync } from 'node:fs'
import { readManifest } from './manifest.js'
import { removeDirIfExists } from './copy.js'
import { removeGitignoreBlock, predictGitignoreStrip, LOCAL_DIRS } from './gitignore.js'
import { confirm, select, closePrompts, c } from './prompt.js'
import { stripManagedBlockFromFile, predictStripFile } from './managed-block.js'
import { resolveManagedPaths } from './managed-paths.js'
import { stripManagedMcpServers, getMcpConfigRelPath, willKeepSomethingAfterStrip } from './mcp.js'
import { IDE_ADAPTERS } from './adapters/index.js'
import type { CliContext, IdeChoice } from './types.js'

/**
 * Removal, with the destructive choice made explicit rather than encoded in the
 * command name.
 *
 * Previously this was two commands whose names gave no hint which one deleted
 * your files: "eject" dropped the manifest and kept everything, "destroy"
 * deleted every generated path. Users had to know the vocabulary before they
 * could safely run either. Now one command asks, and always previews first.
 */

const REMOVE_HELP = `
  opencastle remove [options]

  Remove OpenCastle from this project. Asks whether to keep the generated
  files (so they become standalone) or delete everything.

  Options:
    --keep-files    Keep generated files; only drop the manifest
    --all           Delete every generated file
    --dry-run       Preview without changing anything
    --yes           Skip the confirmation prompt
    --help, -h      Show this help
`

type Mode = 'keep-files' | 'all'

interface CoOwnedPreview {
  path: string
  outcome: 'stripped' | 'deleted'
  note: string
}

/**
 * What removal will do to each co-owned file.
 *
 * Deliberately reads the same content `stripManagedBlockFromFile` and
 * `stripManagedMcpServers` will read, so the preview cannot claim one thing and
 * the command do another. It is still two code paths agreeing rather than one
 * path used twice, which is why `remove.test.ts` asserts the agreement.
 */
async function previewCoOwned(
  projectRoot: string,
  mergedPaths: string[],
  mcpPaths: Set<string>,
  // Which target owns each MCP path. Without it the preview scanned all three
  // container keys while removal scanned one, so the two could disagree about
  // whether a file survives — in the pair of functions whose whole purpose is
  // agreeing.
  ideFor: Map<string, IdeChoice>,
  // Which of these the install created. A file that ends up empty is not
  // evidence that it was ours, and the manifest is the only thing that knows.
  createdConfigs: Set<string>,
): Promise<CoOwnedPreview[]> {
  const out: CoOwnedPreview[] = []

  for (const p of mergedPaths) {
    const abs = resolve(projectRoot, p)
    if (!existsSync(abs)) continue
    const { outcome, legacyGenerated, staleRemains } = await predictStripFile(abs)
    if (outcome === 'stripped') {
      // "Your own writing stays" is only true when what stays is theirs. On a
      // file upgraded from a pre-marker release, the superseded instruction set
      // sits above our block with no marker to delimit it, so the strip cannot
      // take it and the preview must not imply it did: 197 of the 201 surviving
      // lines were ours, still advertising directories this same command had
      // deleted, and with the manifest gone nothing could find them again.
      out.push({
        path: p,
        outcome,
        note: staleRemains
          ? 'the OpenCastle block; your own writing stays — but a superseded instruction' +
            ' set from an older release stays too, and only you can tell where it ends'
          : 'the OpenCastle block; your own writing stays',
      })
    } else {
      out.push({
        path: p,
        outcome,
        note: legacyGenerated
          ? 'generated by an earlier version; a .opencastle-backup is kept'
          : 'it holds nothing but the OpenCastle block',
      })
    }
  }

  for (const p of mcpPaths) {
    const abs = resolve(projectRoot, p)
    if (!existsSync(abs)) continue
    const oursToDelete = createdConfigs.has(p)
    let keepsSomething = true
    let tookAnything = false
    try {
      const parsed = JSON.parse(await readFile(abs, 'utf8')) as Record<string, unknown>
      // Captured before the predicate runs — it edits `parsed` in place.
      const untouched = JSON.stringify(parsed)
      keepsSomething = willKeepSomethingAfterStrip(parsed, ideFor.get(p))
      tookAnything = JSON.stringify(parsed) !== untouched
    } catch {
      // Unreadable JSON is left alone entirely, so it certainly survives.
      out.push({ path: p, outcome: 'stripped', note: 'nothing — the file could not be parsed' })
      continue
    }
    // The same three-way answer the action gives, computed the same way. The
    // preview asked only "will anything be left", so a config that was already
    // empty before OpenCastle ran was previewed as "it holds only our MCP
    // servers" — a sentence that was false about the file it was describing, and
    // the justification for deleting it.
    if (!tookAnything) {
      out.push({ path: p, outcome: 'stripped', note: 'nothing — no MCP server of ours is in it' })
      continue
    }
    out.push(
      keepsSomething || !oursToDelete
        ? { path: p, outcome: 'stripped', note: 'our MCP servers; the rest of the file stays' }
        : { path: p, outcome: 'deleted', note: 'it holds only our MCP servers' },
    )
  }

  return out
}

/**
 * Remove `dirs` that are now empty, and any empty parents up to `stop`.
 *
 * Never recursive and never forced: an entry inside means the user has
 * something there, and it stays.
 */
function pruneEmptyDirs(dirs: Iterable<string>, stop: string): void {
  for (const dir of dirs) {
    let current = dir
    while (current.startsWith(stop) && current !== stop) {
      try {
        if (readdirSync(current).length > 0) break
        rmdirSync(current)
      } catch {
        break
      }
      current = dirname(current)
    }
  }
}

/**
 * Where `.opencastle/` will be parked — the one implementation.
 *
 * The preview named `.opencastle.removed/` unconditionally while the action
 * suffixed to avoid clobbering an earlier rescue copy, so a second uninstall
 * told the user to look somewhere the files were not. One fact, one reader.
 */
export function parkedDirFor(projectRoot: string): string {
  let parked = resolve(projectRoot, '.opencastle.removed')
  let suffix = 2
  while (existsSync(parked)) parked = resolve(projectRoot, `.opencastle.removed.${suffix++}`)
  return parked
}

export default async function remove({ args }: CliContext): Promise<void> {
  if (args.includes('--help') || args.includes('-h')) {
    console.log(REMOVE_HELP)
    return
  }

  const projectRoot = process.cwd()
  const dryRun = args.includes('--dry-run')
  const assumeYes = args.includes('--yes')

  const manifest = await readManifest(projectRoot)
  if (!manifest) {
    console.error(`\n  ${c.red('✗')} No OpenCastle installation found here.`)
    console.error(`  ${c.dim('Run')} ${c.cyan('opencastle')} ${c.dim('to see project status.')}\n`)
    process.exit(1)
  }

  let mode: Mode | undefined
  if (args.includes('--all')) mode = 'all'
  else if (args.includes('--keep-files')) mode = 'keep-files'

  if (!mode) {
    const answer = await select('What should happen to the generated files?', [
      {
        label: 'Keep them (make them standalone)',
        hint: 'removes the manifest only — you can then uninstall the package',
        value: 'keep-files',
      },
      {
        label: 'Delete everything OpenCastle created',
        hint: 'cannot be undone',
        value: 'all',
      },
    ])
    mode = answer as Mode
  }

  // Not `manifest.managedPaths` directly: a manifest written before root files
  // became co-owned filed them under `framework`, and that list gets unlinked.
  const managed = await resolveManagedPaths(manifest)
  const ides = (manifest.ides?.length ? manifest.ides : [manifest.ide]).filter(
    (id): id is IdeChoice => Boolean(id) && id in IDE_ADAPTERS,
  )
  const mcpOwner = new Map(ides.map((ide) => [getMcpConfigRelPath(ide), ide]))
  const mcpPaths = new Set(mcpOwner.keys())
  // An install from before this field existed records nothing, and absence means
  // "unknown" — which is treated as "not ours to delete".
  const createdConfigs = new Set(manifest.createdConfigs ?? [])
  const frameworkPaths = managed.framework.filter((p) => !mcpPaths.has(p))
  // `.opencastle/` is handled explicitly below, so drop it here — listing it in
  // both places printed it twice and counted it twice in "Removed N path(s)".
  const customizablePaths = managed.customizable.filter(
    (p) => !mcpPaths.has(p) && p !== '.opencastle/',
  )
  const mergedPaths = managed.merged
  const legacyManifestPath = resolve(projectRoot, '.opencastle.json')
  const hasLegacy = existsSync(legacyManifestPath)

  console.log(`\n  🏰 ${c.bold('OpenCastle remove')}\n`)

  if (mode === 'keep-files') {
    console.log('  Will remove:')
    console.log(`    ${c.dim('.opencastle/manifest.json')}`)
    console.log('\n  Every generated file stays exactly where it is.')
    console.log(`  Afterwards: ${c.bold('npm uninstall opencastle')}\n`)
  } else {
    console.log(`  ${c.bold('Deleted')}\n`)
    for (const p of [...frameworkPaths, ...customizablePaths]) {
      console.log(`    ${c.red('-')} ${c.dim(p)}`)
    }
    // Named plainly: this is the one path in the list that holds writing of the
    // user's own, and the command spends the rest of its effort preserving
    // exactly that kind of content elsewhere.
    console.log(
      `    ${c.yellow('→')} ${c.dim('.opencastle/')} ${c.yellow(`moved to ${relative(projectRoot, parkedDirFor(projectRoot))}/ — your conventions and lessons`)}`,
    )
    if (hasLegacy) console.log(`    ${c.red('-')} ${c.dim('.opencastle.json')}`)

    // Co-owned files are only *sometimes* kept: one holding nothing but our
    // block is deleted. Announcing "your own writing stays" over a file about to
    // disappear is the preview lying, so each outcome is predicted rather than
    // assumed. `previewCoOwned` reads the same files the strip functions will.
    const coOwned = await previewCoOwned(projectRoot, mergedPaths, mcpPaths, mcpOwner, createdConfigs)

    // `.gitignore` joins the same two lists as every other co-owned file, rather
    // than being appended after them. Printed last, its deletion line landed
    // *under* the "Edited, not deleted" heading — the preview filing a file it
    // was about to unlink under the one heading that promises it will survive.
    const gitignoreOutcome = await predictGitignoreStrip(projectRoot)
    const gitignoreEntry =
      gitignoreOutcome === 'deleted'
        ? { path: '.gitignore', outcome: 'deleted' as const, note: 'it holds nothing but our block' }
        : gitignoreOutcome === 'stripped'
          ? { path: '.gitignore', outcome: 'stripped' as const, note: 'the OpenCastle block' }
          : null
    const entries = gitignoreEntry ? [...coOwned, gitignoreEntry] : coOwned
    const alsoDeleted = entries.filter((e) => e.outcome === 'deleted')
    const kept = entries.filter((e) => e.outcome === 'stripped')

    for (const e of alsoDeleted) {
      console.log(`    ${c.red('-')} ${c.dim(e.path)} ${c.dim(`— ${e.note}`)}`)
    }

    if (kept.length > 0) {
      console.log(`\n  ${c.bold('Edited, not deleted')}\n`)
      for (const e of kept) {
        console.log(`    ${c.yellow('~')} ${c.dim(e.path)} ${c.dim(`— removes ${e.note}`)}`)
      }
    }
    console.log()
  }

  if (dryRun) {
    console.log(`  ${c.dim('[dry-run] Nothing was changed.')}\n`)
    closePrompts()
    return
  }

  if (!assumeYes) {
    const proceed = await confirm(
      mode === 'all' ? 'Go ahead?' : 'Continue?',
      mode !== 'all',
    )
    if (!proceed) {
      console.log('  Aborted.\n')
      closePrompts()
      return
    }
  }

  if (mode === 'keep-files') {
    await unlink(resolve(projectRoot, '.opencastle', 'manifest.json')).catch(() => {})
    // An install old enough to use the flat manifest keeps being found by
    // `readManifest`, so dropping only the new path left the project still
    // reporting as installed under a heading that said otherwise.
    if (hasLegacy) await unlink(legacyManifestPath).catch(() => {})
    console.log(`\n  ${c.green('✓')} Files are now standalone.`)
    console.log(`  You can uninstall: ${c.bold('npm uninstall opencastle')}\n`)
    closePrompts()
    return
  }

  let removed = 0
  const parents = new Set<string>()
  for (const p of [...frameworkPaths, ...customizablePaths]) {
    if (p.endsWith('/')) {
      // Only if it was there. The manifest still lists paths for a target that
      // has since been dropped, so the count claimed to have removed
      // directories that had not existed for releases.
      if (existsSync(resolve(projectRoot, p))) {
        await removeDirIfExists(resolve(projectRoot, p))
        removed++
      }
    } else {
      const file = resolve(projectRoot, p)
      if (existsSync(file)) {
        await unlink(file)
        removed++
      }
    }
    const parent = dirname(resolve(projectRoot, p.replace(/\/$/, '')))
    if (parent !== projectRoot) parents.add(parent)
  }

  // Co-owned files hold the user's own writing above our block. Take back the
  // block; delete the file only if nothing of theirs remains.
  let stripped = 0
  const staleLeft: string[] = []
  for (const p of mergedPaths) {
    const abs = resolve(projectRoot, p)
    // Asked before the strip, because afterwards the markers are gone and
    // nothing can identify the superseded half again — including `doctor`,
    // which needs a manifest this command is about to remove.
    if (existsSync(abs) && (await predictStripFile(abs)).staleRemains) staleLeft.push(p)
    const outcome = await stripManagedBlockFromFile(abs)
    if (outcome === 'deleted') removed++
    else if (outcome === 'stripped') stripped++
  }

  // MCP config is co-owned the same way: we merge our servers into a file that
  // may be the assistant's entire project config. Take back the servers, not
  // the file.
  const unreadable: string[] = []
  for (const ide of ides) {
    const outcome = await stripManagedMcpServers(projectRoot, ide, createdConfigs.has(getMcpConfigRelPath(ide)))
    if (outcome === 'deleted') removed++
    else if (outcome === 'stripped') stripped++
    else if (outcome === 'unreadable') unreadable.push(getMcpConfigRelPath(ide))
    const mcpParent = dirname(resolve(projectRoot, getMcpConfigRelPath(ide)))
    if (mcpParent !== projectRoot) parents.add(mcpParent)
  }

  // The containers our own directories lived in. `.claude/agents/`, `skills/`
  // and `commands/` were each removed by name and `.claude/` itself was left
  // behind — an empty directory the user has to notice and delete, after a
  // command whose whole promise is leaving no trace.
  //
  // Deliberately after the MCP strip, not before it. Pruning first worked for
  // claude-code and opencode, whose MCP config sits at the project root, and
  // silently did nothing for the other five, whose config lives *inside* the
  // container and was therefore still there when the prune walked past. Right
  // for the first case, wrong for the rest.
  //
  // Only ever removes an empty directory, so anything of theirs inside keeps it.
  pruneEmptyDirs(parents, projectRoot)

  // `.opencastle/` holds prose the user wrote — conventions, decisions, lessons —
  // and this same command writes a backup for a root file it merely replaces.
  // `--yes` skips the confirmation, so "previewed and confirmed" is not a
  // standard that actually holds here: `remove --all --yes` is what the help
  // text and CI both use. Renamed rather than deleted, so it is one `mv` back.
  const opencastleDir = resolve(projectRoot, '.opencastle')
  let keptDir: string | undefined
  if (existsSync(opencastleDir)) {
    // A second uninstall used to delete the first one's rescue copy, which is
    // the one thing this parking is for. Suffix instead.
    const parked = parkedDirFor(projectRoot)
    await rename(opencastleDir, parked)
    // The run directories go with it, and they are empty: `sync` creates
    // `runs/`, `artifacts/`, `worktrees/` and `baselines/` on every invocation
    // whether or not anything runs. A rescue copy is meant to hold what the
    // user wrote, not four empty folders the tool made for itself — and the
    // claim is that no command leaves an empty directory of ours behind.
    pruneEmptyDirs(
      LOCAL_DIRS.map((d) => resolve(parked, d.replace(/^\.opencastle\//, ''))),
      parked,
    )
    keptDir = relative(projectRoot, parked)
    removed++
  }

  if (hasLegacy) {
    await unlink(legacyManifestPath)
    removed++
  }

  // Asked before acting, because after the strip there is nothing left to ask.
  // The summary said "+ .gitignore block" either way, which describes an edit —
  // so a run that had just unlinked the whole file reported taking a block out
  // of it, exactly the same wording as a run that left the user's rules in place.
  const gitignoreWas = await predictGitignoreStrip(projectRoot)
  const gitignoreResult = await removeGitignoreBlock(projectRoot)

  const gitignoreNote =
    gitignoreResult !== 'removed'
      ? ''
      : gitignoreWas === 'deleted'
        ? ' + deleted .gitignore'
        : ' + .gitignore block'
  console.log(
    `\n  ${c.green('✓')} Removed ${removed} path(s)` +
      `${stripped > 0 ? `, kept your content in ${stripped} file(s)` : ''}` +
      `${gitignoreNote}.`,
  )
  if (staleLeft.length > 0) {
    console.log(
      `\n  ${c.yellow('!')} ${staleLeft.length} file(s) still hold a superseded instruction set` +
        ` from an older OpenCastle release:\n`,
    )
    for (const p of staleLeft) console.log(`     ${c.dim(p)}`)
    console.log(
      `     ${c.dim('It has no markers, so this command cannot tell it from your own writing.')}`,
    )
  }
  for (const p of unreadable) {
    console.log(`  ${c.yellow('!')} Left ${p} alone — it is not valid JSON.`)
  }
  if (keptDir) {
    console.log(
      `  ${c.dim('Your conventions and lessons are in')} ${c.bold(keptDir)}${c.dim(' — delete it when you are sure.')}`,
    )
  }
  console.log(`  You can uninstall: ${c.bold('npm uninstall opencastle')}\n`)

  closePrompts()
}
