import type { ChildProcess } from 'node:child_process';

// ── Stack selection types ──────────────────────────────────────

export type IdeChoice = 'vscode' | 'cursor' | 'claude-code' | 'opencode' | 'windsurf' | 'codex' | 'antigravity';
export type TechTool = 'sanity' | 'contentful' | 'strapi' | 'supabase' | 'convex' | 'vercel' | 'nx' | 'chrome-devtools' | 'nextjs' | 'astro' | 'netlify' | 'turborepo' | 'prisma' | 'cypress' | 'playwright' | 'vitest' | 'figma' | 'resend' | 'stripe' | 'sentry' | 'drizzle' | 'cloudflare' | 'coolify' | 'expo';
export type TeamTool = 'linear' | 'jira' | 'trello' | 'notion' | 'slack' | 'teams';

export interface StackConfig {
  ides: IdeChoice[];
  techTools: TechTool[];
  teamTools: TeamTool[];
}

/** Check if a stack config uses the legacy v1 format (individual choices with 'none'). */
export function isLegacyStack(stack: unknown): stack is { cms: string; db: string; pm?: string; notifications?: string } {
  return typeof stack === 'object' && stack !== null && 'cms' in stack;
}

/** Migrate a legacy v1 stack config to the v2 array format. */
export function migrateStackConfig(
  legacy: { cms: string; db: string; pm?: string; notifications?: string },
  ide?: string
): StackConfig {
  const techTools: TechTool[] = [];
  const teamTools: TeamTool[] = [];

  if (legacy.cms && legacy.cms !== 'none') techTools.push(legacy.cms as TechTool);
  if (legacy.db && legacy.db !== 'none') techTools.push(legacy.db as TechTool);
  if (legacy.pm && legacy.pm !== 'none') teamTools.push(legacy.pm as TeamTool);
  if (legacy.notifications && legacy.notifications !== 'none') teamTools.push(legacy.notifications as TeamTool);

  const ides: IdeChoice[] = ide ? [ide as IdeChoice] : [];
  return { ides, techTools, teamTools };
}

/** Context passed from bin/cli.mjs to every command handler. */
export interface CliContext {
  pkgRoot: string;
  args: string[];
}

/** Results from a copy/install/update operation. */
export interface CopyResults {
  copied: string[];
  skipped: string[];
  created: string[];
  /** Root files replaced wholesale on upgrade; each has a `.opencastle-backup`. */
  adopted?: string[];
  /** Root files that still carry an older release's output above our block. */
  staleRoots?: string[];
  /** Files the compiler removed that it did not generate. */
  deleted?: string[];
  /**
   * Generated config files that exist but will not parse.
   *
   * Named and skipped rather than thrown: an abort here leaves the framework
   * tree written and the manifest absent, and the user is never told which
   * file to fix.
   */
  /**
   * Files that held more than one complete block and were collapsed to one.
   *
   * Distinct from `adopted`: nothing here came from an earlier release, so
   * reporting it as "replaced a file generated by an earlier version" told the
   * user the wrong story about their own file. A backup is written either way.
   */
  repaired?: string[];

  /**
   * Root files holding more than one block *and* unpaired markers.
   *
   * Not reducible without risking the user's own text, so they are named and
   * left alone rather than cut.
   */
  damagedRoots?: string[];

  unreadable?: string[];

  /**
   * Every destination the compile considered, whatever it then did to it.
   *
   * The sweep that removes output with no source left needs "did the compiler
   * account for this path", and reassembling that from created ∪ copied ∪
   * skipped makes it depend on how each write happened to be *categorised*. It
   * broke twice that way: once when `skipped` was left out of the union and the
   * first sync deleted all 79 regenerated files, once when `copied` was left
   * out and an upgrade deleted 43 skills. Recorded where the path is decided,
   * so no reporting change can move it.
   */
  visited?: string[];
  /**
   * Root files carrying a marker that belongs to no block.
   *
   * Distinct from `staleRoots`: a hand-written file that merely quotes the
   * marker has never held our output, and saying it "still contains output from
   * an earlier version" is simply false.
   */
  tornRoots?: string[];
}

/** Options for the copyDir utility. */
export interface CopyDirOptions {
  overwrite?: boolean;
  filter?: (_name: string, _srcPath: string) => boolean;
  transform?: (
    _content: string,
    _srcPath: string
  ) => Promise<string | null> | string | null;
}

/** Combined repository tooling info — auto-detected + user-declared. */
export interface RepoInfo {
  packageManager?: string;
  monorepo?: string;
  language?: string;
  frameworks?: string[];
  databases?: string[];
  cms?: string[];
  deployment?: string[];
  testing?: string[];
  cicd?: string[];
  styling?: string[];
  auth?: string[];
  pm?: string[];
  notifications?: string[];
  services?: string[];
  mcpConfig?: boolean;
  configFiles?: string[];
}

/** OpenCastle project manifest (.opencastle.json). */
export interface Manifest {
  version: string;
  ide: string;
  ides?: string[];
  installedAt: string;
  updatedAt: string;
  managedPaths?: ManagedPaths;
  stack?: StackConfig;
  repoInfo?: RepoInfo;
}

/** Framework vs customizable file paths. */
export interface ManagedPaths {
  /** Wholly generated. Safe to delete and regenerate. */
  framework: string[];
  /** The user's, never overwritten. */
  customizable: string[];
  /**
   * Co-owned: the user's prose plus a managed block. Never delete these — strip
   * the block and keep the rest. Treating them as `framework` is what let
   * `init` and `remove --all` destroy someone's CLAUDE.md.
   */
  merged?: string[];
}

/** Structure check for the doctor command — describes expected files/dirs per IDE. */
export interface DoctorCheck {
  /** Human-friendly label for the check */
  label: string;
  /** Relative path to a file or directory (ending with /) to check exists */
  path: string;
  /** 'file' or 'dir' */
  type: 'file' | 'dir';
  /** If true, counts the contents and reports count */
  countContents?: boolean;
  /** File extension filter when counting (e.g. '.md', '.mdc', '.agent.md') */
  countFilter?: string;
}

/** IDE adapter interface (init/update commands). */
export interface IdeAdapter {
  install(_pkgRoot: string, _projectRoot: string, _stack?: StackConfig, _repoInfo?: RepoInfo): Promise<CopyResults>;
  update(
    _pkgRoot: string,
    _projectRoot: string,
    _stack?: StackConfig,
    _repoInfo?: RepoInfo,
  ): Promise<CopyResults>;
  getManagedPaths(): ManagedPaths;
  getDoctorChecks(): DoctorCheck[];
}

/** Select prompt option. */
export interface SelectOption {
  label: string;
  hint?: string;
  value: string;
  /** Whether this option starts selected (preselected). */
  selected?: boolean;
}

/** Scaffold result from MCP config. */
export interface ScaffoldResult {
  path: string;
  action: 'created' | 'skipped';
}

/** IDE display labels. */
export const IDE_LABELS: Record<IdeChoice, string> = {
  vscode: 'VS Code',
  cursor: 'Cursor',
  'claude-code': 'Claude Code',
  opencode: 'OpenCode',
  windsurf: 'Windsurf',
  codex: 'Codex CLI',
  antigravity: 'Antigravity',
};

// ── Run command types ──────────────────────────────────────────

/**
 * A generated file we could not parse.
 *
 * Named, so the command can say which file and carry on. Committed generated
 * JSON is exactly what a merge conflicts on, and an unguarded `JSON.parse`
 * turned that into an abort with no filename — after the adapters had rewritten
 * the framework directories and before the manifest was written.
 */
export class UnreadableConfigError extends Error {
  /**
   * Why it could not be read.
   *
   * "It is not valid JSON" was printed for a path that was a *directory* — the
   * remedy offered ("fix the file") did not match the fault, and the user had
   * nothing to act on.
   */
  readonly reason: 'unparseable' | 'unreadable';

  constructor(
    public readonly file: string,
    reason: 'unparseable' | 'unreadable' = 'unparseable',
  ) {
    super(`Cannot read ${file}`);
    this.name = 'UnreadableConfigError';
    this.reason = reason;
  }
}
