import { stringify } from 'yaml'
import { getEffortProfile } from './effort-scaling.js'

/** The task plan generated by the LLM — just the creative decomposition, no YAML concerns */
export interface TaskPlanTask {
  id: string
  agent?: string
  description?: string
  files?: string[]
  depends_on?: string[]
  timeout?: string
  max_retries?: number
  review?: string
  complexity?: 1 | 2 | 3 | 5 | 8 | 13
  prompt: string
  gates?: string[]
  built_in_gates?: Record<string, boolean | string>
}

export interface TaskPlan {
  name: string
  branch?: string
  concurrency?: number | 'auto'
  on_failure?: 'continue' | 'stop'
  tasks: TaskPlanTask[]
  gates?: string[]
  gate_retries?: number
}

/** A patch to apply to a task plan — output of the fix-convoy prompt */
export interface TaskPatch {
  task_id: string   // task ID to patch, or "_plan" for top-level fields
  field: string     // field name (e.g., "prompt", "files", "depends_on")
  value: unknown    // new value for the field
}

function toKebabCase(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

/** Advanced spec properties derived programmatically from complexity assessment */
export interface SpecEnrichment {
  guard?: { enabled: boolean }
  circuit_breaker?: { threshold: number; cooldown_ms: number }
  detect_drift?: boolean
  built_in_gates?: Record<string, boolean | string>
  max_concurrent_reviews?: number
}

/**
 * Derives advanced convoy spec properties from a complexity assessment.
 * These are infrastructure concerns the LLM shouldn't generate — they're computed from signals.
 */
export function deriveSpecEnrichment(complexity: {
  complexity: 'low' | 'medium' | 'high'
  total_tasks: number
  domains: string[]
}): SpecEnrichment {
  const enrichment: SpecEnrichment = {}

  // Circuit breaker: higher complexity → lower threshold (trip faster)
  if (complexity.complexity === 'high') {
    enrichment.circuit_breaker = { threshold: 2, cooldown_ms: 300_000 }
  } else if (complexity.complexity === 'medium') {
    enrichment.circuit_breaker = { threshold: 3, cooldown_ms: 300_000 }
  }

  // Drift detection for medium/high
  if (complexity.complexity !== 'low') {
    enrichment.detect_drift = true
  }

  // Guard: enabled for medium/high
  if (complexity.complexity !== 'low') {
    enrichment.guard = { enabled: true }
  }

  // Built-in gates based on domains
  const domains = new Set(complexity.domains.map(d => d.toLowerCase()))
  const gates: Record<string, boolean | string> = {
    secret_scan: true,
    blast_radius: true,
  }

  if (domains.has('frontend') || domains.has('ui')) {
    gates.browser_test = 'auto'
  }
  if (domains.has('testing') || complexity.total_tasks > 5) {
    gates.regression_test = 'auto'
  }
  if (domains.has('database') || domains.has('api') || domains.has('backend')) {
    gates.dependency_audit = 'auto'
  }

  enrichment.built_in_gates = gates

  // Review concurrency scales with task count
  enrichment.max_concurrent_reviews = complexity.total_tasks > 6 ? 3 : 2

  return enrichment
}

/**
 * Converts a TaskPlan into a valid convoy YAML string with a comment header.
 */
export function buildConvoyYaml(plan: TaskPlan, enrichment?: SpecEnrichment): string {
  const tasks = plan.tasks.map((task) => {
    const t: Record<string, unknown> = {}
    t.id = task.id
    t.agent = task.agent ?? 'developer'
    t.description = task.description ?? task.id
    if (task.timeout !== undefined) t.timeout = task.timeout
    if (task.files && task.files.length > 0) t.files = task.files
    if (task.depends_on && task.depends_on.length > 0) t.depends_on = task.depends_on
    if (task.max_retries !== undefined) t.max_retries = task.max_retries
    if (task.review !== undefined) t.review = task.review
    if (task.gates !== undefined) t.gates = task.gates
    if (task.built_in_gates !== undefined) t.built_in_gates = task.built_in_gates
    // Auto-populate from effort table when complexity is set and fields are missing
    if (task.complexity !== undefined) {
      const profile = getEffortProfile(task.complexity)
      if (t.timeout === undefined) t.timeout = profile.timeout
      if (t.max_retries === undefined) t.max_retries = profile.max_retries
      if (t.review === undefined) t.review = profile.review
    }
    // prompt last — keeps the long text at the end of each task block
    t.prompt = task.prompt
    return t
  })

  const spec: Record<string, unknown> = {
    name: plan.name,
    version: 1,
    concurrency: plan.concurrency ?? 2,
    on_failure: plan.on_failure ?? 'stop',
  }

  if (plan.branch !== undefined) spec.branch = plan.branch

  const defaults: Record<string, unknown> = {
    timeout: '30m',
    max_retries: 1,
    review: 'fast',
  }

  if (enrichment?.circuit_breaker) defaults.circuit_breaker = enrichment.circuit_breaker
  if (enrichment?.detect_drift) defaults.detect_drift = enrichment.detect_drift
  if (enrichment?.built_in_gates) defaults.built_in_gates = enrichment.built_in_gates
  if (enrichment?.max_concurrent_reviews) defaults.max_concurrent_reviews = enrichment.max_concurrent_reviews

  spec.defaults = defaults

  // guard is spec-level (not inside defaults)
  if (enrichment?.guard) spec.guard = enrichment.guard

  spec.tasks = tasks

  if (plan.gates !== undefined) spec.gates = plan.gates
  if (plan.gate_retries !== undefined) spec.gate_retries = plan.gate_retries

  const header = `# .opencastle/convoys/${toKebabCase(plan.name)}.convoy.yml\n`
  const yaml = stringify(spec, {
    lineWidth: 120,
    defaultKeyType: 'PLAIN',
    defaultStringType: 'PLAIN',
  })
  return header + yaml
}

/**
 * Applies an array of patches to a task plan. Returns a new TaskPlan (immutable).
 */
export function applyPatches(plan: TaskPlan, patches: TaskPatch[]): TaskPlan {
  const clone = structuredClone(plan)
  let skipped = 0
  for (const patch of patches) {
    if (patch.task_id === '_plan') {
      ;(clone as unknown as Record<string, unknown>)[patch.field] = patch.value
    } else {
      const task = clone.tasks.find((t) => t.id === patch.task_id)
      if (task) {
        ;(task as unknown as Record<string, unknown>)[patch.field] = patch.value
      } else {
        console.warn(`  ⚠ applyPatches: patch targets unknown task "${patch.task_id}" — skipping`)
        skipped++
      }
    }
  }
  if (skipped > 0) {
    console.warn(`  ⚠ applyPatches: ${skipped} of ${patches.length} patches skipped (unknown task IDs)`)
  }
  return clone
}

/**
 * Detects whether a JSON string appears to be truncated (output cut off mid-generation).
 * Returns a descriptive reason string, or null if the JSON looks complete.
 */
function detectJsonTruncation(jsonText: string): string | null {
  const trimmed = jsonText.trim()
  if (!trimmed) return 'empty output'

  // Count open/close braces and brackets
  let braces = 0
  let brackets = 0
  let inString = false
  let prevChar = ''
  for (const ch of trimmed) {
    if (ch === '"' && prevChar !== '\\') {
      inString = !inString
    } else if (!inString) {
      if (ch === '{') braces++
      else if (ch === '}') braces--
      else if (ch === '[') brackets++
      else if (ch === ']') brackets--
    }
    prevChar = ch
  }

  if (braces > 0 || brackets > 0) {
    return `output truncated (${braces} unclosed braces, ${brackets} unclosed brackets) — the LLM likely hit its output token limit`
  }

  return null
}

/**
 * Result of parsing a task plan JSON. Contains either a valid plan or a diagnostic reason.
 */
export interface ParseTaskPlanResult {
  plan: TaskPlan | null
  reason?: string
}

/**
 * Parses a JSON string into a TaskPlan. Returns null if parsing fails or required fields are missing.
 */
export function parseTaskPlan(jsonText: string): TaskPlan | null {
  return parseTaskPlanWithReason(jsonText).plan
}

/**
 * Like parseTaskPlan but returns a diagnostic reason on failure.
 */
export function parseTaskPlanWithReason(jsonText: string): ParseTaskPlanResult {
  const truncation = detectJsonTruncation(jsonText)
  if (truncation) {
    console.warn(`  ⚠ parseTaskPlan: ${truncation}`)
    return { plan: null, reason: truncation }
  }

  let parsed: Record<string, unknown>
  try {
    parsed = JSON.parse(jsonText.trim()) as Record<string, unknown>
  } catch (err) {
    return { plan: null, reason: `JSON.parse failed: ${err instanceof Error ? err.message : String(err)}` }
  }

  if (!parsed || typeof parsed.name !== 'string') {
    return { plan: null, reason: `missing or invalid top-level "name" field (got ${typeof parsed?.name})` }
  }
  if (!Array.isArray(parsed.tasks) || (parsed.tasks as unknown[]).length === 0) {
    return { plan: null, reason: `missing or empty "tasks" array` }
  }
  for (let i = 0; i < (parsed.tasks as unknown[]).length; i++) {
    const t = (parsed.tasks as unknown[])[i] as Record<string, unknown>
    if (typeof t.id !== 'string') {
      return { plan: null, reason: `task[${i}] missing "id" field` }
    }
    if (typeof t.prompt !== 'string') {
      return { plan: null, reason: `task "${t.id ?? i}" missing "prompt" field (has keys: ${Object.keys(t).join(', ')})` }
    }
    if ((t.prompt as string).length === 0) {
      return { plan: null, reason: `task "${t.id}" has empty "prompt" field` }
    }
  }

  // Validate unique task IDs
  const tasks = parsed.tasks as Array<Record<string, unknown>>
  const ids = new Set<string>()
  const duplicates: string[] = []
  for (const task of tasks) {
    const id = task.id as string
    if (ids.has(id)) duplicates.push(id)
    ids.add(id)
  }
    if (duplicates.length > 0) {
    console.warn(`  ⚠ parseTaskPlan: duplicate task IDs: ${duplicates.join(', ')}`)
    return { plan: null, reason: `duplicate task IDs: ${duplicates.join(', ')}` }
  }

  // Validate depends_on references
  for (const task of tasks) {
    if (Array.isArray(task.depends_on)) {
      for (const dep of task.depends_on as string[]) {
        if (!ids.has(dep)) {
          console.warn(`  ⚠ parseTaskPlan: task "${task.id as string}" depends on unknown task "${dep}"`)
          return { plan: null, reason: `task "${task.id as string}" depends on unknown task "${dep}"` }
        }
      }
    }
  }

  // Cycle detection (Kahn's algorithm)
  const inDegree = new Map<string, number>()
  const adj = new Map<string, string[]>()
  for (const id of ids) {
    inDegree.set(id, 0)
    adj.set(id, [])
  }
  for (const task of tasks) {
    if (Array.isArray(task.depends_on)) {
      for (const dep of task.depends_on as string[]) {
        adj.get(dep)!.push(task.id as string)
        inDegree.set(task.id as string, (inDegree.get(task.id as string) ?? 0) + 1)
      }
    }
  }
  const queue = [...ids].filter(id => inDegree.get(id) === 0)
  let visited = 0
  while (queue.length > 0) {
    const node = queue.shift()!
    visited++
    for (const next of adj.get(node) ?? []) {
      const deg = (inDegree.get(next) ?? 1) - 1
      inDegree.set(next, deg)
      if (deg === 0) queue.push(next)
    }
  }
  if (visited < ids.size) {
    console.warn(`  ⚠ parseTaskPlan: dependency cycle detected`)
    return { plan: null, reason: 'dependency cycle detected' }
  }

  return { plan: parsed as unknown as TaskPlan }
}

/**
 * Parses a JSON string into a TaskPatch[]. Returns null if parsing fails.
 */
export function parsePatches(jsonText: string): TaskPatch[] | null {
  try {
    const parsed = JSON.parse(jsonText.trim())
    if (!Array.isArray(parsed)) return null
    for (const item of parsed as unknown[]) {
      const p = item as Record<string, unknown>
      if (typeof p.task_id !== 'string' || typeof p.field !== 'string' || p.value === undefined) {
        return null
      }
    }
    return parsed as TaskPatch[]
  } catch {
    return null
  }
}
