#!/bin/bash
# Self-verification of the branch's stated claims, driving the CLI.
# Written in bash (not zsh) so unquoted expansion word-splits as expected;
# `timeout` does not exist on this machine, so nothing relies on it.
set -u
CLI="$(cd "$(dirname "$0")/.." && pwd)/bin/cli.mjs"
ROOT=$(mktemp -d)
PASS=0; FAIL=0
ok()   { echo "  ok   $1"; PASS=$((PASS+1)); }
bad()  { echo "  FAIL $1"; FAIL=$((FAIL+1)); }
say()  { echo; echo "$1"; }

new() { d="$ROOT/$1"; rm -rf "$d"; mkdir -p "$d"; cd "$d" || exit 1; git init -q; }

START='<!-- >>> OpenCastle managed — regenerated by `opencastle sync`, edits here are lost >>> -->'
END='<!-- <<< OpenCastle managed <<< -->'

say "CLAIM 1 — one complete block, from any starting content"
for shape in plain unclosed-fence quoted-block quoted-start-only trailing-rule crlf; do
  new "c1-$shape"
  case $shape in
    plain)          printf '# Mine\n\nkeep\n' > CLAUDE.md ;;
    unclosed-fence) printf '# Mine\n\n```sh\nmake\n\nkeep\n' > CLAUDE.md ;;
    quoted-block)   printf '# Mine\n\n```md\n%s\nx\n%s\n```\n\nkeep\n' "$START" "$END" > CLAUDE.md ;;
    quoted-start-only) printf '# Mine\n\n```md\n%s\n```\n\nRULE 1\nRULE 2\n' "$START" > CLAUDE.md ;;
    trailing-rule)  printf '# Mine\n\nkeep\n\n---\n' > CLAUDE.md ;;
    crlf)           printf '# Mine\r\n\r\nkeep\r\n' > CLAUDE.md ;;
  esac
  cp CLAUDE.md "$ROOT/$shape.orig"
  node $CLI init --yes >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  # A fixture that already held a complete quoted block keeps it: that is the
  # user's documentation, and ours goes below. Every other shape ends with one.
  case $shape in quoted-block) want=2 ;; *) want=1 ;; esac
  n=$(grep -c -- "$END" CLAUDE.md)
  if [ "$n" = "$want" ]; then ok "$shape: $want block(s) after init+2 syncs"
  else bad "$shape: $n blocks, wanted $want"; fi
  node $CLI remove --all --yes >/dev/null 2>&1
  # Our *body* must be gone. A quoted example keeps its markers, because those
  # are the user's text, so markers alone are not the test.
  if [ -f CLAUDE.md ] && grep -q "Project Instructions" CLAUDE.md; then
    bad "$shape: our body survived uninstall"
  else ok "$shape: uninstall left nothing of ours"; fi
  # The user's own bytes, not just ours. The harness used to check only that our
  # markers were gone, so it passed on a file whose rules had been deleted.
  # A file holding a *complete* quoted block has that block adopted — recorded
  # in `blockRegions` as the price of never guessing which marker is ours. Every
  # other shape must come back byte for byte.
  if false; then :
  else
    # Everything except OpenCastle's own marker lines must come back byte for
    # byte. A marker line is text this tool authored, so taking it even out of
    # someone's quoted example loses nothing they wrote; anything else would.
    grep -v -F -- "$START" "$ROOT/$shape.orig" > "$ROOT/$shape.expect"
    grep -v -F -- "$START" CLAUDE.md > "$ROOT/$shape.actual" 2>/dev/null || true
    if cmp -s "$ROOT/$shape.expect" "$ROOT/$shape.actual"; then
      ok "$shape: user half byte-identical"
    else
      bad "$shape: user half changed"
      diff "$ROOT/$shape.expect" "$ROOT/$shape.actual" | head -4
    fi
  fi
done

say "CLAIM 1b — a doubled block heals on a plain sync"
new c1b; printf '# Mine\n\nKEEP\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 - "$START" "$END" <<'PY'
import sys, pathlib
S, E = sys.argv[1], sys.argv[2]
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
a, b = t.index(S), t.index(E) + len(E)
p.write_text(t[:a] + t[a:b].replace('# Project Instructions', '# Project Instructions\n\nSTALE') + '\n\n' + t[a:])
PY
node $CLI sync --check >/dev/null 2>&1 && bad "doubled file not reported as drift" || ok "doubled file reported as drift"
node $CLI sync --yes >/dev/null 2>&1
[ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "plain sync collapsed it" || bad "still doubled"
grep -q STALE CLAUDE.md && bad "stale half survived" || ok "stale half gone"

say "CLAIM 1e — a documented example does not capture the real block"
for side in below above; do
  new "c1e-$side"; printf '# Mine\n\nkeep\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  python3 -c "
import pathlib, sys
S=sys.argv[1]; E=sys.argv[2]
doc = chr(10)+'## How this works'+chr(10)*2+'\`\`\`md'+chr(10)+S+chr(10)+'...example...'+chr(10)+E+chr(10)+'\`\`\`'+chr(10)
p=pathlib.Path('CLAUDE.md'); t=p.read_text()
p.write_text(t+doc if sys.argv[3]=='below' else doc+t)
" "$START" "$END" "$side"
  node $CLI sync --yes --force >/dev/null 2>&1
  [ "$(grep -c -- "$END" CLAUDE.md)" = "2" ] && ok "doc $side: one real block plus the example" \
                                             || bad "doc $side: block count wrong"
  python3 -c "
import pathlib, sys
t = pathlib.Path('CLAUDE.md').read_text()
i = t.index('\`\`\`md'); seg = t[i:t.index('\`\`\`', i+5)]
sys.exit(1 if 'Project Instructions' in seg else 0)
" && ok "doc $side: our body stayed out of the user's fence" \
   || bad "doc $side: our body was written into the user's fence"
done

say "CLAIM 2 — a lone start marker is never interpreted"
new c2; printf '# Mine\n\nmy rules\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace(sys.argv[1] + chr(10), ''))
" "$END"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "torn file does not grow" || bad "torn file grew"
node $CLI doctor 2>&1 | grep -q "belongs to no block" && ok "doctor names the torn file" || bad "doctor silent about it"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q "my rules" CLAUDE.md 2>/dev/null && ok "user prose kept" || bad "user prose lost"
grep -q -- "$START" CLAUDE.md 2>/dev/null && bad "our marker survived" || ok "our marker taken"

# Torn the other way: start marker deleted, end marker surviving. This shape had
# no fixture, so it went unreported and kept its whole body through an uninstall.
new c2-mirror; printf '# Mine\n\nkeep\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
grep -v -- '^<!-- >>> OpenCastle managed' CLAUDE.md > t && mv t CLAUDE.md
node $CLI doctor 2>&1 | grep -q "belongs to no block" && ok "doctor names it torn the other way" || bad "doctor silent on the mirror shape"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q "keep" CLAUDE.md 2>/dev/null && ok "mirror: user prose kept" || bad "mirror: user prose lost"
grep -q 'OpenCastle managed' CLAUDE.md 2>/dev/null && bad "mirror: our marker survived" || ok "mirror: our markers taken"

# Neither ordering may delete or duplicate the user's text.
for side in above below; do
  new "c2-$side"; printf '# Mine\n\nBEFORE\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  if [ "$side" = below ]; then
    printf '\nMIDDLE\n\n%s\n\nAFTER\n' "$START" >> CLAUDE.md
  else
    python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
p.write_text(t.replace('BEFORE' + chr(10), 'BEFORE' + chr(10)*2 + sys.argv[1] + chr(10)*2 + 'MIDDLE' + chr(10), 1))
" "$START"
  fi
  node $CLI remove --all --yes >/dev/null 2>&1
  clean=1
  for line in BEFORE MIDDLE; do
    n=$(grep -c "^$line$" CLAUDE.md 2>/dev/null || echo 0)
    [ "$n" = "1" ] || clean=0
  done
  [ "$clean" = "1" ] && ok "marker $side the block: nothing lost or duplicated" \
                     || bad "marker $side the block: text lost or duplicated"
done

say "CLAIM 3 — byte fidelity, root file and .gitignore"
for shape in lf crlf fenced blanks no-eol-newline; do
  new "c3-$shape"
  case $shape in
    lf)     printf '# A\n\nUse pnpm.\n' > CLAUDE.md ;;
    crlf)   printf '# A\r\n\r\nUse pnpm.\r\n' > CLAUDE.md ;;
    fenced) printf '# A\n\n```text\nkeep\n\n\n\nthese\n```\n' > CLAUDE.md ;;
    blanks) printf '# A\n\n\n\nspaced\n' > CLAUDE.md ;;
    no-eol-newline) printf '# A\n\nUse pnpm.' > CLAUDE.md ;;
  esac
  printf 'node_modules\n\n\ndist/\n' > .gitignore
  cp CLAUDE.md /tmp/v-root; cp .gitignore /tmp/v-gi
  node $CLI init --yes >/dev/null 2>&1
  node $CLI remove --all --yes >/dev/null 2>&1
  cmp -s /tmp/v-root CLAUDE.md && ok "$shape: root file byte-identical" || bad "$shape: root file differs"
  cmp -s /tmp/v-gi .gitignore && ok "$shape: .gitignore byte-identical" || bad "$shape: .gitignore differs"
done

say "CLAIM 4 — sync does not touch what it did not create"
new c4; echo '{"name":"p","dependencies":{"@supabase/supabase-js":"^2"}}' > package.json
node $CLI init --yes >/dev/null 2>&1
find .opencastle -name '*.md' -type f -exec sh -c 'printf "\nSENTINEL\n" >> "$1"' _ {} \;
before=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/agents/skill-matrix.json');d=json.load(open(p))
d['bindings']['framework']['entries']=[{'name':'Mine','skill':'my-skill'}]
json.dump(d,open(p,'w'),indent=2)"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
after=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
[ "$before" = "$after" ] && ok "all $after hand edits survived" || bad "lost $((before-after)) of $before"
grep -q my-skill .opencastle/agents/skill-matrix.json && ok "hand-set matrix entry survived" || bad "matrix entry erased"

say "CLAIM 5 — unparseable generated JSON is named, not fatal"
new c5; echo '{"name":"p","version":"1.0.0"}' > package.json
node $CLI init --yes >/dev/null 2>&1
mcp=$(ls .vscode/mcp.json .mcp.json 2>/dev/null | head -1)
python3 - "$mcp" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); l = p.read_text().split('\n')
l.insert(2, '<<<<<<< HEAD\n=======\n>>>>>>> feat'); p.write_text('\n'.join(l))
PY
out=$(node $CLI sync --force --yes </dev/null 2>&1); code=$?
[ $code -eq 0 ] && ok "sync completed" || bad "sync exited $code"
echo "$out" | grep -q "$mcp" && ok "named the file" || bad "did not name the file"

say "CLAIM 6 — doctor remedies work; status agrees with doctor"
for breakage in agents matrix gitignored; do
  new "c6-$breakage"; printf '# R\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  case $breakage in
    agents)     rm -rf .opencastle/agents ;;
    matrix)     rm -f .opencastle/agents/skill-matrix.json ;;
    gitignored) printf 'node_modules\n.claude/\n' > .gitignore ;;
  esac

  node $CLI doctor >/dev/null 2>&1 && { bad "$breakage: doctor no longer detects this"; continue; }
  ok "$breakage: doctor reports it"

  node $CLI 2>&1 | grep -q "Everything is current" \
    && bad "$breakage: status green while doctor red" || ok "$breakage: status agrees"

  # Run whatever doctor printed as the remedy — not an assumed `sync`. A failure
  # only a person can clear must say so instead of naming a command.
  remedy=$(node $CLI doctor 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | grep -oE 'npx opencastle [a-z-]+' | head -1)
  if [ -n "$remedy" ]; then
    node $CLI ${remedy#npx opencastle } --yes >/dev/null 2>&1
    node $CLI doctor >/dev/null 2>&1 && ok "$breakage: '$remedy' cleared it" \
                                     || bad "$breakage: '$remedy' did not clear it"
  else
    node $CLI doctor 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | grep -q "by hand\|remove those entries" \
      && ok "$breakage: names a fix only a person can apply" \
      || bad "$breakage: no actionable remedy given"
  fi
done

say "CLAIM 12b — a failing command leaves the install coherent"
new c12b; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib
p=pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace('# Project Instructions','# CHANGED'))"
chmod 444 CLAUDE.md
node $CLI sync --yes --force >/dev/null 2>&1
chmod 644 CLAUDE.md
[ "$(ls .claude/agents 2>/dev/null | wc -l | tr -d ' ')" -gt 0 ] \
  && ok "a failed sync left the framework directories intact" \
  || bad "a failed sync emptied the framework directories"

say "CLAIM 12c — every adapter names what it deletes"
for ide in claude-code vscode cursor; do
  new "c12c-$ide"
  case $ide in
    claude-code) printf '# R\n' > CLAUDE.md; d=.claude/agents ;;
    vscode)      d=.github/instructions ;;
    cursor)      printf 'x\n' > .cursorrules; d=.cursor/rules ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  mkdir -p "$d"; echo mine > "$d/MY-OWN.md"
  node $CLI sync --yes --force 2>&1 | grep -q "MY-OWN.md" \
    && ok "$ide names the file it removed" || bad "$ide deleted it in silence"
done

say "CLAIM 7 — every entry point preserves the stack"
new c7; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
node $CLI add sentry >/dev/null 2>&1
for cmd in "init --yes" "sync --yes --force"; do
  node $CLI $cmd >/dev/null 2>&1
  python3 -c "
import json,sys
s=json.load(open('.opencastle/manifest.json'))['stack']['techTools']
sys.exit(0 if 'sentry' in s else 1)" && ok "$cmd kept sentry" || bad "$cmd dropped sentry"
done

say "CLAIM 11/12 — stdin closed, and dry runs write nothing"
new c11; printf '# R\n' > CLAUDE.md
node $CLI init --yes </dev/null >/dev/null 2>&1 && ok "init --yes" || bad "init --yes"
node $CLI sync --reconfigure --yes </dev/null >/dev/null 2>&1 && ok "sync --reconfigure --yes" || bad "sync --reconfigure --yes"
node $CLI add sentry </dev/null >/dev/null 2>&1 && ok "add" || bad "add"
# Content, not just paths — the previous version compared `find` output, so a
# dry run that rewrote a file would have passed.
tree_hash() { find . -path ./.git -prune -o -type f -print0 | sort -z | xargs -0 shasum | shasum; }
before=$(tree_hash)
node $CLI sync --dry-run </dev/null >/dev/null 2>&1
node $CLI remove --all --dry-run </dev/null >/dev/null 2>&1
after=$(tree_hash)
[ "$before" = "$after" ] && ok "dry runs wrote nothing (content hashed)" || bad "dry run changed the tree"

say "CLAIM 8 — the removal preview matches the action, including .gitignore"
new c8; printf '# Mine\n\nKEEP\n' > CLAUDE.md; printf 'node_modules\n' > .gitignore
node $CLI init --yes >/dev/null 2>&1
preview=$(node $CLI remove --all --dry-run 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
node $CLI remove --all --yes >/dev/null 2>&1
echo "$preview" | grep -q 'Edited, not deleted' && ok "preview has an edited section" || bad "no edited section"
grep -q KEEP CLAUDE.md && ok "a file previewed as edited still exists" || bad "previewed as edited, then deleted"
grep -q node_modules .gitignore && ok ".gitignore kept the user's rules" || bad ".gitignore lost the user's rules"

say "CLAIM 9 — a v1 manifest is migrated, not crashed on"
new c9; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json');m=json.load(open(p))
m['stack']={'cms':'sanity','db':'supabase','pm':'linear'}
json.dump(m,open(p,'w'),indent=2)"
node $CLI sync --yes --force >/dev/null 2>&1 && ok "sync survived a v1 stack" || bad "sync crashed"
node $CLI doctor >/dev/null 2>&1; [ $? -le 1 ] && ok "doctor survived a v1 stack" || bad "doctor crashed"
python3 -c "
import json,sys
s=json.load(open('.opencastle/manifest.json'))['stack']
sys.exit(0 if 'techTools' in s else 1)" && ok "manifest migrated to v2" || bad "manifest not migrated"

say "CLAIM 10 — nothing shipped names a command that does not exist"
cd /Users/filip/repos/MonkiLabs/opencastle
npx vitest run src/cli/docs-accuracy.test.ts >/dev/null 2>&1 && ok "docs-accuracy guards pass" || bad "docs-accuracy failing"

say "CLAIM 1c — a doubled .gitignore block heals and uninstalls"
new c1c; printf 'node_modules\ndist/\n' > .gitignore; cp .gitignore "$ROOT/gi.orig"
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib,re
p=pathlib.Path('.gitignore');t=p.read_text()
m=re.search(r'# >>> OpenCastle managed.*?# <<< OpenCastle managed <<<',t,re.S)
p.write_text(t[:m.end()] + '\n\n' + m.group(0) + t[m.end():])"
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(grep -c '>>> OpenCastle managed' .gitignore)" = "1" ] && ok "sync collapsed the doubled block" || bad "still doubled"
node $CLI remove --all --yes >/dev/null 2>&1
cmp -s "$ROOT/gi.orig" .gitignore && ok ".gitignore restored byte-identical" || bad ".gitignore not restored"

# Separated by a single newline, with a user rule below — the shape that welded
# `.env.local` into a comment and stopped git ignoring it.
new c1d; printf 'node_modules\n' > .gitignore; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
printf '.env.local\n' >> .gitignore
python3 -c "
import pathlib,re
p=pathlib.Path('.gitignore');t=p.read_text()
m=re.search(r'# >>> OpenCastle managed.*?# <<< OpenCastle managed <<<',t,re.S)
p.write_text(t[:m.end()]+chr(10)+m.group(0)+t[m.end():])"
node $CLI sync --yes --force >/dev/null 2>&1
git check-ignore -q .env.local && ok "a user rule below a doubled block survives" || bad "user rule welded into a comment"

say "CLAIM 4b — init does not rewrite .opencastle/ either"
new c4b; echo '{"name":"p","dependencies":{"@supabase/supabase-js":"^2"}}' > package.json
printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
find .opencastle -name '*.md' -type f -exec sh -c 'printf "\nSENTINEL\n" >> "$1"' _ {} \;
b=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
node $CLI init --yes >/dev/null 2>&1
a=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
[ "$b" = "$a" ] && ok "init kept all $a hand edits" || bad "init lost $((b-a)) of $b"

echo
echo "════ $PASS passed, $FAIL failed ════"
cd /; rm -rf "$ROOT"
exit $([ $FAIL -eq 0 ] && echo 0 || echo 1)
