#!/bin/bash
# Self-verification of the branch's stated claims, driving the CLI.
# Written in bash (not zsh) so unquoted expansion word-splits as expected;
# `timeout` does not exist on this machine, so nothing relies on it.
set -u
REPO="$(cd "$(dirname "$0")/.." && pwd)"
CLI="$REPO/bin/cli.mjs"
ROOT=$(mktemp -d)
PASS=0; FAIL=0
ok()   { echo "  ok   $1"; PASS=$((PASS+1)); }
bad()  { echo "  FAIL $1"; FAIL=$((FAIL+1)); }
say()  { echo; echo "$1"; }
# The CLI styles its output, so a literal grep for "Updated 0 framework files"
# can never match: the count is wrapped in bold. An assertion that can never
# match is an assertion that always reports whatever its else-branch says, and
# two of the checks below were passing for that reason alone.
plain() { sed $'s/\033\[[0-9;]*m//g'; }

new() { d="$ROOT/$1"; rm -rf "$d"; mkdir -p "$d"; cd "$d" || exit 1; git init -q; }

START='<!-- >>> OpenCastle managed — regenerated by `opencastle sync`, edits here are lost >>> -->'
END='<!-- <<< OpenCastle managed <<< -->'

say "CLAIM 1 — one complete block, from any starting content"
for shape in plain unclosed-fence quoted-block quoted-start-only trailing-rule crlf; do
  new "c1-$shape"
  case $shape in
    plain)          printf '# Mine\n\nkeep\n' > CLAUDE.md ;;
    unclosed-fence) printf '# Mine\n\n```sh\nmake\n\nkeep\n' > CLAUDE.md ;;
    quoted-block)   printf '# Mine\n\n```md\n%s\nx\n%s\n```\n\nkeep\n' "$START" "$END" > CLAUDE.md ;;
    quoted-start-only) printf '# Mine\n\n```md\n%s\n```\n\nRULE 1\nRULE 2\n' "$START" > CLAUDE.md ;;
    trailing-rule)  printf '# Mine\n\nkeep\n\n---\n' > CLAUDE.md ;;
    crlf)           printf '# Mine\r\n\r\nkeep\r\n' > CLAUDE.md ;;
  esac
  cp CLAUDE.md "$ROOT/$shape.orig"
  node $CLI init --yes >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  # One block, from every shape. A fixture that already held a complete block
  # inside a fence has it collapsed into the one we maintain: a complete marker
  # pair is this tool's wherever it sits, which is the only reading the writer,
  # the checker, the collapse and the uninstall have ever managed to share.
  want=1
  n=$(grep -c -- "$END" CLAUDE.md)
  if [ "$n" = "$want" ]; then ok "$shape: $want block(s) after init+2 syncs"
  else bad "$shape: $n blocks, wanted $want"; fi
  node $CLI remove --all --yes >/dev/null 2>&1
  # Our *body* must be gone. A quoted example keeps its markers, because those
  # are the user's text, so markers alone are not the test.
  if [ -f CLAUDE.md ] && grep -q "Project Instructions" CLAUDE.md; then
    bad "$shape: our body survived uninstall"
  else ok "$shape: uninstall left nothing of ours"; fi
  # The user's own bytes, not just ours. The harness used to check only that our
  # markers were gone, so it passed on a file whose rules had been deleted.
  # A file holding a *complete* quoted block has that block adopted — recorded
  # in `blockRegions` as the price of never guessing which marker is ours. Every
  # other shape must come back byte for byte.
  # Everything except OpenCastle's own marker lines must come back byte for
  # byte. A marker line is text this tool authored, so taking it even out of
  # someone's quoted example loses nothing they wrote; anything else would.
  # Filtering it from *both* sides is deliberate and is a real exception to
  # "byte for byte" — so it is asserted separately, immediately below, rather
  # than hidden by the filter.
  # `quoted-block` is compared on prose only: its marker pair *and* the body
  # between them are ours, so they do not come back. Every other shape must.
  if [ "$shape" = quoted-block ]; then
    grep -v -x -F -e "$START" -e "$END" -e 'x' "$ROOT/$shape.orig" > "$ROOT/$shape.expect"
    grep -v -x -F -e "$START" -e "$END" -e 'x' CLAUDE.md > "$ROOT/$shape.actual" 2>/dev/null || true
  else
    grep -v -F -- "$START" "$ROOT/$shape.orig" > "$ROOT/$shape.expect"
    grep -v -F -- "$START" CLAUDE.md > "$ROOT/$shape.actual" 2>/dev/null || true
  fi
  if cmp -s "$ROOT/$shape.expect" "$ROOT/$shape.actual"; then
    ok "$shape: user half byte-identical"
  else
    bad "$shape: user half changed"
    diff "$ROOT/$shape.expect" "$ROOT/$shape.actual" | head -4
  fi
  # The exception, stated rather than filtered: a marker line is text this tool
  # authored, so it is taken back even from inside the user's fence — together
  # with the block body it delimits. Their prose and their fence stay.
  case $shape in
    quoted-block)
      grep -q -F -- "$START" CLAUDE.md \
        && bad "$shape: a marker pair survived uninstall" \
        || ok "$shape: marker pair taken, prose kept (documented exception)"
      grep -q '```md' CLAUDE.md \
        && ok "$shape: the user's fence survives" \
        || bad "$shape: the user's fence was removed" ;;
    quoted-start-only)
      grep -q -F -- "$START" CLAUDE.md \
        && bad "$shape: a lone quoted marker survived" \
        || ok "$shape: a lone quoted marker is taken (documented exception)" ;;
  esac
done

say "CLAIM 1b — a doubled block heals on a plain sync"
new c1b; printf '# Mine\n\nKEEP\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 - "$START" "$END" <<'PY'
import sys, pathlib
S, E = sys.argv[1], sys.argv[2]
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
a, b = t.index(S), t.index(E) + len(E)
p.write_text(t[:a] + t[a:b].replace('# Project Instructions', '# Project Instructions\n\nSTALE') + '\n\n' + t[a:])
PY
node $CLI sync --check >/dev/null 2>&1 && bad "doubled file not reported as drift" || ok "doubled file reported as drift"
node $CLI sync --yes >/dev/null 2>&1
[ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "plain sync collapsed it" || bad "still doubled"
grep -q STALE CLAUDE.md && bad "stale half survived" || ok "stale half gone"

say "CLAIM 1e — a second complete block is collapsed, wherever it sits"
for side in below above; do
  new "c1e-$side"; printf '# Mine\n\nkeep\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  python3 -c "
import pathlib, sys
S=sys.argv[1]; E=sys.argv[2]
doc = chr(10)+'## How this works'+chr(10)*2+'\`\`\`md'+chr(10)+S+chr(10)+'...example...'+chr(10)+E+chr(10)+'\`\`\`'+chr(10)
p=pathlib.Path('CLAUDE.md'); t=p.read_text()
p.write_text(t+doc if sys.argv[3]=='below' else doc+t)
" "$START" "$END" "$side"
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  [ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "doc $side: collapsed to one block" \
                                             || bad "doc $side: $(grep -c -- "$END" CLAUDE.md) blocks"
  grep -q '## How this works' CLAUDE.md && ok "doc $side: their heading kept" \
                                        || bad "doc $side: their heading lost"
  grep -q '```md' CLAUDE.md && ok "doc $side: their fence kept" || bad "doc $side: their fence lost"
  grep -q 'keep' CLAUDE.md && ok "doc $side: their prose kept" || bad "doc $side: their prose lost"
  [ -f CLAUDE.md.opencastle-backup ] && ok "doc $side: a backup was written" \
                                     || bad "doc $side: collapsed without a backup"
  node $CLI sync --check >/dev/null 2>&1 && ok "doc $side: check clean" || bad "doc $side: drift remains"
done

say "CLAIM 1f — a block the user fenced is still ours, and still leaves one"
# The shape that defeated six versions of a "is this quoted?" test: an unpaired
# fence above the block, a bare fence below it. Every version disowned the block
# — check red forever, an upgrade appending a second 20KB body that every
# command called healthy, and our whole body left behind by `remove --all`.
for shape in wrapped unpaired; do
  new "c1f-$shape"
  case $shape in
    wrapped)  printf '# House rules\n\nUse pnpm.\n' > CLAUDE.md ;;
    unpaired) printf '# House rules\n\nA snippet that never got closed:\n\n```\n' > CLAUDE.md ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  if [ "$shape" = wrapped ]; then
    python3 -c "
import pathlib, sys
p=pathlib.Path('CLAUDE.md'); t=p.read_text(); i=t.index(sys.argv[1])
p.write_text(t[:i] + '\`\`\`' + chr(10) + t[i:].rstrip(chr(10)) + chr(10) + '\`\`\`' + chr(10))" "$START"
  else
    printf '\n```\nnpm test\n```\n' >> CLAUDE.md
  fi
  node $CLI sync --check >/dev/null 2>&1 && ok "$shape: check clean" || bad "$shape: unclearable drift"
  # A content change is what exposed the duplication: the byte-identical case
  # hid it. Simulate a new release by editing the compiled body's source.
  node $CLI sync --yes --force >/dev/null 2>&1
  [ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "$shape: still one block" \
                                             || bad "$shape: $(grep -c -- "$END" CLAUDE.md) blocks"
  node $CLI remove --all --yes >/dev/null 2>&1
  grep -q 'Project Instructions' CLAUDE.md 2>/dev/null \
    && bad "$shape: our body survived uninstall" || ok "$shape: uninstall left nothing of ours"
  grep -q 'House rules' CLAUDE.md 2>/dev/null \
    && ok "$shape: their heading kept" || bad "$shape: their heading lost"
done

say "CLAIM 2 — a lone start marker is never interpreted"
new c2; printf '# Mine\n\nmy rules\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace(sys.argv[1] + chr(10), ''))
" "$END"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "torn file does not grow" || bad "torn file grew"
node $CLI doctor 2>&1 | grep -q "belongs to no block" && ok "doctor names the torn file" || bad "doctor silent about it"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q "my rules" CLAUDE.md 2>/dev/null && ok "user prose kept" || bad "user prose lost"
grep -q -- "$START" CLAUDE.md 2>/dev/null && bad "our marker survived" || ok "our marker taken"

# Torn the other way: start marker deleted, end marker surviving. This shape had
# no fixture, so it went unreported and kept its whole body through an uninstall.
new c2-mirror; printf '# Mine\n\nkeep\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
grep -v -- '^<!-- >>> OpenCastle managed' CLAUDE.md > t && mv t CLAUDE.md
node $CLI doctor 2>&1 | grep -q "belongs to no block" && ok "doctor names it torn the other way" || bad "doctor silent on the mirror shape"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q "keep" CLAUDE.md 2>/dev/null && ok "mirror: user prose kept" || bad "mirror: user prose lost"
grep -q 'OpenCastle managed' CLAUDE.md 2>/dev/null && bad "mirror: our marker survived" || ok "mirror: our markers taken"

# Neither ordering may delete or duplicate the user's text.
for side in above below; do
  new "c2-$side"; printf '# Mine\n\nBEFORE\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  if [ "$side" = below ]; then
    printf '\nMIDDLE\n\n%s\n\nAFTER\n' "$START" >> CLAUDE.md
  else
    python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
p.write_text(t.replace('BEFORE' + chr(10), 'BEFORE' + chr(10)*2 + sys.argv[1] + chr(10)*2 + 'MIDDLE' + chr(10), 1))
" "$START"
  fi
  node $CLI remove --all --yes >/dev/null 2>&1
  clean=1
  for line in BEFORE MIDDLE; do
    n=$(grep -c "^$line$" CLAUDE.md 2>/dev/null || echo 0)
    [ "$n" = "1" ] || clean=0
  done
  [ "$clean" = "1" ] && ok "marker $side the block: nothing lost or duplicated" \
                     || bad "marker $side the block: text lost or duplicated"
done

say "CLAIM 3 — byte fidelity, root file and .gitignore"
for shape in lf crlf fenced blanks no-eol-newline; do
  new "c3-$shape"
  case $shape in
    lf)     printf '# A\n\nUse pnpm.\n' > CLAUDE.md ;;
    crlf)   printf '# A\r\n\r\nUse pnpm.\r\n' > CLAUDE.md ;;
    fenced) printf '# A\n\n```text\nkeep\n\n\n\nthese\n```\n' > CLAUDE.md ;;
    blanks) printf '# A\n\n\n\nspaced\n' > CLAUDE.md ;;
    no-eol-newline) printf '# A\n\nUse pnpm.' > CLAUDE.md ;;
  esac
  printf 'node_modules\n\n\ndist/\n' > .gitignore
  cp CLAUDE.md /tmp/v-root; cp .gitignore /tmp/v-gi
  node $CLI init --yes >/dev/null 2>&1
  node $CLI remove --all --yes >/dev/null 2>&1
  cmp -s /tmp/v-root CLAUDE.md && ok "$shape: root file byte-identical" || bad "$shape: root file differs"
  cmp -s /tmp/v-gi .gitignore && ok "$shape: .gitignore byte-identical" || bad "$shape: .gitignore differs"
done

say "CLAIM 4 — sync does not touch what it did not create"
new c4; echo '{"name":"p","dependencies":{"@supabase/supabase-js":"^2"}}' > package.json
node $CLI init --yes >/dev/null 2>&1
find .opencastle -name '*.md' -type f -exec sh -c 'printf "\nSENTINEL\n" >> "$1"' _ {} \;
before=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/agents/skill-matrix.json');d=json.load(open(p))
d['bindings']['framework']['entries']=[{'name':'Mine','skill':'my-skill'}]
json.dump(d,open(p,'w'),indent=2)"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
after=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
[ "$before" = "$after" ] && ok "all $after hand edits survived" || bad "lost $((before-after)) of $before"
grep -q my-skill .opencastle/agents/skill-matrix.json && ok "hand-set matrix entry survived" || bad "matrix entry erased"

say "CLAIM 5 — unparseable generated JSON is named, not fatal, on every target"
# Parameterised because the previous fixture (a bare package.json) always
# resolved to vscode — the one adapter whose update() never re-runs the scaffold
# — so the unguarded parse that broke the other six was unreachable from here.
# `init` is exercised too: it is the command that left a framework tree on disk
# with no manifest beside it.
c5_seed() {
  case $1 in
    claude-code) printf '# R\n' > CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# R\n' > AGENTS.md ;;
    antigravity) printf '# R\n' > GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# R\n' > .github/copilot-instructions.md ;;
  esac
}
c5_mcp() {
  case $1 in
    claude-code) echo .mcp.json ;;
    codex)       echo .codex/mcp.json ;;
    antigravity) echo .agents/mcp_config.json ;;
    cursor)      echo .cursor/mcp.json ;;
    windsurf)    echo .windsurf/mcp.json ;;
    vscode)      echo .vscode/mcp.json ;;
  esac
}
corrupt() {
  python3 - "$1" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); l = p.read_text().split('\n')
l.insert(2, '<<<<<<< HEAD\n=======\n>>>>>>> feat'); p.write_text('\n'.join(l))
PY
}
for ide in claude-code codex antigravity cursor windsurf vscode; do
  mcp=$(c5_mcp "$ide")
  # (a) sync over a conflicted config
  new "c5-sync-$ide"; c5_seed "$ide"
  node $CLI init --yes >/dev/null 2>&1
  if [ ! -f "$mcp" ]; then bad "$ide: expected $mcp after init"; continue; fi
  corrupt "$mcp"
  out=$(node $CLI sync --force --yes </dev/null 2>&1); code=$?
  [ $code -eq 0 ] && ok "$ide: sync completed" || bad "$ide: sync exited $code"
  echo "$out" | grep -q -- "$mcp" && ok "$ide: sync named the file" || bad "$ide: sync did not name it"

  # (b) a first init meeting a config it cannot read — must not orphan the tree
  new "c5-init-$ide"; c5_seed "$ide"
  mkdir -p "$(dirname "$mcp")"
  printf '{\n  // JSONC, legal to VS Code\n  "servers": {}\n}\n' > "$mcp"
  out=$(node $CLI init --yes </dev/null 2>&1); code=$?
  [ $code -eq 0 ] && ok "$ide: init completed" || bad "$ide: init exited $code"
  echo "$out" | grep -q -- "$mcp" && ok "$ide: init named the file" || bad "$ide: init did not name it"
  [ -f .opencastle/manifest.json ] && ok "$ide: manifest written" || bad "$ide: ORPHANED install"
done

say "CLAIM 6 — doctor remedies work; status agrees with doctor"
for breakage in agents matrix gitignored gitignored-ours; do
  new "c6-$breakage"; printf '# R\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  case $breakage in
    agents)     rm -rf .opencastle/agents ;;
    matrix)     rm -f .opencastle/agents/skill-matrix.json ;;
    # Appended, not overwritten. Overwriting destroyed our managed block, so
    # the two-branch remedy added for the pre-0.36 population was never reached
    # — the fixture only ever exercised the branch that was already there.
    gitignored)      printf '.claude/\n' >> .gitignore ;;
    gitignored-ours) python3 -c "
import pathlib
p = pathlib.Path('.gitignore')
p.write_text('node_modules\n\n# >>> OpenCastle managed (do not edit) >>>\nCLAUDE.md\n.claude/agents/\n# <<< OpenCastle managed <<<\n')" ;;
  esac

  node $CLI doctor >/dev/null 2>&1 && { bad "$breakage: doctor no longer detects this"; continue; }
  ok "$breakage: doctor reports it"

  node $CLI 2>&1 | grep -q "Everything is current" \
    && bad "$breakage: status green while doctor red" || ok "$breakage: status agrees"

  # Run whatever doctor printed as the remedy — not an assumed `sync`. A failure
  # only a person can clear must say so instead of naming a command.
  # With or without the `npx` prefix. The pattern required it, and the remedy
  # added for the gitignore case does not use it — so that remedy was invisible
  # here, and the else-branch's grep did not match its wording either. The check
  # could not pass on the case it was written for, in either direction.
  remedy=$(node $CLI doctor 2>&1 | plain | grep -oE '(npx )?opencastle [a-z-]+( --[a-z]+)?' | tail -1)
  if [ -n "$remedy" ]; then
    node $CLI ${remedy#*opencastle } --yes >/dev/null 2>&1
    node $CLI doctor >/dev/null 2>&1 && ok "$breakage: '$remedy' cleared it" \
                                     || bad "$breakage: '$remedy' did not clear it"
  else
    node $CLI doctor 2>&1 | plain | grep -q "remove those entries\|by hand\|only you" \
      && ok "$breakage: names a fix only a person can apply" \
      || { bad "$breakage: no actionable remedy given"; node $CLI doctor 2>&1 | plain | tail -3; }
  fi
done

say "CLAIM 12b — a failing command leaves the install coherent"
new c12b; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib
p=pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace('# Project Instructions','# CHANGED'))"
chmod 444 CLAUDE.md
node $CLI sync --yes --force >/dev/null 2>&1
chmod 644 CLAUDE.md
[ "$(ls .claude/agents 2>/dev/null | wc -l | tr -d ' ')" -gt 0 ] \
  && ok "a failed sync left the framework directories intact" \
  || bad "a failed sync emptied the framework directories"

say "CLAIM 12c — every adapter names what it deletes"
for ide in claude-code vscode cursor; do
  new "c12c-$ide"
  case $ide in
    claude-code) printf '# R\n' > CLAUDE.md; d=.claude/agents ;;
    vscode)      d=.github/instructions ;;
    cursor)      printf 'x\n' > .cursorrules; d=.cursor/rules ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  mkdir -p "$d"; echo mine > "$d/MY-OWN.md"
  node $CLI sync --yes --force 2>&1 | grep -q "MY-OWN.md" \
    && ok "$ide names the file it removed" || bad "$ide deleted it in silence"
done

say "CLAIM 7 — every entry point preserves the stack"
new c7; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
node $CLI add sentry >/dev/null 2>&1
for cmd in "init --yes" "sync --yes --force"; do
  node $CLI $cmd >/dev/null 2>&1
  python3 -c "
import json,sys
s=json.load(open('.opencastle/manifest.json'))['stack']['techTools']
sys.exit(0 if 'sentry' in s else 1)" && ok "$cmd kept sentry" || bad "$cmd dropped sentry"
done

say "CLAIM 11/12 — stdin closed, and dry runs write nothing"
new c11; printf '# R\n' > CLAUDE.md
node $CLI init --yes </dev/null >/dev/null 2>&1 && ok "init --yes" || bad "init --yes"
node $CLI sync --reconfigure --yes </dev/null >/dev/null 2>&1 && ok "sync --reconfigure --yes" || bad "sync --reconfigure --yes"
node $CLI add sentry </dev/null >/dev/null 2>&1 && ok "add" || bad "add"
# Content, not just paths — the previous version compared `find` output, so a
# dry run that rewrote a file would have passed.
tree_hash() { find . -path ./.git -prune -o -type f -print0 | sort -z | xargs -0 shasum | shasum; }
before=$(tree_hash)
node $CLI sync --dry-run </dev/null >/dev/null 2>&1
node $CLI remove --all --dry-run </dev/null >/dev/null 2>&1
after=$(tree_hash)
[ "$before" = "$after" ] && ok "dry runs wrote nothing (content hashed)" || bad "dry run changed the tree"

say "CLAIM 8 — the removal preview matches the action, including .gitignore"
new c8; printf '# Mine\n\nKEEP\n' > CLAUDE.md; printf 'node_modules\n' > .gitignore
node $CLI init --yes >/dev/null 2>&1
preview=$(node $CLI remove --all --dry-run 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
node $CLI remove --all --yes >/dev/null 2>&1
echo "$preview" | grep -q 'Edited, not deleted' && ok "preview has an edited section" || bad "no edited section"
grep -q KEEP CLAUDE.md && ok "a file previewed as edited still exists" || bad "previewed as edited, then deleted"
grep -q node_modules .gitignore && ok ".gitignore kept the user's rules" || bad ".gitignore lost the user's rules"

say "CLAIM 9 — a v1 manifest is migrated, not crashed on"
new c9; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json');m=json.load(open(p))
m['stack']={'cms':'sanity','db':'supabase','pm':'linear'}
json.dump(m,open(p,'w'),indent=2)"
node $CLI sync --yes --force >/dev/null 2>&1 && ok "sync survived a v1 stack" || bad "sync crashed"
# `[ $? -le 1 ]` was the old test, and `bin/cli.mjs` exits 1 on any uncaught
# throw — so a doctor that died on EISDIR scored the same as a clean run. Assert
# on the output: a doctor that ran printed its check table.
out=$(node $CLI doctor 2>&1 | plain)
echo "$out" | grep -q "OpenCastle manifest" \
  && ok "doctor survived a v1 stack" \
  || { bad "doctor crashed on a v1 stack"; echo "$out" | head -3; }
python3 -c "
import json,sys
s=json.load(open('.opencastle/manifest.json'))['stack']
sys.exit(0 if 'techTools' in s else 1)" && ok "manifest migrated to v2" || bad "manifest not migrated"

say "CLAIM 10 — nothing shipped names a command that does not exist"
cd "$REPO"
npx vitest run src/cli/docs-accuracy.test.ts >/dev/null 2>&1 && ok "docs-accuracy guards pass" || bad "docs-accuracy failing"

say "CLAIM 1c — a doubled .gitignore block heals and uninstalls"
new c1c; printf 'node_modules\ndist/\n' > .gitignore; cp .gitignore "$ROOT/gi.orig"
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib,re
p=pathlib.Path('.gitignore');t=p.read_text()
m=re.search(r'# >>> OpenCastle managed.*?# <<< OpenCastle managed <<<',t,re.S)
p.write_text(t[:m.end()] + '\n\n' + m.group(0) + t[m.end():])"
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(grep -c '>>> OpenCastle managed' .gitignore)" = "1" ] && ok "sync collapsed the doubled block" || bad "still doubled"
node $CLI remove --all --yes >/dev/null 2>&1
cmp -s "$ROOT/gi.orig" .gitignore && ok ".gitignore restored byte-identical" || bad ".gitignore not restored"

# Separated by a single newline, with a user rule below — the shape that welded
# `.env.local` into a comment and stopped git ignoring it.
new c1d; printf 'node_modules\n' > .gitignore; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
printf '.env.local\n' >> .gitignore
python3 -c "
import pathlib,re
p=pathlib.Path('.gitignore');t=p.read_text()
m=re.search(r'# >>> OpenCastle managed.*?# <<< OpenCastle managed <<<',t,re.S)
p.write_text(t[:m.end()]+chr(10)+m.group(0)+t[m.end():])"
node $CLI sync --yes --force >/dev/null 2>&1
git check-ignore -q .env.local && ok "a user rule below a doubled block survives" || bad "user rule welded into a comment"

say "CLAIM 13 — sync recompiles content, on every target"
# The claim the branch is *named* for, and the one nothing tested: a generated
# file whose bytes differ from its source is rewritten by `sync`. It went
# unnoticed for a full release because every existing check asked whether files
# were *present*, and the four single-file targets kept every stale byte while
# reporting "Updated 0 framework files" and a drift the prescribed remedy could
# not clear.
c13_seed() {
  case $1 in
    claude-code) printf '# R\n' > CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# R\n' > AGENTS.md ;;
    antigravity) printf '# R\n' > GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# R\n' > .github/copilot-instructions.md ;;
    opencode)    printf '# R\n' > CLAUDE.md ;;
  esac
}
for ide in claude-code codex antigravity opencode cursor windsurf vscode; do
  new "c13-$ide"; c13_seed "$ide"
  node $CLI init --yes >/dev/null 2>&1
  # opencode has no detection trigger of its own that does not collide with
  # codex over AGENTS.md, so point the manifest at it and recompile.
  if [ "$ide" = opencode ]; then
    python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json'); m=json.load(open(p))
m['ides']=['opencode']; m['ide']='opencode'; m['stack']['ides']=['opencode']
json.dump(m,open(p,'w'),indent=2)"
    node $CLI sync --yes --force >/dev/null 2>&1
  fi

  before=$(find . -path ./.git -prune -o -type f -print | wc -l | tr -d ' ')
  # Tamper with every generated markdown file the compiler owns.
  targets=$(node --input-type=module -e "
const {IDE_ADAPTERS} = await import('$REPO/dist/cli/adapters/index.js')
const a = await IDE_ADAPTERS[process.argv[1]]()
console.log(a.getManagedPaths().framework.filter(p => p.endsWith('/')).join(' '))
" "$ide" 2>/dev/null)
  n=0
  for dir in $targets; do
    while IFS= read -r f; do
      printf 'STALE RELEASE CONTENT\n' > "$f"; n=$((n+1))
    done < <(find "$dir" -type f 2>/dev/null)
  done
  if [ "$n" = "0" ]; then bad "$ide: no generated files found to tamper with"; continue; fi

  node $CLI sync --yes --force >/dev/null 2>&1
  left=$(grep -rl 'STALE RELEASE CONTENT' $targets 2>/dev/null | wc -l | tr -d ' ')
  [ "$left" = "0" ] && ok "$ide: sync restored all $n tampered files" \
                    || bad "$ide: $left of $n files kept stale content"
  node $CLI sync --check >/dev/null 2>&1 \
    && ok "$ide: sync --check clean afterwards" \
    || bad "$ide: sync --check still reports drift its own remedy cannot clear"
  after=$(find . -path ./.git -prune -o -type f -print | wc -l | tr -d ' ')
  [ "$before" = "$after" ] && ok "$ide: file count unchanged ($after)" \
                           || bad "$ide: $before files before, $after after"
done

say "CLAIM 13b — an upgrade delivers new content to an existing install"
new c13b; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
before=$(find .claude -type f | wc -l | tr -d ' ')
find .claude -type f -name '*.md' -exec sh -c 'printf "PREVIOUS RELEASE\n" > "$1"' _ {} \;
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json'); m=json.load(open(p)); m['version']='0.30.0'
json.dump(m,open(p,'w'),indent=2)"
out=$(node $CLI sync --yes 2>&1 | plain)
[ "$(grep -rl 'PREVIOUS RELEASE' .claude 2>/dev/null | wc -l | tr -d ' ')" = "0" ] \
  && ok "no file kept the previous release's body" || bad "stale bodies survived the upgrade"
[ "$before" = "$(find .claude -type f | wc -l | tr -d ' ')" ] \
  && ok "the upgrade deleted nothing ($before files)" || bad "the upgrade changed the file count"
node $CLI sync --check >/dev/null 2>&1 && ok "clean after upgrade" || bad "drift after upgrade"
# The counter must describe the run, not the tree.
echo "$out" | grep -q "Updated 0 framework files" && bad "reported 0 while rewriting the tree" \
                                                  || ok "the count reflects what changed"
out2=$(node $CLI sync --yes --force 2>&1 | plain)
echo "$out2" | grep -q "Updated 0 framework files" \
  && ok "a no-op sync reports 0" || bad "a no-op sync inflated its count"

say "CLAIM 12d — a failing init leaves the install coherent too"
# CLAIM 12b tests `sync` only, which is why `init` shipped a re-init path that
# emptied every framework directory before writing a byte.
for cmd in "init --yes" "sync --yes --force"; do
  new "c12d-$(echo "$cmd" | tr ' -' '__')"
  printf '# R\n' > CLAUDE.md; printf 'x\n' > .cursorrules
  node $CLI init --yes >/dev/null 2>&1
  before=$(find .claude .cursor -type f 2>/dev/null | wc -l | tr -d ' ')
  python3 -c "
import pathlib
p=pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace('# Project Instructions','# CHANGED'))"
  chmod 444 CLAUDE.md
  node $CLI $cmd >/dev/null 2>&1
  chmod 644 CLAUDE.md
  after=$(find .claude .cursor -type f 2>/dev/null | wc -l | tr -d ' ')
  [ "$after" -gt 0 ] && ok "$cmd: framework directories still populated ($after files)" \
                     || bad "$cmd: emptied the framework directories (was $before)"
done

say "CLAIM 12e — no command leaves an empty directory it created"
for ide in claude-code codex antigravity cursor windsurf vscode; do
  new "c12e-$ide"
  case $ide in
    claude-code) printf '# R\n' > CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# R\n' > AGENTS.md ;;
    antigravity) printf '# R\n' > GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# R\n' > .github/copilot-instructions.md ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  node $CLI remove --all --yes >/dev/null 2>&1
  empties=$(find . -path ./.git -prune -o -type d -empty -print 2>/dev/null | grep -v '^\./\.git' | grep -v '^\.$' | tr '\n' ' ')
  [ -z "$empties" ] && ok "$ide: nothing left empty" || bad "$ide: left behind $empties"
done

say "CLAIM 12f — a rename that differs only in case is not deleted"
# macOS and Windows match filenames case-insensitively, so the compiler writes
# into the existing file under its existing name; the sweep then compared the
# name it asked for against the name on disk and removed what it had written.
new c12f; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
mv .claude/agents/architect.agent.md .claude/agents/Architect.agent.md
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(find .claude/agents -iname 'architect.agent.md' | wc -l | tr -d ' ')" = "1" ] \
  && ok "the file survives a case-only rename" || bad "sync deleted the file it just wrote"
node $CLI sync --check >/dev/null 2>&1 && ok "check clean after a case-only rename" \
                                       || bad "case-only rename leaves drift"

say "CLAIM 6b — every printed remedy is a command that works"
# The MCP message told the user to run `sync`, which short-circuits when nothing
# has drifted — and the MCP config is not a path the drift checker compares.
new c6b; printf '# R\n' > CLAUDE.md; echo '{"name":"p","dependencies":{"@sentry/node":"^8"}}' > package.json
mkdir -p .vscode; printf '{\n  // JSONC\n  "mcpServers": {}\n}\n' > .mcp.json
out=$(node $CLI init --yes </dev/null 2>&1 | plain)
echo "$out" | grep -q "not valid JSON" && ok "init named the unreadable config" \
                                       || bad "init did not name it"
remedy=$(echo "$out" | grep -oE 'opencastle sync( --[a-z]+)?' | tail -1)
printf '{\n  "mcpServers": {}\n}\n' > .mcp.json       # the user fixes the file
node $CLI ${remedy#opencastle } --yes >/dev/null 2>&1
[ "$(grep -c sentry .mcp.json)" -gt 0 ] && ok "'$remedy' added the MCP servers" \
                                        || bad "'$remedy' did not add the MCP servers"

say "CLAIM 6c — doctor never prescribes a command that refuses to run"
new c6c; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
node $CLI remove --keep-files --yes >/dev/null 2>&1
out=$(node $CLI doctor 2>&1 | plain)
remedy=$(echo "$out" | grep -oE '(npx )?opencastle [a-z-]+' | tail -1)
if [ -n "$remedy" ]; then
  node $CLI ${remedy#*opencastle } --yes >/dev/null 2>&1
  code=$?
  [ $code -eq 0 ] && ok "'$remedy' runs on a manifest-less install" \
                  || bad "'$remedy' exits $code — doctor named a command that refuses"
else
  bad "doctor named no remedy for a missing manifest"
fi

say "CLAIM 3b — a co-owned JSON config keeps every key the user put in it"
# Byte fidelity is claimed for markdown, where the block is delimited and the
# rest is untouched. A JSON config we merge servers into is round-tripped
# through a parser, so it comes back canonically formatted — what must hold is
# that every key of theirs survives with the same value, and that nothing of
# ours is left. Asserted rather than assumed: `stripManagedMcpServers` used to
# rewrite the file even when it removed nothing at all.
new c3b; printf '# R\n' > CLAUDE.md
printf '{"name":"p","agent":{"build":{"model":"anthropic/claude-opus-4"}}}\n' > opencode.json
cp opencode.json "$ROOT/oc.orig"
node $CLI init --yes >/dev/null 2>&1
node $CLI remove --all --yes >/dev/null 2>&1
if [ ! -f opencode.json ]; then
  bad "opencode.json was deleted — it is the user's whole project config"
else
  python3 -c "
import json, sys
a = json.load(open('$ROOT/oc.orig')); b = json.load(open('opencode.json'))
missing = [k for k, v in a.items() if k not in b or b[k] != v]
sys.exit(1 if missing else 0)" \
    && ok "every key the user wrote survived" || bad "keys were lost or changed"
  grep -q chrome-devtools opencode.json && bad "our servers survived uninstall" \
                                        || ok "our servers are gone"
fi

say "CLAIM 3c — a config we take nothing out of is not rewritten"
new c3c; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
printf '{"mcpServers":{"mine":{"command":"node"}}}\n' > opencode.json
cp opencode.json "$ROOT/oc2.orig"
node $CLI remove --all --yes >/dev/null 2>&1
if [ -f opencode.json ]; then
  cmp -s "$ROOT/oc2.orig" opencode.json && ok "left byte-identical" \
    || { bad "reformatted a file it removed nothing from"; diff "$ROOT/oc2.orig" opencode.json | head -4; }
else
  bad "deleted a config holding only the user's own server"
fi

say "CLAIM 12g — no command answers a broken project with a stack trace"
new c12g; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
chmod 000 .opencastle/manifest.json
for cmd in "" "doctor" "sync --check"; do
  out=$(node $CLI $cmd 2>&1 | plain)
  echo "$out" | grep -qE 'at async|Node\.js v' \
    && bad "'opencastle $cmd' printed a stack trace" \
    || ok "'opencastle ${cmd:-(bare)}' failed cleanly"
done
chmod 644 .opencastle/manifest.json

say "CLAIM 4b — init does not rewrite .opencastle/ either"
new c4b; echo '{"name":"p","dependencies":{"@supabase/supabase-js":"^2"}}' > package.json
printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
find .opencastle -name '*.md' -type f -exec sh -c 'printf "\nSENTINEL\n" >> "$1"' _ {} \;
b=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
node $CLI init --yes >/dev/null 2>&1
a=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
[ "$b" = "$a" ] && ok "init kept all $a hand edits" || bad "init lost $((b-a)) of $b"

echo
echo "════ $PASS passed, $FAIL failed ════"
cd /; rm -rf "$ROOT"
exit $([ $FAIL -eq 0 ] && echo 0 || echo 1)
