#!/bin/bash
# Self-verification of the branch's stated claims, driving the CLI.
# Written in bash (not zsh) so unquoted expansion word-splits as expected;
# `timeout` does not exist on this machine, so nothing relies on it.
set -u
REPO="$(cd "$(dirname "$0")/.." && pwd)"
CLI="$REPO/bin/cli.mjs"
ROOT=$(mktemp -d)
PASS=0; FAIL=0
ok()   { echo "  ok   $1"; PASS=$((PASS+1)); }
bad()  { echo "  FAIL $1"; FAIL=$((FAIL+1)); }
say()  { echo; echo "$1"; }
# The CLI styles its output, so a literal grep for "Updated 0 framework files"
# can never match: the count is wrapped in bold. An assertion that can never
# match is an assertion that always reports whatever its else-branch says, and
# two of the checks below were passing for that reason alone.
plain() { sed $'s/\033\[[0-9;]*m//g'; }

new() { d="$ROOT/$1"; rm -rf "$d"; mkdir -p "$d"; cd "$d" || exit 1; git init -q; }

START='<!-- >>> OpenCastle managed — regenerated by `opencastle sync`, edits here are lost >>> -->'
END='<!-- <<< OpenCastle managed <<< -->'

say "CLAIM 1 — one complete block, from any starting content"
for shape in plain unclosed-fence quoted-block quoted-start-only trailing-rule crlf; do
  new "c1-$shape"
  case $shape in
    plain)          printf '# Mine\n\nkeep\n' > CLAUDE.md ;;
    unclosed-fence) printf '# Mine\n\n```sh\nmake\n\nkeep\n' > CLAUDE.md ;;
    quoted-block)   printf '# Mine\n\n```md\n%s\nx\n%s\n```\n\nkeep\n' "$START" "$END" > CLAUDE.md ;;
    quoted-start-only) printf '# Mine\n\n```md\n%s\n```\n\nRULE 1\nRULE 2\n' "$START" > CLAUDE.md ;;
    trailing-rule)  printf '# Mine\n\nkeep\n\n---\n' > CLAUDE.md ;;
    crlf)           printf '# Mine\r\n\r\nkeep\r\n' > CLAUDE.md ;;
  esac
  cp CLAUDE.md "$ROOT/$shape.orig"
  node $CLI init --yes >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  # One block, from every shape. A fixture that already held a complete block
  # inside a fence has it collapsed into the one we maintain: a complete marker
  # pair is this tool's wherever it sits, which is the only reading the writer,
  # the checker, the collapse and the uninstall have ever managed to share.
  want=1
  n=$(grep -c -- "$END" CLAUDE.md)
  if [ "$n" = "$want" ]; then ok "$shape: $want block(s) after init+2 syncs"
  else bad "$shape: $n blocks, wanted $want"; fi
  node $CLI remove --all --yes >/dev/null 2>&1
  # Our *body* must be gone. A quoted example keeps its markers, because those
  # are the user's text, so markers alone are not the test.
  if [ -f CLAUDE.md ] && grep -q "Project Instructions" CLAUDE.md; then
    bad "$shape: our body survived uninstall"
  else ok "$shape: uninstall left nothing of ours"; fi
  # The user's own bytes, not just ours. The harness used to check only that our
  # markers were gone, so it passed on a file whose rules had been deleted.
  # A file holding a *complete* quoted block has that block adopted — recorded
  # in `blockRegions` as the price of never guessing which marker is ours. Every
  # other shape must come back byte for byte.
  # Everything except OpenCastle's own marker lines must come back byte for
  # byte. A marker line is text this tool authored, so taking it even out of
  # someone's quoted example loses nothing they wrote; anything else would.
  # Filtering it from *both* sides is deliberate and is a real exception to
  # "byte for byte" — so it is asserted separately, immediately below, rather
  # than hidden by the filter.
  # `quoted-block` is compared on prose only: its marker pair *and* the body
  # between them are ours, so they do not come back. Every other shape must.
  if [ "$shape" = quoted-block ]; then
    grep -v -x -F -e "$START" -e "$END" -e 'x' "$ROOT/$shape.orig" > "$ROOT/$shape.expect"
    grep -v -x -F -e "$START" -e "$END" -e 'x' CLAUDE.md > "$ROOT/$shape.actual" 2>/dev/null || true
  else
    grep -v -F -- "$START" "$ROOT/$shape.orig" > "$ROOT/$shape.expect"
    grep -v -F -- "$START" CLAUDE.md > "$ROOT/$shape.actual" 2>/dev/null || true
  fi
  if cmp -s "$ROOT/$shape.expect" "$ROOT/$shape.actual"; then
    ok "$shape: user half byte-identical"
  else
    bad "$shape: user half changed"
    diff "$ROOT/$shape.expect" "$ROOT/$shape.actual" | head -4
  fi
  # The exception, stated rather than filtered: a marker line is text this tool
  # authored, so it is taken back even from inside the user's fence — together
  # with the block body it delimits. Their prose and their fence stay.
  case $shape in
    quoted-block)
      grep -q -F -- "$START" CLAUDE.md \
        && bad "$shape: a marker pair survived uninstall" \
        || ok "$shape: marker pair taken, prose kept (documented exception)"
      grep -q '```md' CLAUDE.md \
        && ok "$shape: the user's fence survives" \
        || bad "$shape: the user's fence was removed" ;;
    quoted-start-only)
      grep -q -F -- "$START" CLAUDE.md \
        && bad "$shape: a lone quoted marker survived" \
        || ok "$shape: a lone quoted marker is taken (documented exception)" ;;
  esac
done

say "CLAIM 1b — a doubled block heals on a plain sync"
new c1b; printf '# Mine\n\nKEEP\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 - "$START" "$END" <<'PY'
import sys, pathlib
S, E = sys.argv[1], sys.argv[2]
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
a, b = t.index(S), t.index(E) + len(E)
p.write_text(t[:a] + t[a:b].replace('# Project Instructions', '# Project Instructions\n\nSTALE') + '\n\n' + t[a:])
PY
node $CLI sync --check >/dev/null 2>&1 && bad "doubled file not reported as drift" || ok "doubled file reported as drift"
node $CLI sync --yes >/dev/null 2>&1
[ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "plain sync collapsed it" || bad "still doubled"
grep -q STALE CLAUDE.md && bad "stale half survived" || ok "stale half gone"

say "CLAIM 1e — a second complete block is collapsed, wherever it sits"
for side in below above; do
  new "c1e-$side"; printf '# Mine\n\nkeep\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  python3 -c "
import pathlib, sys
S=sys.argv[1]; E=sys.argv[2]
doc = chr(10)+'## How this works'+chr(10)*2+'\`\`\`md'+chr(10)+S+chr(10)+'...example...'+chr(10)+E+chr(10)+'\`\`\`'+chr(10)
p=pathlib.Path('CLAUDE.md'); t=p.read_text()
p.write_text(t+doc if sys.argv[3]=='below' else doc+t)
" "$START" "$END" "$side"
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI sync --yes --force >/dev/null 2>&1
  [ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "doc $side: collapsed to one block" \
                                             || bad "doc $side: $(grep -c -- "$END" CLAUDE.md) blocks"
  grep -q '## How this works' CLAUDE.md && ok "doc $side: their heading kept" \
                                        || bad "doc $side: their heading lost"
  grep -q '```md' CLAUDE.md && ok "doc $side: their fence kept" || bad "doc $side: their fence lost"
  grep -q 'keep' CLAUDE.md && ok "doc $side: their prose kept" || bad "doc $side: their prose lost"
  [ -f CLAUDE.md.opencastle-backup ] && ok "doc $side: a backup was written" \
                                     || bad "doc $side: collapsed without a backup"
  node $CLI sync --check >/dev/null 2>&1 && ok "doc $side: check clean" || bad "doc $side: drift remains"
done

say "CLAIM 1f — a block the user fenced is still ours, and still leaves one"
# The shape that defeated six versions of a "is this quoted?" test: an unpaired
# fence above the block, a bare fence below it. Every version disowned the block
# — check red forever, an upgrade appending a second 20KB body that every
# command called healthy, and our whole body left behind by `remove --all`.
for shape in wrapped unpaired; do
  new "c1f-$shape"
  case $shape in
    wrapped)  printf '# House rules\n\nUse pnpm.\n' > CLAUDE.md ;;
    unpaired) printf '# House rules\n\nA snippet that never got closed:\n\n```\n' > CLAUDE.md ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  if [ "$shape" = wrapped ]; then
    python3 -c "
import pathlib, sys
p=pathlib.Path('CLAUDE.md'); t=p.read_text(); i=t.index(sys.argv[1])
p.write_text(t[:i] + '\`\`\`' + chr(10) + t[i:].rstrip(chr(10)) + chr(10) + '\`\`\`' + chr(10))" "$START"
  else
    printf '\n```\nnpm test\n```\n' >> CLAUDE.md
  fi
  node $CLI sync --check >/dev/null 2>&1 && ok "$shape: check clean" || bad "$shape: unclearable drift"
  # Both cases, because they fail differently: the byte-identical sync (which
  # once hid the duplication) and a changed body. The comment here used to
  # promise the second and perform only the first.
  node $CLI sync --yes --force >/dev/null 2>&1
  python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
p.write_text(t.replace('# Project Instructions', '# Project Instructions CHANGED', 1))
"
  node $CLI sync --yes --force >/dev/null 2>&1
  [ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "$shape: still one block" \
                                             || bad "$shape: $(grep -c -- "$END" CLAUDE.md) blocks"
  node $CLI remove --all --yes >/dev/null 2>&1
  grep -q 'Project Instructions' CLAUDE.md 2>/dev/null \
    && bad "$shape: our body survived uninstall" || ok "$shape: uninstall left nothing of ours"
  grep -q 'House rules' CLAUDE.md 2>/dev/null \
    && ok "$shape: their heading kept" || bad "$shape: their heading lost"
done

say "CLAIM 2 — a lone start marker is never interpreted"
new c2; printf '# Mine\n\nmy rules\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace(sys.argv[1] + chr(10), ''))
" "$END"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
# Counting end markers cannot detect this: the fixture deletes the file's only
# end marker, so after a 20KB block is appended there is exactly one again and
# the assertion read `[ 1 = 1 ]` over a file that had doubled. Count bodies.
[ "$(grep -c '^# Project Instructions$' CLAUDE.md)" = "1" ] \
  && ok "torn file does not grow" \
  || bad "torn file grew to $(grep -c '^# Project Instructions$' CLAUDE.md) instruction sets"
node $CLI doctor 2>&1 | plain | grep -qE "pair with nothing|no complete block" && ok "doctor names the torn file" || bad "doctor silent about it"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q "my rules" CLAUDE.md 2>/dev/null && ok "user prose kept" || bad "user prose lost"
grep -q -- "$START" CLAUDE.md 2>/dev/null && bad "our marker survived" || ok "our marker taken"

# Torn the other way: start marker deleted, end marker surviving. This shape had
# no fixture, so it went unreported and kept its whole body through an uninstall.
new c2-mirror; printf '# Mine\n\nkeep\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
grep -v -- '^<!-- >>> OpenCastle managed' CLAUDE.md > t && mv t CLAUDE.md
node $CLI doctor 2>&1 | plain | grep -qE "pair with nothing|no complete block" && ok "doctor names it torn the other way" || bad "doctor silent on the mirror shape"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q "keep" CLAUDE.md 2>/dev/null && ok "mirror: user prose kept" || bad "mirror: user prose lost"
grep -q 'OpenCastle managed' CLAUDE.md 2>/dev/null && bad "mirror: our marker survived" || ok "mirror: our markers taken"

# Neither ordering may delete or duplicate the user's text.
for side in above below; do
  new "c2-$side"; printf '# Mine\n\nBEFORE\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  if [ "$side" = below ]; then
    printf '\nMIDDLE\n\n%s\n\nAFTER\n' "$START" >> CLAUDE.md
  else
    python3 -c "
import pathlib, sys
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
p.write_text(t.replace('BEFORE' + chr(10), 'BEFORE' + chr(10)*2 + sys.argv[1] + chr(10)*2 + 'MIDDLE' + chr(10), 1))
" "$START"
  fi
  node $CLI remove --all --yes >/dev/null 2>&1
  clean=1
  for line in BEFORE MIDDLE; do
    n=$(grep -c "^$line$" CLAUDE.md 2>/dev/null || echo 0)
    [ "$n" = "1" ] || clean=0
  done
  [ "$clean" = "1" ] && ok "marker $side the block: nothing lost or duplicated" \
                     || bad "marker $side the block: text lost or duplicated"
done

say "CLAIM 3 — byte fidelity, root file and .gitignore"
for shape in lf crlf fenced blanks no-eol-newline; do
  new "c3-$shape"
  case $shape in
    lf)     printf '# A\n\nUse pnpm.\n' > CLAUDE.md ;;
    crlf)   printf '# A\r\n\r\nUse pnpm.\r\n' > CLAUDE.md ;;
    fenced) printf '# A\n\n```text\nkeep\n\n\n\nthese\n```\n' > CLAUDE.md ;;
    blanks) printf '# A\n\n\n\nspaced\n' > CLAUDE.md ;;
    no-eol-newline) printf '# A\n\nUse pnpm.' > CLAUDE.md ;;
  esac
  printf 'node_modules\n\n\ndist/\n' > .gitignore
  cp CLAUDE.md "$ROOT/v-root"; cp .gitignore "$ROOT/v-gi"
  node $CLI init --yes >/dev/null 2>&1
  node $CLI remove --all --yes >/dev/null 2>&1
  # A file that never ended in a newline gets one back, and only that. Our
  # append and a block placed by anything else are byte-identical in that case,
  # so removal cannot tell whose newline it is looking at; it declines to delete
  # rather than guess. Everything else must match byte for byte.
  if [ "$shape" = no-eol-newline ]; then
    want=$(( $(wc -c < "$ROOT/v-root") + 1 ))
    got=$(wc -c < CLAUDE.md)
    if [ "$(cat "$ROOT/v-root")" = "$(cat CLAUDE.md)" ] && [ "$got" -eq "$want" ]; then
      ok "$shape: restored, plus the one newline it will not guess about"
    else
      bad "$shape: differs beyond the stated exception ($got bytes, wanted $want)"
      diff "$ROOT/v-root" CLAUDE.md | head -4
    fi
  elif cmp -s "$ROOT/v-root" CLAUDE.md; then
    ok "$shape: root file byte-identical"
  else
    bad "$shape: root file differs"
    diff "$ROOT/v-root" CLAUDE.md | head -4
  fi
  cmp -s "$ROOT/v-gi" .gitignore && ok "$shape: .gitignore byte-identical" || bad "$shape: .gitignore differs"
done

say "CLAIM 3g — .gitignore byte fidelity, over the alphabet that reaches it"
# The loop above always writes a `.gitignore` ending in a newline, so the one
# case with a stated exception was never exercised on this file. Both round-20
# reviewers found the gap independently.
#
# The exception is narrow and it is not a choice: git ends a line at `\n` and
# nowhere else, so appending our block below a last line that has no `\n` after
# it welds our marker onto the user's last rule and the rule stops matching. One
# byte buys their rule back, and no removal can tell afterwards whose byte it was.
for shape in lf crlf cr no-final-nl no-final-nl-cr blanks spaces bom bom-only latin1 negation mixed empty; do
  new "c3g-$shape"; printf '# R\n' > CLAUDE.md
  python3 - "$shape" <<'PY2'
import pathlib, sys
BOM = b'\xef\xbb\xbf'
shapes = {
  'lf': b'node_modules\ndist\n',
  'crlf': b'node_modules\r\ndist\r\n',
  'cr': b'node_modules\rdist\r',
  'no-final-nl': b'node_modules\ndist',
  'no-final-nl-cr': b'node_modules\rdist',
  'blanks': b'\n\n\n',
  'spaces': b'   \n',
  'bom': BOM + b'node_modules\n',
  'bom-only': BOM,
  'latin1': b'secrets-caf\xe9/\n',
  'negation': b'*.txt\n!keep.txt\n',
  'mixed': b'a\nb\r\nc\rd\n',
  'empty': b'',
}
pathlib.Path('.gitignore').write_bytes(shapes[sys.argv[1]])
PY2
  cp .gitignore "$ROOT/v-gi3"
  node $CLI init --yes >/dev/null 2>&1
  node $CLI remove --all --yes >/dev/null 2>&1
  if [ ! -f .gitignore ]; then
    # Deleting is right only when nothing of theirs was there to begin with.
    if [ ! -s "$ROOT/v-gi3" ]; then
      ok "$shape: an empty file we filled and emptied is gone"
    else
      bad "$shape: their .gitignore was deleted"
    fi
  elif cmp -s "$ROOT/v-gi3" .gitignore; then
    ok "$shape: byte-identical"
  else
    want=$(( $(wc -c < "$ROOT/v-gi3") + 1 ))
    got=$(wc -c < .gitignore)
    # The stated exception, and nothing wider: one added byte, and it must be the
    # terminator on the final line. Their text is otherwise untouched.
    if [ "$got" -eq "$want" ] && [ "$(printf '%s' "$(cat "$ROOT/v-gi3")")" = "$(printf '%s' "$(cat .gitignore)")" ]; then
      ok "$shape: restored, plus the one line terminator git needs"
    else
      bad "$shape: differs beyond the stated exception ($got bytes, wanted $want)"
      od -c "$ROOT/v-gi3" | head -3; echo ' --- became ---'; od -c .gitignore | head -3
    fi
  fi
done

say "CLAIM 4 — sync does not touch what it did not create"
new c4; echo '{"name":"p","dependencies":{"@supabase/supabase-js":"^2"}}' > package.json
node $CLI init --yes >/dev/null 2>&1
find .opencastle -name '*.md' -type f -exec sh -c 'printf "\nSENTINEL\n" >> "$1"' _ {} \;
before=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/agents/skill-matrix.json');d=json.load(open(p))
d['bindings']['framework']['entries']=[{'name':'Mine','skill':'my-skill'}]
json.dump(d,open(p,'w'),indent=2)"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
after=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
[ "$before" = "$after" ] && ok "all $after hand edits survived" || bad "lost $((before-after)) of $before"
grep -q my-skill .opencastle/agents/skill-matrix.json && ok "hand-set matrix entry survived" || bad "matrix entry erased"

say "CLAIM 5 — unparseable generated JSON is named, not fatal, on every target"
# Parameterised because the previous fixture (a bare package.json) always
# resolved to vscode — the one adapter whose update() never re-runs the scaffold
# — so the unguarded parse that broke the other six was unreachable from here.
# `init` is exercised too: it is the command that left a framework tree on disk
# with no manifest beside it.
c5_seed() {
  case $1 in
    claude-code) printf '# R\n' > CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# R\n' > AGENTS.md ;;
    antigravity) printf '# R\n' > GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# R\n' > .github/copilot-instructions.md ;;
    opencode)    printf '# R\n' > CLAUDE.md; printf '{"name":"p"}\n' > opencode.json ;;
  esac
}
c5_mcp() {
  case $1 in
    claude-code) echo .mcp.json ;;
    codex)       echo .codex/mcp.json ;;
    antigravity) echo .agents/mcp_config.json ;;
    cursor)      echo .cursor/mcp.json ;;
    windsurf)    echo .windsurf/mcp.json ;;
    vscode)      echo .vscode/mcp.json ;;
    opencode)    echo opencode.json ;;
  esac
}
corrupt() {
  python3 - "$1" <<'PY'
import sys, pathlib
p = pathlib.Path(sys.argv[1]); l = p.read_text().split('\n')
l.insert(2, '<<<<<<< HEAD\n=======\n>>>>>>> feat'); p.write_text('\n'.join(l))
PY
}
for ide in claude-code codex antigravity opencode cursor windsurf vscode; do
  mcp=$(c5_mcp "$ide")
  # (a) sync over a conflicted config
  new "c5-sync-$ide"; c5_seed "$ide"
  node $CLI init --yes >/dev/null 2>&1
  if [ ! -f "$mcp" ]; then bad "$ide: expected $mcp after init"; continue; fi
  corrupt "$mcp"
  out=$(node $CLI sync --force --yes </dev/null 2>&1); code=$?
  [ $code -eq 0 ] && ok "$ide: sync completed" || bad "$ide: sync exited $code"
  echo "$out" | grep -q -- "$mcp" && ok "$ide: sync named the file" || bad "$ide: sync did not name it"

  # (b) a first init meeting a config it cannot read — must not orphan the tree
  new "c5-init-$ide"; c5_seed "$ide"
  mkdir -p "$(dirname "$mcp")"
  printf '{\n  // JSONC, legal to VS Code\n  "servers": {}\n}\n' > "$mcp"
  out=$(node $CLI init --yes </dev/null 2>&1); code=$?
  [ $code -eq 0 ] && ok "$ide: init completed" || bad "$ide: init exited $code"
  echo "$out" | grep -q -- "$mcp" && ok "$ide: init named the file" || bad "$ide: init did not name it"
  [ -f .opencastle/manifest.json ] && ok "$ide: manifest written" || bad "$ide: ORPHANED install"
done

say "CLAIM 6 — doctor remedies work; status agrees with doctor"
for breakage in agents matrix gitignored gitignored-ours; do
  new "c6-$breakage"; printf '# R\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  case $breakage in
    agents)     rm -rf .opencastle/agents ;;
    matrix)     rm -f .opencastle/agents/skill-matrix.json ;;
    # Appended, not overwritten. Overwriting destroyed our managed block, so
    # the two-branch remedy added for the pre-0.36 population was never reached
    # — the fixture only ever exercised the branch that was already there.
    gitignored)      printf '.claude/\n' >> .gitignore ;;
    gitignored-ours) python3 -c "
import pathlib
p = pathlib.Path('.gitignore')
p.write_text('node_modules\n\n# >>> OpenCastle managed (do not edit) >>>\nCLAUDE.md\n.claude/agents/\n# <<< OpenCastle managed <<<\n')" ;;
  esac

  node $CLI doctor >/dev/null 2>&1 && { bad "$breakage: doctor no longer detects this"; continue; }
  ok "$breakage: doctor reports it"

  node $CLI 2>&1 | grep -q "Everything is current" \
    && bad "$breakage: status green while doctor red" || ok "$breakage: status agrees"

  # Run whatever doctor printed as the remedy — not an assumed `sync`. A failure
  # only a person can clear must say so instead of naming a command.
  # With or without the `npx` prefix. The pattern required it, and the remedy
  # added for the gitignore case does not use it — so that remedy was invisible
  # here, and the else-branch's grep did not match its wording either. The check
  # could not pass on the case it was written for, in either direction.
  remedy=$(node $CLI doctor 2>&1 | plain | grep -oE '(npx )?opencastle [a-z-]+( --[a-z]+)?' | tail -1)
  if [ -n "$remedy" ]; then
    node $CLI ${remedy#*opencastle } --yes >/dev/null 2>&1
    node $CLI doctor >/dev/null 2>&1 && ok "$breakage: '$remedy' cleared it" \
                                     || bad "$breakage: '$remedy' did not clear it"
  else
    node $CLI doctor 2>&1 | plain | grep -q "remove those entries\|by hand\|only you" \
      && ok "$breakage: names a fix only a person can apply" \
      || { bad "$breakage: no actionable remedy given"; node $CLI doctor 2>&1 | plain | tail -3; }
  fi
done

say "CLAIM 12b — a failing command leaves the install coherent"
new c12b; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib
p=pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace('# Project Instructions','# CHANGED'))"
chmod 444 CLAUDE.md
node $CLI sync --yes --force >/dev/null 2>&1; code=$?
chmod 644 CLAUDE.md
[ $code -ne 0 ] && ok "the injected failure took effect" \
                || bad "sync exited 0 — the fixture tested nothing"
[ "$(ls .claude/agents 2>/dev/null | wc -l | tr -d ' ')" -gt 0 ] \
  && ok "a failed sync left the framework directories intact" \
  || bad "a failed sync emptied the framework directories"

say "CLAIM 12c — every adapter names what it deletes"
for ide in claude-code vscode cursor; do
  new "c12c-$ide"
  case $ide in
    claude-code) printf '# R\n' > CLAUDE.md; d=.claude/agents ;;
    vscode)      d=.github/instructions ;;
    cursor)      printf 'x\n' > .cursorrules; d=.cursor/rules ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  mkdir -p "$d"; echo mine > "$d/MY-OWN.md"
  node $CLI sync --yes --force 2>&1 | grep -q "MY-OWN.md" \
    && ok "$ide names the file it removed" || bad "$ide deleted it in silence"
done

say "CLAIM 7 — every entry point preserves the stack"
new c7; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
node $CLI add sentry >/dev/null 2>&1
for cmd in "init --yes" "sync --yes --force"; do
  node $CLI $cmd >/dev/null 2>&1
  python3 -c "
import json,sys
s=json.load(open('.opencastle/manifest.json'))['stack']['techTools']
sys.exit(0 if 'sentry' in s else 1)" && ok "$cmd kept sentry" || bad "$cmd dropped sentry"
done

say "CLAIM 11/12 — stdin closed, and dry runs write nothing"
new c11; printf '# R\n' > CLAUDE.md
node $CLI init --yes </dev/null >/dev/null 2>&1 && ok "init --yes" || bad "init --yes"
node $CLI sync --reconfigure --yes </dev/null >/dev/null 2>&1 && ok "sync --reconfigure --yes" || bad "sync --reconfigure --yes"
node $CLI add sentry </dev/null >/dev/null 2>&1 && ok "add" || bad "add"
# Content, not just paths — the previous version compared `find` output, so a
# dry run that rewrote a file would have passed.
tree_hash() { find . -path ./.git -prune -o -type f -print0 | sort -z | xargs -0 shasum | shasum; }
before=$(tree_hash)
node $CLI sync --dry-run </dev/null >/dev/null 2>&1
node $CLI remove --all --dry-run </dev/null >/dev/null 2>&1
after=$(tree_hash)
[ "$before" = "$after" ] && ok "dry runs wrote nothing (content hashed)" || bad "dry run changed the tree"

say "CLAIM 8 — the removal preview matches the action, including .gitignore"
new c8; printf '# Mine\n\nKEEP\n' > CLAUDE.md; printf 'node_modules\n' > .gitignore
node $CLI init --yes >/dev/null 2>&1
preview=$(node $CLI remove --all --dry-run 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
node $CLI remove --all --yes >/dev/null 2>&1
echo "$preview" | grep -q 'Edited, not deleted' && ok "preview has an edited section" || bad "no edited section"
grep -q KEEP CLAUDE.md && ok "a file previewed as edited still exists" || bad "previewed as edited, then deleted"
grep -q node_modules .gitignore && ok ".gitignore kept the user's rules" || bad ".gitignore lost the user's rules"

say "CLAIM 9 — a v1 manifest is migrated, not crashed on"
new c9; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json');m=json.load(open(p))
m['stack']={'cms':'sanity','db':'supabase','pm':'linear'}
json.dump(m,open(p,'w'),indent=2)"
node $CLI sync --yes --force >/dev/null 2>&1 && ok "sync survived a v1 stack" || bad "sync crashed"
# `[ $? -le 1 ]` was the old test, and `bin/cli.mjs` exits 1 on any uncaught
# throw — so a doctor that died on EISDIR scored the same as a clean run. Assert
# on the output: a doctor that ran printed its check table.
out=$(node $CLI doctor 2>&1 | plain)
echo "$out" | grep -q "OpenCastle manifest" \
  && ok "doctor survived a v1 stack" \
  || { bad "doctor crashed on a v1 stack"; echo "$out" | head -3; }
python3 -c "
import json,sys
s=json.load(open('.opencastle/manifest.json'))['stack']
sys.exit(0 if 'techTools' in s else 1)" && ok "manifest migrated to v2" || bad "manifest not migrated"

say "CLAIM 10 — nothing shipped names a command that does not exist"
cd "$REPO"
npx vitest run src/cli/docs-accuracy.test.ts >/dev/null 2>&1 && ok "docs-accuracy guards pass" || bad "docs-accuracy failing"

say "CLAIM 1c — a doubled .gitignore block heals and uninstalls"
new c1c; printf 'node_modules\ndist/\n' > .gitignore; cp .gitignore "$ROOT/gi.orig"
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib,re
p=pathlib.Path('.gitignore');t=p.read_text()
m=re.search(r'# >>> OpenCastle managed.*?# <<< OpenCastle managed <<<',t,re.S)
p.write_text(t[:m.end()] + '\n\n' + m.group(0) + t[m.end():])"
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(grep -c '>>> OpenCastle managed' .gitignore)" = "1" ] && ok "sync collapsed the doubled block" || bad "still doubled"
node $CLI remove --all --yes >/dev/null 2>&1
cmp -s "$ROOT/gi.orig" .gitignore && ok ".gitignore restored byte-identical" || bad ".gitignore not restored"

# Separated by a single newline, with a user rule below — the shape that welded
# `.env.local` into a comment and stopped git ignoring it.
new c1d; printf 'node_modules\n' > .gitignore; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
printf '.env.local\n' >> .gitignore
python3 -c "
import pathlib,re
p=pathlib.Path('.gitignore');t=p.read_text()
m=re.search(r'# >>> OpenCastle managed.*?# <<< OpenCastle managed <<<',t,re.S)
p.write_text(t[:m.end()]+chr(10)+m.group(0)+t[m.end():])"
node $CLI sync --yes --force >/dev/null 2>&1
git check-ignore -q .env.local && ok "a user rule below a doubled block survives" || bad "user rule welded into a comment"

say "CLAIM 13 — sync recompiles content, on every target"
# The claim the branch is *named* for, and the one nothing tested: a generated
# file whose bytes differ from its source is rewritten by `sync`. It went
# unnoticed for a full release because every existing check asked whether files
# were *present*, and the four single-file targets kept every stale byte while
# reporting "Updated 0 framework files" and a drift the prescribed remedy could
# not clear.
c13_seed() {
  case $1 in
    claude-code) printf '# R\n' > CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# R\n' > AGENTS.md ;;
    antigravity) printf '# R\n' > GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# R\n' > .github/copilot-instructions.md ;;
    opencode)    printf '# R\n' > CLAUDE.md ;;
  esac
}
for ide in claude-code codex antigravity opencode cursor windsurf vscode; do
  new "c13-$ide"; c13_seed "$ide"
  node $CLI init --yes >/dev/null 2>&1
  # opencode has no detection trigger of its own that does not collide with
  # codex over AGENTS.md, so point the manifest at it and recompile.
  if [ "$ide" = opencode ]; then
    python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json'); m=json.load(open(p))
m['ides']=['opencode']; m['ide']='opencode'; m['stack']['ides']=['opencode']
json.dump(m,open(p,'w'),indent=2)"
    node $CLI sync --yes --force >/dev/null 2>&1
  fi

  before=$(find . -path ./.git -prune -o -type f -print | wc -l | tr -d ' ')
  # Tamper with every generated markdown file the compiler owns.
  targets=$(node --input-type=module -e "
const {IDE_ADAPTERS} = await import('$REPO/dist/cli/adapters/index.js')
const a = await IDE_ADAPTERS[process.argv[1]]()
console.log(a.getManagedPaths().framework.filter(p => p.endsWith('/')).join(' '))
" "$ide" 2>/dev/null)
  n=0
  for dir in $targets; do
    while IFS= read -r f; do
      printf 'STALE RELEASE CONTENT\n' > "$f"; n=$((n+1))
    done < <(find "$dir" -type f 2>/dev/null)
  done
  if [ "$n" = "0" ]; then bad "$ide: no generated files found to tamper with"; continue; fi

  node $CLI sync --yes --force >/dev/null 2>&1
  left=$(grep -rl 'STALE RELEASE CONTENT' $targets 2>/dev/null | wc -l | tr -d ' ')
  [ "$left" = "0" ] && ok "$ide: sync restored all $n tampered files" \
                    || bad "$ide: $left of $n files kept stale content"
  node $CLI sync --check >/dev/null 2>&1 \
    && ok "$ide: sync --check clean afterwards" \
    || bad "$ide: sync --check still reports drift its own remedy cannot clear"
  after=$(find . -path ./.git -prune -o -type f -print | wc -l | tr -d ' ')
  [ "$before" = "$after" ] && ok "$ide: file count unchanged ($after)" \
                           || bad "$ide: $before files before, $after after"
done

say "CLAIM 13b — an upgrade delivers new content to an existing install"
new c13b; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
before=$(find .claude -type f | wc -l | tr -d ' ')
find .claude -type f -name '*.md' -exec sh -c 'printf "PREVIOUS RELEASE\n" > "$1"' _ {} \;
python3 -c "
import json,pathlib
p=pathlib.Path('.opencastle/manifest.json'); m=json.load(open(p)); m['version']='0.30.0'
json.dump(m,open(p,'w'),indent=2)"
out=$(node $CLI sync --yes 2>&1 | plain)
[ "$(grep -rl 'PREVIOUS RELEASE' .claude 2>/dev/null | wc -l | tr -d ' ')" = "0" ] \
  && ok "no file kept the previous release's body" || bad "stale bodies survived the upgrade"
[ "$before" = "$(find .claude -type f | wc -l | tr -d ' ')" ] \
  && ok "the upgrade deleted nothing ($before files)" || bad "the upgrade changed the file count"
node $CLI sync --check >/dev/null 2>&1 && ok "clean after upgrade" || bad "drift after upgrade"
# The counter must describe the run, not the tree.
echo "$out" | grep -q "Updated 0 framework files" && bad "reported 0 while rewriting the tree" \
                                                  || ok "the count reflects what changed"
out2=$(node $CLI sync --yes --force 2>&1 | plain)
echo "$out2" | grep -q "Updated 0 framework files" \
  && ok "a no-op sync reports 0" || bad "a no-op sync inflated its count"

say "CLAIM 8b — whenever a backup appears, the run said so"
# The harness checked that `.opencastle-backup` existed and never that the
# command mentioned it, which is why a collapse could go silent on four of the
# seven targets through 175 green checks. The backup is the only recovery route
# for a collapse; a backup nobody is told about is not one.
c8b_seed() {
  case $1 in
    claude-code) printf '# Mine\n' > CLAUDE.md; echo CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# Mine\n' > AGENTS.md; echo AGENTS.md ;;
    antigravity) printf '# Mine\n' > GEMINI.md; echo GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules; echo .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules; echo .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# Mine\n' > .github/copilot-instructions.md; echo .github/copilot-instructions.md ;;
  esac
}
for ide in claude-code codex antigravity cursor windsurf vscode; do
  new "c8b-$ide"; root=$(c8b_seed "$ide")
  node $CLI init --yes >/dev/null 2>&1
  # Duplicate the block, as a merge that kept both sides does.
  python3 -c "
import pathlib, re, sys
S = sys.argv[1]; E = sys.argv[2]; f = pathlib.Path(sys.argv[3])
t = f.read_text(); b = re.search(re.escape(S) + '.*?' + re.escape(E), t, re.S).group(0)
f.write_text(t + chr(10) + b + chr(10))" "$START" "$END" "$root"
  out=$(node $CLI sync --yes --force 2>&1 | plain)
  if [ -f "$root.opencastle-backup" ]; then
    echo "$out" | grep -qi "collapsed a duplicated block" \
      && ok "$ide: the collapse was reported" \
      || { bad "$ide: wrote a backup and said nothing"; echo "$out" | tail -4; }
    echo "$out" | grep -q "$(basename "$root")" \
      && ok "$ide: the file was named" || bad "$ide: the file was not named"
  else
    bad "$ide: no backup written for a collapsed duplicate"
  fi
  [ "$(grep -c -- "$END" "$root")" = "1" ] && ok "$ide: one block after the collapse" \
                                           || bad "$ide: still doubled"
done

say "CLAIM 8c — a torn file is reported, not cut"
# Two blocks *and* unpaired markers. Reducing it means cutting, and cutting can
# sweep the user's own text into a block — so the tool must decline, say so, and
# keep every line of theirs.
new c8c; printf '# Mine\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib, re, sys
S = sys.argv[1]; E = sys.argv[2]; f = pathlib.Path('CLAUDE.md')
t = f.read_text(); b = re.search(re.escape(S) + '.*?' + re.escape(E), t, re.S).group(0)
f.write_text(S + chr(10) + 'MY OWN RULE' + chr(10) + b + chr(10) + E + chr(10) + b + chr(10))" "$START" "$END"
out=$(node $CLI sync --yes --force 2>&1 | plain)
grep -q 'MY OWN RULE' CLAUDE.md && ok "the user's line survived the sync" || bad "the user's line was eaten"
echo "$out" | grep -qi "cannot be reduced safely" && ok "sync said it would not reduce it" \
                                                  || { bad "sync was silent about it"; echo "$out" | tail -4; }
node $CLI doctor 2>&1 | plain | grep -qE "OpenCastle blocks?" \
  && ok "doctor names it" || bad "doctor calls a doubled file healthy"
node $CLI doctor >/dev/null 2>&1 && bad "doctor passes on a doubled file" || ok "doctor fails on it"
node $CLI sync --yes --force >/dev/null 2>&1
grep -q 'MY OWN RULE' CLAUDE.md && ok "and survived a second sync" || bad "the second sync ate it"
node $CLI remove --all --yes >/dev/null 2>&1
grep -q 'MY OWN RULE' CLAUDE.md 2>/dev/null && ok "and survived remove --all" || bad "remove --all ate it"

say "CLAIM 3d — .gitignore keeps the rules git was honouring"
new c3d; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib, re
S = '# >>> OpenCastle managed (do not edit) >>>'; E = '# <<< OpenCastle managed <<<'
p = pathlib.Path('.gitignore'); t = p.read_text()
b = re.search(re.escape(S) + '.*?' + re.escape(E), t, re.S).group(0)
p.write_text('node_modules' + chr(10) + b + chr(10) + 'keep-me' + chr(10) + S + chr(10) +
             '.env.local' + chr(10) + b + chr(10) + E + chr(10))"
git check-ignore -q .env.local && ok "git honours .env.local to begin with" || bad "fixture is wrong"
node $CLI sync --yes --force >/dev/null 2>&1
node $CLI sync --yes --force >/dev/null 2>&1
git check-ignore -q .env.local && ok ".env.local still ignored after two syncs" \
                               || bad "two syncs dropped an ignore rule"
grep -q 'keep-me' .gitignore && ok "the user's other rule survived" || bad "lost keep-me"

say "CLAIM 14 — every surface agrees, and every remedy is reachable"
# The closure that makes the four reporting surfaces one system rather than four
# opinions. For each broken state: whatever `doctor` and `sync --check` say, the
# remedy they print must either work or name a person — and they must not
# disagree about whether the project is healthy.
# `undamaged` (second argument, optional) marks the one state where every surface
# being green is the correct answer. For every other state the fixture has broken
# something, so all-green means no surface noticed — which is the property this
# function exists to test, and which its `else` arm used to score as a pass.
c14_check() {
  label=$1
  undamaged=${2:-no}
  doc=$(node $CLI doctor 2>&1 | plain); doc_code=$?
  node $CLI doctor >/dev/null 2>&1; doc_code=$?
  chk=$(node $CLI sync --check 2>&1 | plain); chk_code=$?
  node $CLI sync --check >/dev/null 2>&1; chk_code=$?
  st=$(node $CLI 2>&1 | plain)

  # 1. status must not call a project healthy while doctor or the checker is red.
  if [ $doc_code -ne 0 ] || [ $chk_code -ne 0 ]; then
    echo "$st" | grep -q "Everything is current" \
      && bad "$label: status green while doctor=$doc_code check=$chk_code" \
      || ok "$label: status agrees with doctor and the checker"
  elif [ "$undamaged" = yes ]; then
    ok "$label: undamaged, and every surface agrees"
  else
    bad "$label: the fixture broke something and no surface noticed"
  fi

  # 2. a red checker either prescribes a command that clears it, or says a
  #    person is needed. It must never prescribe one that cannot work.
  if [ $chk_code -ne 0 ]; then
    if echo "$chk" | grep -q "Needs a person"; then
      echo "$chk" | grep -q "Fix: opencastle sync" \
        && bad "$label: checker prescribed sync for a state sync refuses" \
        || ok "$label: checker names a person, not a command"
    else
      node $CLI sync --yes --force >/dev/null 2>&1
      node $CLI sync --check >/dev/null 2>&1 \
        && ok "$label: the checker's remedy cleared it" \
        || bad "$label: checker red, remedy did not clear it"
    fi
  fi

  # 3. "needs a person" has to be true. Run the command it declined to name and
  #    require the report to be unchanged — the checker used to say "no command
  #    will change these" about drift one sync cleared.
  if [ $chk_code -ne 0 ] && echo "$chk" | grep -q "Needs a person"; then
    node $CLI sync --yes --force >/dev/null 2>&1
    again=$(node $CLI sync --check 2>&1 | plain)
    echo "$again" | grep -q "Needs a person" \
      && ok "$label: 'needs a person' survived a sync, as claimed" \
      || bad "$label: sync cleared a state reported as needing a person"
  fi

  # 4. a red doctor either prescribes a command that clears it, or says so.
  if [ $doc_code -ne 0 ]; then
    if echo "$doc" | grep -q "needs a person"; then
      ok "$label: doctor names a person, not a command"
    else
      remedy=$(echo "$doc" | grep -oE "(npx )?opencastle [a-z-]+( --[a-z]+)?" | tail -1)
      if [ -n "$remedy" ]; then
        node $CLI ${remedy#*opencastle } --yes >/dev/null 2>&1
        node $CLI doctor >/dev/null 2>&1 \
          && ok "$label: doctor's remedy '$remedy' cleared it" \
          || bad "$label: doctor red, '$remedy' did not clear it"
      else
        bad "$label: doctor red with no remedy at all"
      fi
    fi
  fi
}

for state in clean doubled torn unreducible gi-doubled gi-torn gi-severed gi-severed-start gi-unreducible; do
  new "c14-$state"; printf '# House rules\n\nMY OWN RULE\n' > CLAUDE.md
  printf 'node_modules\nkeep-me\n' > .gitignore
  node $CLI init --yes >/dev/null 2>&1
  python3 - "$START" "$END" "$state" <<'PY'
import pathlib, re, sys
S, E, state = sys.argv[1], sys.argv[2], sys.argv[3]
GS = '# >>> OpenCastle managed (do not edit) >>>'
GE = '# <<< OpenCastle managed <<<'
root = pathlib.Path('CLAUDE.md'); t = root.read_text()
blk = re.search(re.escape(S) + '.*?' + re.escape(E), t, re.S).group(0)
gi = pathlib.Path('.gitignore'); g = gi.read_text()
gblk = re.search(re.escape(GS) + '.*?' + re.escape(GE), g, re.S).group(0)
if state == 'doubled':
    root.write_text(t + chr(10) + blk + chr(10))
elif state == 'torn':
    root.write_text(t.replace(E + chr(10), '', 1))
elif state == 'unreducible':
    root.write_text(S + chr(10) + 'MY OWN RULE' + chr(10) + blk + chr(10) + E + chr(10) + blk + chr(10))
elif state == 'gi-doubled':
    gi.write_text(g + chr(10) + gblk + chr(10))
elif state == 'gi-torn':
    gi.write_text(g + chr(10) + GS + chr(10))
elif state == 'gi-severed':
    gi.write_text(g.replace(GE + chr(10), '', 1))
elif state == 'gi-severed-start':
    gi.write_text(g.replace(GS + chr(10), '', 1))
elif state == 'gi-unreducible':
    gi.write_text('node_modules' + chr(10) + gblk + chr(10) + 'keep-me' + chr(10) + GS +
                  chr(10) + '.env.local' + chr(10) + gblk + chr(10) + GE + chr(10))
PY
  if [ "$state" = clean ]; then c14_check "$state" yes; else c14_check "$state"; fi
  # And nothing of the user's is ever lost while all that is going on.
  case $state in
    gi-*) grep -q 'keep-me\|node_modules' .gitignore && ok "$state: their rules survived" \
                                                    || bad "$state: lost their rules" ;;
    *)    grep -q 'MY OWN RULE' CLAUDE.md && ok "$state: their line survived" \
                                          || bad "$state: lost their line" ;;
  esac
done

say "CLAIM 9b — init over an existing install compiles what it records"
# `install` is scaffold-once, so re-init left every generated file untouched and
# then wrote the current version into the manifest: the record said one release
# and the tree was another. Recoverable, because the drift checker compares
# content rather than version numbers — but a command must not assert work it
# has not done.
new c9b; printf '# Mine\n\nMY RULE\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
find .claude -name '*.md' -exec sh -c 'printf "STALE\n" > "$1"' _ {} \;
python3 -c "
import json,pathlib; p=pathlib.Path('.opencastle/manifest.json'); m=json.load(open(p)); m['version']='0.30.0'
json.dump(m,open(p,'w'),indent=2)"
echo mine > .claude/MY-OWN.md
node $CLI init --yes >/dev/null 2>&1
[ "$(grep -rl STALE .claude 2>/dev/null | wc -l | tr -d ' ')" = "0" ] \
  && ok "re-init recompiled the tree it stamped" || bad "re-init recorded a version it did not compile"
node $CLI sync --check >/dev/null 2>&1 && ok "clean afterwards" || bad "drift after re-init"
grep -q 'MY RULE' CLAUDE.md && ok "their root-file line survived" || bad "re-init ate their line"
[ -f .claude/MY-OWN.md ] && ok "their own file under .claude/ survived" || bad "re-init deleted their file"

say "CLAIM 6d — no surface calls a project healthy while another is red"
# Injected filesystem faults, which is the only route I could find to a
# status/doctor divergence — and the route that found three of them. `status`
# derived its verdict from half of `doctor`'s checks and treated a comparison
# that *threw* as "no drift".
# Extended with the shapes two reviewers used to find `doctor` issuing a clean
# bill: a directory wearing a generated file's name in a check that declares no
# `countFilter`, an unreadable skill folder one level down, and faults on the
# customizable half of the tree. The list had no entry of either kind, which is
# why all of them passed 427 checks.
for fault in unreadable-dir file-where-dir-belongs unreadable-root unreadable-matrix unreadable-mcp unreadable-gitignore mcp-is-a-dir dir-wearing-unfiltered-name unreadable-nested-skill unreadable-oc-agents; do
  new "c6d-$fault"; printf '# R\n' > CLAUDE.md
  node $CLI init --yes >/dev/null 2>&1
  # The path the fixture broke, asserted to appear in whatever the tool prints.
  # `EISDIR` is raised on the descriptor, so it carries no `.path` and the
  # catch-all had nothing to name: `sync` died anonymously in the middle of a
  # hundred-file install while the gate, reading the same tree, named it.
  faulted=""
  case $fault in
    unreadable-dir)       chmod 000 .claude/agents; faulted=".claude/agents" ;;
    file-where-dir-belongs) rm -rf .claude/agents; printf 'oops' > .claude/agents; faulted=".claude/agents" ;;
    unreadable-root)      chmod 000 CLAUDE.md; faulted="CLAUDE.md" ;;
    unreadable-matrix)    rm -f .opencastle/agents/skill-matrix.json
                          mkdir -p .opencastle/agents/skill-matrix.json
                          faulted=".opencastle/agents/skill-matrix.json" ;;
    # Each of these was the twin of a guard added a round earlier: the same
    # shape, one file over, still unguarded.
    unreadable-mcp)       chmod 000 .mcp.json; faulted=".mcp.json" ;;
    unreadable-gitignore) chmod 000 .gitignore; faulted=".gitignore" ;;
    mcp-is-a-dir)         rm -f .mcp.json; mkdir .mcp.json; faulted=".mcp.json" ;;
    dir-wearing-unfiltered-name)
                          f=$(ls .claude/commands/*.md 2>/dev/null | head -1)
                          [ -n "$f" ] && { rm -f "$f"; mkdir "$f"; faulted="$f"; } ;;
    unreadable-nested-skill)
                          d=$(ls -d .claude/skills/*/ 2>/dev/null | head -1)
                          [ -n "$d" ] && { chmod 000 "$d"; faulted="${d%/}"; } ;;
    unreadable-oc-agents) chmod 000 .opencastle/agents; faulted=".opencastle/agents" ;;
  esac
  node $CLI doctor >/dev/null 2>&1; dr=$?
  node $CLI sync --check >/dev/null 2>&1; ck=$?
  # The fault has to bite, or the arm below is a free pass — the same shape the
  # chmod fixtures were fixed for.
  [ $dr -ne 0 ] || [ $ck -ne 0 ] && ok "$fault: the fault registered" \
                                 || bad "$fault: neither surface noticed — the fixture tested nothing"
  # And the full closure, not just agreement: every remedy printed for a
  # filesystem fault must work or name a person. `doctor` used to answer both
  # of these with "run sync", and `sync` exits non-zero on the same path.
  c14_check "$fault"
  # And whatever failed, it named the file rather than dying anonymously.
  #
  # "No stack trace" was the whole test, which a one-line
  # `✗ EISDIR: illegal operation on a directory, read` passes while naming nothing
  # to act on — and two of those were live while this assertion was green. The
  # path is what the user needs, so the path is what is asserted.
  out=$(node $CLI doctor 2>&1 | plain; node $CLI sync --yes --force 2>&1 | plain)
  echo "$out" | grep -qE "at async|Node\.js v" && bad "$fault: printed a stack trace" \
                                               || ok "$fault: failed cleanly"
  if [ -n "$faulted" ]; then
    echo "$out" | grep -qF "$faulted" \
      && ok "$fault: named $faulted" \
      || bad "$fault: never named $faulted — nothing to act on"
  else
    bad "$fault: the fixture recorded no path, so nothing was asserted about naming"
  fi
  chmod 755 .claude/agents 2>/dev/null; chmod 644 CLAUDE.md 2>/dev/null
  chmod 644 .mcp.json .gitignore 2>/dev/null
  chmod 755 .opencastle .opencastle/agents 2>/dev/null
  chmod -R 755 .claude/skills 2>/dev/null
done

say "CLAIM 14b — anything called unreducible really is"
# The generalisation reviewers asked for: every drift entry the checker files
# under "needs a person" must survive the command it declined to name.
#
# The fixture builds a genuinely *unreducible* file — two complete blocks plus a
# stray marker. It used to build a merely torn one, which the checker classifies
# as ordinary drift, so the branch this claim is named for never executed once.
new c14b; printf '# House rules\n\nMY OWN RULE\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
python3 -c "
import pathlib, re, sys
S, E = sys.argv[1], sys.argv[2]
p = pathlib.Path('CLAUDE.md'); t = p.read_text()
b = re.search(re.escape(S) + '.*?' + re.escape(E), t, re.S).group(0)
p.write_text('MY OWN RULE' + chr(10) + b + chr(10) + E + chr(10) + b + chr(10))
" "$START" "$END"
out=$(node $CLI sync --check 2>&1 | plain)
if echo "$out" | grep -q "Needs a person"; then
  ok "the unreducible state reached the checker"
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI sync --check >/dev/null 2>&1 \
    && bad "called it unreducible, then sync cleared it" \
    || ok "unreducible survived a sync, as claimed"
else
  bad "the fixture did not produce an unreducible state — this claim tests nothing"
  echo "$out" | head -4
fi
grep -q 'MY OWN RULE' CLAUDE.md && ok "their line survived" || bad "their line was eaten"

say "CLAIM 3e — a byte that is not valid UTF-8 survives"
# Everything outside our markers is the user's, including bytes a decoder
# cannot read. They used to come back as U+FFFD, and in .gitignore a re-spelled
# pattern stops matching — the rule is gone and the file it protected is
# committable, with nothing said.
new c3e
printf 'Caf\xe9 rules: use pnpm\n' > CLAUDE.md
cp CLAUDE.md "$ROOT/enc.orig"
printf 'secrets-caf\xe9/\n' > .gitignore
cp .gitignore "$ROOT/enc.gi"
node $CLI init --yes >/dev/null 2>&1
printf 'secrets-caf\xe9/x\n' | git check-ignore --stdin >/dev/null 2>&1 \
  && ok "git still honours a rule with a non-UTF-8 byte" \
  || bad "init broke a rule containing a non-UTF-8 byte"
node $CLI remove --all --yes >/dev/null 2>&1
cmp -s "$ROOT/enc.orig" CLAUDE.md && ok "root file byte-identical" \
  || { bad "a non-UTF-8 byte was rewritten"; xxd CLAUDE.md | head -1; }
# The baseline this claim copied and then never looked at — so the *removal*
# path for a non-UTF-8 ignore rule, which is what the comment above describes,
# was set up and left unasserted.
if [ -f .gitignore ]; then
  cmp -s "$ROOT/enc.gi" .gitignore && ok ".gitignore byte-identical after removal" \
    || { bad "removal rewrote a non-UTF-8 ignore rule"; xxd .gitignore | head -1; }
else
  # Deleting is only right if there was nothing of theirs in it. This fixture writes
  # `secrets-café/` *before* `init`, so the file always held a rule of the user's —
  # and this arm used to print `ok` for its destruction, which is precisely the loss
  # the claim above exists to rule out.
  if [ -s "$ROOT/enc.gi" ]; then
    bad "removal deleted a .gitignore that held the user's non-UTF-8 rule"
  else
    ok ".gitignore held nothing but our block and was removed"
  fi
fi

say "CLAIM 13c — upgrading a real previous-release install"
# Synthesised the way the previous release actually wrote it, rather than with a
# fixture this branch produces. Round 15's worst defect lived exactly here: the
# stale-half warning excluded the population it was written for, and every
# surface called the result healthy.
c13c_seed() {
  # A pre-marker root file: our old banner, our old header, our old opening line.
  printf '# Project Instructions\n\nAll conventions, architecture, and project context are embedded below. Skills are in `.claude/skills/`.\n\n## Agent Definitions\n\n- API Designer\n\n## Available Skills\n\n- backbone-scaffolding\n' > CLAUDE.md
}
for shape in rules-above rules-below untouched; do
  new "c13c-$shape"; c13c_seed
  case $shape in
    rules-above) python3 -c "
import pathlib;p=pathlib.Path('CLAUDE.md');p.write_text('# MY OWN RULES'+chr(10)*2+'Never force-push main.'+chr(10)*2+p.read_text())" ;;
    rules-below) printf '\n## MY OWN RULES\n\nNever force-push main.\n' >> CLAUDE.md ;;
  esac
  out=$(node $CLI init --yes 2>&1 | plain)

  case $shape in
    rules-above)
      # Their writing came first, so the file is appended to rather than
      # replaced — and the superseded half is still in there.
      grep -q 'MY OWN RULES' CLAUDE.md && ok "$shape: their rules kept" || bad "$shape: their rules lost"
      echo "$out" | grep -qi "earlier version" && ok "$shape: the stale half was reported" \
                                               || bad "$shape: nothing said about the stale half"
      node $CLI doctor >/dev/null 2>&1 && bad "$shape: doctor calls it healthy" \
                                       || ok "$shape: doctor names it"
      node $CLI sync --check >/dev/null 2>&1 && bad "$shape: the CI gate passes it" \
                                             || ok "$shape: the CI gate fails it"
      node $CLI 2>&1 | plain | grep -q "Everything is current" \
        && bad "$shape: status green while others are red" || ok "$shape: status agrees"
      ;;
    rules-below|untouched)
      # No marker, and the whole file is ours: adopted, loudly, with a backup.
      echo "$out" | grep -qi "earlier version" && ok "$shape: the adoption was reported" \
                                               || bad "$shape: adopted in silence"
      [ -f CLAUDE.md.opencastle-backup ] && ok "$shape: a backup was written" \
                                         || bad "$shape: adopted with no backup"
      if [ "$shape" = rules-below ]; then
        grep -q 'MY OWN RULES' CLAUDE.md.opencastle-backup \
          && ok "$shape: their appended text is in the backup" \
          || bad "$shape: their appended text is nowhere"
      fi
      node $CLI sync --check >/dev/null 2>&1 && ok "$shape: clean afterwards" \
                                             || bad "$shape: drift after adoption"
      ;;
  esac
  [ "$(grep -c -- "$END" CLAUDE.md)" = "1" ] && ok "$shape: exactly one block" \
                                             || bad "$shape: $(grep -c -- "$END" CLAUDE.md) blocks"
done

say "CLAIM 3f — a byte-order mark changes nothing but the bytes"
# Three bytes in front of the heading made the start marker stop being at column
# zero, so the block was invisible, `sync` appended a second one, the file
# doubled to two full instruction sets, and every surface reported health.
c3f_seed() {
  case $1 in
    claude-code) echo CLAUDE.md ;;
    codex)       mkdir -p .codex; echo AGENTS.md ;;
    antigravity) echo GEMINI.md ;;
    cursor)      echo .cursorrules ;;
    windsurf)    echo .windsurfrules ;;
    vscode)      mkdir -p .github; echo .github/copilot-instructions.md ;;
  esac
}
for ide in claude-code codex antigravity cursor windsurf vscode; do
  new "c3f-$ide"; root=$(c3f_seed "$ide"); printf '# R\n' > "$root"
  node $CLI init --yes >/dev/null 2>&1
  before=$(wc -c < "$root" | tr -d ' ')
  python3 -c "
import pathlib, sys
p = pathlib.Path(sys.argv[1]); p.write_bytes(b'\xef\xbb\xbf' + p.read_bytes())" "$root"
  node $CLI sync --yes --force >/dev/null 2>&1
  after=$(wc -c < "$root" | tr -d ' ')
  [ "$after" -eq "$((before + 3))" ] && ok "$ide: the BOM costs three bytes and nothing else" \
    || bad "$ide: $before + 3 expected, got $after"
  [ "$(grep -c -- "$END" "$root")" = "1" ] && ok "$ide: still one block" \
    || bad "$ide: $(grep -c -- "$END" "$root") blocks"
  node $CLI remove --all --yes >/dev/null 2>&1
  if [ -f "$root" ]; then
    grep -q 'Project Instructions\|Copilot Instructions' "$root" \
      && bad "$ide: our body survived the uninstall" || ok "$ide: uninstall left nothing of ours"
  else
    # The fixture seeds `# R` into every root file before `init`, so a co-owned file
    # that is gone after the uninstall took the user's line with it. That is the loss
    # the markers exist to prevent, and this arm used to call it a pass.
    bad "$ide: uninstall deleted a co-owned root file that held the user's line"
  fi
done

say "CLAIM 15 — doctor and the CI gate never disagree"
# Stated once, over every damage shape the suite knows. Four findings in rounds
# 15-17 were instances of this one property failing, each reported separately
# because nothing asserted the property itself: a torn .gitignore red on one
# surface and green on the other, a doubled .gitignore the reverse, an MCP
# config that is a directory, a manifest naming no target.
#
# They need not produce the same *exit code* — a warning is not a failure — but
# neither may report health while the other reports a fault a person must fix.
c15_states="clean gi-block-deleted gi-doubled gi-torn root-severed root-doubled
            manifest-empty mcp-is-dir mcp-unparseable stale-legacy
            gi-bom gi-bom-block-first gi-mixed-endings
            dir-wearing-unfiltered-name unreadable-oc-agents"
# Shapes that are not damage, so all-green is the right answer — and is asserted,
# not merely permitted.
#
# `gi-bom-block-first` is here because it is fixed. A mark in front of our own
# opening marker is exactly what two round-21 reviewers found breaking every
# surface at once, with `sync` a no-op and the diagnosis false about the file. The
# readers agree about it now, so the honest assertion is that the file is accepted
# as it stands. If one of them ever calls it a fault again, this fails.
c15_benign="clean gi-bom gi-bom-block-first"
# Faults in the *tree*, as opposed to drift in the *content*. For these a green
# `doctor` is a defect however loudly it warns about something else: the gate is
# red because a person has to act, and this is the command that tells them so.
c15_structural="mcp-is-dir mcp-unparseable manifest-empty root-severed
                dir-wearing-unfiltered-name unreadable-oc-agents"
for state in $c15_states; do
  new "c15-$state"; printf '# House rules\n\nMY OWN RULE\n' > CLAUDE.md
  printf 'node_modules\n' > .gitignore
  node $CLI init --yes >/dev/null 2>&1
  python3 - "$START" "$END" "$state" <<'PY'
import pathlib, re, sys, json
S, E, state = sys.argv[1], sys.argv[2], sys.argv[3]
GS = '# >>> OpenCastle managed (do not edit) >>>'
GE = '# <<< OpenCastle managed <<<'
root = pathlib.Path('CLAUDE.md'); gi = pathlib.Path('.gitignore')
def block(p, s, e):
    return re.search(re.escape(s) + '.*?' + re.escape(e), p.read_text(), re.S).group(0)
if state == 'gi-block-deleted':
    gi.write_text(re.sub(re.escape(GS) + '.*?' + re.escape(GE), '', gi.read_text(), flags=re.S).strip() + chr(10))
elif state == 'gi-doubled':
    gi.write_text(gi.read_text() + chr(10) + block(gi, GS, GE) + chr(10))
elif state == 'gi-torn':
    gi.write_text(gi.read_text().replace(GE + chr(10), '', 1))
elif state == 'root-severed':
    root.write_text(root.read_text().replace(E + chr(10), '', 1))
elif state == 'root-doubled':
    root.write_text(root.read_text() + chr(10) + block(root, S, E) + chr(10))
elif state == 'manifest-empty':
    pathlib.Path('.opencastle/manifest.json').write_text('{"version":"0.35.3","ides":[]}')
elif state == 'mcp-is-dir':
    import os, shutil
    for c in ('.mcp.json', '.vscode/mcp.json'):
        q = pathlib.Path(c)
        if q.exists(): q.unlink(); q.mkdir()
elif state == 'mcp-unparseable':
    for c in ('.mcp.json', '.vscode/mcp.json'):
        q = pathlib.Path(c)
        if q.exists(): q.write_text('{ not json')
elif state == 'gi-bom':
    # A mark in front of a file whose *first* line is a user rule.
    gi = pathlib.Path('.gitignore')
    gi.write_bytes(b'\xef\xbb\xbf' + gi.read_bytes())
elif state == 'gi-bom-block-first':
    # And in front of one whose first line is our start marker — which is exactly
    # what `init` writes on a project that had no `.gitignore`. Two reviewers
    # found this shape independently: every surface red, `sync` a no-op, and the
    # diagnosis ("0 start markers") false about a file holding one complete pair.
    gi = pathlib.Path('.gitignore')
    body = gi.read_text()
    at = body.index(GS)
    gi.write_bytes(b'\xef\xbb\xbf' + body[at:].encode() + body[:at].encode())
elif state == 'gi-mixed-endings':
    # One file, more than one terminator. Uniform conversion cannot produce it and
    # an ordinary editing history can: a CRLF checkout with a line appended by a
    # Unix script.
    gi = pathlib.Path('.gitignore')
    text = gi.read_text()
    out, flip = [], 0
    for line in text.split(chr(10)):
        out.append(line + (chr(13) + chr(10) if flip % 3 == 0 else
                           chr(13) if flip % 3 == 1 else chr(10)))
        flip += 1
    gi.write_text(''.join(out))
elif state == 'dir-wearing-unfiltered-name':
    import glob
    for pat in ('.claude/commands/*.md', '.github/prompts/*.prompt.md'):
        hit = sorted(glob.glob(pat))
        if hit:
            q = pathlib.Path(hit[0]); q.unlink(); q.mkdir()
            break
elif state == 'unreadable-oc-agents':
    import os
    os.chmod('.opencastle/agents', 0)
elif state == 'stale-legacy':
    root.write_text('# Project Instructions' + chr(10)*2 +
                    'All conventions, architecture, and project context are embedded below.' +
                    chr(10)*2 + root.read_text())
PY
  doc=$(node $CLI doctor 2>&1 | plain); node $CLI doctor >/dev/null 2>&1; dr=$?
  chk=$(node $CLI sync --check 2>&1 | plain); node $CLI sync --check >/dev/null 2>&1; ck=$?
  st=$(node $CLI 2>&1 | plain)

  # Neither surface may call the project healthy while the other names a fault.
  #
  # Benign shapes are asserted green rather than merely allowed to be, because
  # "both surfaces agree" passes when they agree on a fault too — so a regression
  # that turned one of these red again would have slipped through that arm.
  if case " $c15_benign " in *" $state "*) true ;; *) false ;; esac; then
    { [ $dr -eq 0 ] && [ $ck -eq 0 ]; } \
      && ok "$state: not a fault, and every surface is quiet" \
      || bad "$state: nothing is wrong with this file, but doctor=$dr gate=$ck"
  elif [ $dr -ne 0 ] && [ $ck -eq 0 ]; then
    echo "$chk" | grep -q "match their sources" \
      && bad "$state: doctor=1 but the CI gate reports everything matching" \
      || ok "$state: gate is quiet but not claiming health"
  elif [ $ck -ne 0 ] && [ $dr -eq 0 ]; then
    # `grep -qi warning` used to satisfy this, and every healthy install prints
    # "All checks passed with 1 warning(s)." — so the arm could not fail, and the
    # property it guards is the one three round-20 findings violated.
    #
    # A content edit legitimately leaves `doctor` green: it checks shape and
    # presence, the gate compares bytes. A *structural* fault does not — if the
    # tree is malformed, the command people run when something is wrong has to
    # say so. Which kind each state is, is known here, so it is asserted here.
    case " $c15_structural " in
      *" $state "*)
        bad "$state: a structural fault, and doctor reports a clean bill" ;;
      *)
        ok "$state: content drift — gate red, doctor legitimately quiet" ;;
    esac
  elif [ $dr -ne 0 ] && [ $ck -ne 0 ]; then
    ok "$state: both surfaces name the fault"
  else
    # Agreement is not the property. Two surfaces can agree by both being wrong,
    # and this arm scored that as a pass — the fixture damaged the project and
    # neither the diagnostic nor the CI gate noticed.
    bad "$state: the fixture broke something and neither surface noticed"
  fi

  # And status never contradicts either of them.
  if [ $dr -ne 0 ] || [ $ck -ne 0 ]; then
    echo "$st" | grep -q "Everything is current" \
      && bad "$state: status green while doctor=$dr gate=$ck" \
      || ok "$state: status agrees"
  fi
  # A writing command, then the check. Everything above this point only reads —
  # `doctor`, `sync --check` and the bare status contain no write between them — so
  # "their line survived" was asserted against three commands that could not have
  # removed it. The line has to survive the command that rewrites the file.
  node $CLI sync --yes --force >/dev/null 2>&1
  grep -q 'MY OWN RULE' CLAUDE.md 2>/dev/null && ok "$state: their line survived a real sync" \
                                              || bad "$state: their line was lost"
  chmod 755 .opencastle .opencastle/agents 2>/dev/null
done

say "CLAIM 12h — a target that fails does not orphan the ones that worked"
# `init` ran its adapter loop with no guard and wrote the manifest after it, so
# a second target throwing left the first target's whole tree on disk with no
# manifest: the front door said "not set up", `sync` said run `init`, `init`
# failed identically, and `remove --all` refused to uninstall what it had just
# installed. A single-target install writes the root file first and throws
# before anything lands, which is why two targets were needed to see it.
for fault in readonly-second dir-second; do
  new "c12h-$fault"; mkdir -p .claude .github
  printf '# House rules\n\nMY OWN RULE\n' > CLAUDE.md
  case $fault in
    readonly-second) printf '# Copilot\n\nTHEIR TEXT\n' > .github/copilot-instructions.md
                     chmod 444 .github/copilot-instructions.md ;;
    dir-second)      rm -rf .github/copilot-instructions.md
                     mkdir -p .github/copilot-instructions.md ;;
  esac
  out=$(node $CLI init --yes 2>&1 | plain)
  files=$(find .claude -type f 2>/dev/null | wc -l | tr -d ' ')
  if [ "$files" -gt 0 ]; then
    [ -f .opencastle/manifest.json ] \
      && ok "$fault: the working target is recorded, not orphaned" \
      || bad "$fault: $files files on disk and no manifest"
    echo "$out" | grep -qi "could not be installed" \
      && ok "$fault: the failing target was named" \
      || bad "$fault: the failure was not reported"
    node $CLI 2>&1 | plain | grep -q "not set up" \
      && bad "$fault: the front door calls it uninstalled" \
      || ok "$fault: the front door sees the install"
  else
    # The whole point of this fixture is a *partial* install: one target fails and
    # the others must still be recorded. Nothing landing means the fixture never
    # reached the state the claim is about, so there is nothing to be pleased with.
    bad "$fault: no files landed at all — the partial-install fixture tested nothing"
  fi
  chmod 644 .github/copilot-instructions.md 2>/dev/null
  rm -rf .github/copilot-instructions.md 2>/dev/null
  printf '# Copilot\n' > .github/copilot-instructions.md 2>/dev/null
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI doctor >/dev/null 2>&1 && ok "$fault: recovers once the fault is fixed" \
                                   || bad "$fault: still broken after the fault is fixed"
done

say "CLAIM 16 — .gitignore converges from any damage, in one sync"
# Every shape `.gitignore` has failed in across the review history, asserted
# together. It was failing repeatedly because it was being maintained with the
# root files' machinery — collapse, torn, severed, unreducible — and none of
# that is needed here: our block is a constant, so it is rebuilt rather than
# maintained, and the worst case of a mistake is a duplicate ignore rule git
# does not care about rather than a second set of instructions an assistant
# obeys. One sync must fix all of these, and a second must change nothing.
# `bom`, `bom-first` and `mixed-endings` were the gaps. This list is the alphabet
# CLAIM 16 explores, and a shape absent from it is a shape nothing checks: a mark
# in front of our own opening marker left every surface red with `sync` a no-op,
# and a file mixing terminators was not a fixed point of the command CI runs twice.
for shape in doubled torn-end torn-start block-gone rules-gone file-gone crlf cr-only both-gone reordered marker-trailing bom bom-first mixed-endings; do
  new "c16-$shape"; printf '# R\n' > CLAUDE.md
  printf 'node_modules\nkeep-me\n' > .gitignore
  node $CLI init --yes >/dev/null 2>&1
  printf 'S=1\n' > .env
  python3 - "$shape" <<'PY'
import pathlib, re, sys
GS = '# >>> OpenCastle managed (do not edit) >>>'
GE = '# <<< OpenCastle managed <<<'
p = pathlib.Path('.gitignore'); t = p.read_text()
b = re.search(re.escape(GS) + '.*?' + re.escape(GE), t, re.S).group(0)
s = sys.argv[1]
if s == 'doubled':          p.write_text(t + chr(10) + b + chr(10))
elif s == 'torn-end':       p.write_text(t.replace(GE + chr(10), '', 1))
elif s == 'torn-start':     p.write_text(t.replace(GS + chr(10), '', 1))
elif s == 'block-gone':     p.write_text(re.sub(re.escape(GS)+'.*?'+re.escape(GE), '', t, flags=re.S).strip() + chr(10))
elif s == 'rules-gone':     p.write_text(t.replace(chr(10) + '.env' + chr(10), chr(10), 1))
elif s == 'file-gone':      p.unlink()
elif s == 'crlf':           p.write_bytes(t.replace(chr(10), chr(13)+chr(10)).encode())
elif s == 'both-gone':      p.write_text(t.replace(GS+chr(10), '', 1).replace(GE+chr(10), '', 1))
elif s == 'reordered':      p.write_text(b + chr(10) + 'node_modules' + chr(10) + 'keep-me' + chr(10))
elif s == 'marker-trailing': p.write_text(t.replace(GS, GS + ' and a note', 1))
elif s == 'cr-only':        p.write_bytes(t.replace(chr(10), chr(13)).encode())
elif s == 'bom':            p.write_bytes(b'\xef\xbb\xbf' + t.encode())
elif s == 'bom-first':
    at = t.index(GS)
    p.write_bytes(b'\xef\xbb\xbf' + t[at:].encode() + t[:at].encode())
elif s == 'mixed-endings':
    parts, flip, out = t.split(chr(10)), 0, []
    for line in parts:
        out.append(line + (chr(13) + chr(10) if flip % 3 == 0 else
                           chr(13) if flip % 3 == 1 else chr(10)))
        flip += 1
    p.write_bytes(''.join(out).encode())
PY
  node $CLI sync --yes --force >/dev/null 2>&1
  git -c core.excludesFile=/dev/null check-ignore -q .env && ok "$shape: .env is ignored again" || bad "$shape: .env still committable"
  [ "$(grep -c -- '>>> OpenCastle managed' .gitignore)" = "1" ] \
    && ok "$shape: exactly one block" \
    || bad "$shape: $(grep -c -- '>>> OpenCastle managed' .gitignore) blocks"
  node $CLI sync --check >/dev/null 2>&1 && ok "$shape: the gate is green" || bad "$shape: gate still red"
  node $CLI doctor >/dev/null 2>&1 && ok "$shape: doctor is green" || bad "$shape: doctor still red"
  # The user's own rule survives everything except their own deletion of the file.
  case $shape in
    file-gone) ok "$shape: (their rules went with the file they deleted)" ;;
    *) grep -q 'keep-me' .gitignore && ok "$shape: their rule survived" || bad "$shape: their rule was lost" ;;
  esac
  # And it is a fixed point.
  cp .gitignore "$ROOT/c16.$shape"
  node $CLI sync --yes --force >/dev/null 2>&1
  cmp -s "$ROOT/c16.$shape" .gitignore && ok "$shape: a second sync changes nothing" \
                                       || bad "$shape: not idempotent"
done

say "CLAIM 12d — a failing init leaves the install coherent too"
# CLAIM 12b tests `sync` only, which is why `init` shipped a re-init path that
# emptied every framework directory before writing a byte.
for cmd in "init --yes" "sync --yes --force"; do
  new "c12d-$(echo "$cmd" | tr ' -' '__')"
  printf '# R\n' > CLAUDE.md; printf 'x\n' > .cursorrules
  node $CLI init --yes >/dev/null 2>&1
  before=$(find .claude .cursor -type f 2>/dev/null | wc -l | tr -d ' ')
  python3 -c "
import pathlib
p=pathlib.Path('CLAUDE.md'); p.write_text(p.read_text().replace('# Project Instructions','# CHANGED'))"
  chmod 444 CLAUDE.md
  # Captured before the pipe: `$?` after `cmd | plain` is sed's exit status, not
  # the command's, so the code was always 0 and the check below always fired.
  out=$(node $CLI $cmd 2>&1); code=$?
  out=$(printf '%s' "$out" | plain)
  chmod 644 CLAUDE.md
  # The injected failure has to actually bite, or "the tree survived" is true of
  # a run that simply succeeded — the assertion passes identically either way,
  # and would go on passing anywhere the chmod does not apply (CI as root).
  #
  # "Bit" means non-zero *or* named: `init` no longer aborts on one target's
  # failure, because doing so left the targets that had worked on disk with no
  # manifest and nothing able to reach them. It reports and carries on.
  if [ $code -ne 0 ] || echo "$out" | grep -qi "could not be installed"; then
    ok "$cmd: the injected failure took effect"
  else
    bad "$cmd: exited 0 and said nothing — the fixture tested nothing"
  fi
  after=$(find .claude .cursor -type f 2>/dev/null | wc -l | tr -d ' ')
  [ "$after" -gt 0 ] && ok "$cmd: framework directories still populated ($after files)" \
                     || bad "$cmd: emptied the framework directories (was $before)"
done

say "CLAIM 12e — no command leaves an empty directory it created"
for ide in claude-code codex antigravity opencode cursor windsurf vscode; do
  new "c12e-$ide"
  case $ide in
    claude-code) printf '# R\n' > CLAUDE.md ;;
    codex)       mkdir -p .codex; printf '# R\n' > AGENTS.md ;;
    antigravity) printf '# R\n' > GEMINI.md ;;
    cursor)      printf 'x\n' > .cursorrules ;;
    windsurf)    printf 'x\n' > .windsurfrules ;;
    vscode)      mkdir -p .github; printf '# R\n' > .github/copilot-instructions.md ;;
    opencode)    printf '# R\n' > CLAUDE.md; printf '{"name":"p"}\n' > opencode.json ;;
  esac
  node $CLI init --yes >/dev/null 2>&1
  # After a sync, not only after init: the run directories only exist once
  # something has run, so the fixture never created what it was checking for.
  node $CLI sync --yes --force >/dev/null 2>&1
  node $CLI remove --all --yes >/dev/null 2>&1
  empties=$(find . -path ./.git -prune -o -type d -empty -print 2>/dev/null | grep -v '^\./\.git' | grep -v '^\.$' | tr '\n' ' ')
  [ -z "$empties" ] && ok "$ide: nothing left empty" || bad "$ide: left behind $empties"
done

say "CLAIM 12f — a rename that differs only in case is not deleted"
# macOS and Windows match filenames case-insensitively, so the compiler writes
# into the existing file under its existing name; the sweep then compared the
# name it asked for against the name on disk and removed what it had written.
new c12f; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
mv .claude/agents/architect.agent.md .claude/agents/Architect.agent.md
node $CLI sync --yes --force >/dev/null 2>&1
[ "$(find .claude/agents -iname 'architect.agent.md' | wc -l | tr -d ' ')" = "1" ] \
  && ok "the file survives a case-only rename" || bad "sync deleted the file it just wrote"
node $CLI sync --check >/dev/null 2>&1 && ok "check clean after a case-only rename" \
                                       || bad "case-only rename leaves drift"

say "CLAIM 6b — every printed remedy is a command that works"
# The MCP message told the user to run `sync`, which short-circuits when nothing
# has drifted — and the MCP config is not a path the drift checker compares.
new c6b; printf '# R\n' > CLAUDE.md; echo '{"name":"p","dependencies":{"@sentry/node":"^8"}}' > package.json
mkdir -p .vscode; printf '{\n  // JSONC\n  "mcpServers": {}\n}\n' > .mcp.json
out=$(node $CLI init --yes </dev/null 2>&1 | plain)
echo "$out" | grep -q "not valid JSON" && ok "init named the unreadable config" \
                                       || bad "init did not name it"
remedy=$(echo "$out" | grep -oE 'opencastle sync( --[a-z]+)?' | tail -1)
printf '{\n  "mcpServers": {}\n}\n' > .mcp.json       # the user fixes the file
node $CLI ${remedy#opencastle } --yes >/dev/null 2>&1
[ "$(grep -c sentry .mcp.json)" -gt 0 ] && ok "'$remedy' added the MCP servers" \
                                        || bad "'$remedy' did not add the MCP servers"

say "CLAIM 6c — doctor never prescribes a command that refuses to run"
new c6c; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
node $CLI remove --keep-files --yes >/dev/null 2>&1
out=$(node $CLI doctor 2>&1 | plain)
remedy=$(echo "$out" | grep -oE '(npx )?opencastle [a-z-]+' | tail -1)
if [ -n "$remedy" ]; then
  node $CLI ${remedy#*opencastle } --yes >/dev/null 2>&1
  code=$?
  [ $code -eq 0 ] && ok "'$remedy' runs on a manifest-less install" \
                  || bad "'$remedy' exits $code — doctor named a command that refuses"
else
  bad "doctor named no remedy for a missing manifest"
fi

say "CLAIM 3b — a co-owned JSON config keeps every key the user put in it"
# Byte fidelity is claimed for markdown, where the block is delimited and the
# rest is untouched. A JSON config we merge servers into is round-tripped
# through a parser, so it comes back canonically formatted — what must hold is
# that every key of theirs survives with the same value, and that nothing of
# ours is left. Asserted rather than assumed: `stripManagedMcpServers` used to
# rewrite the file even when it removed nothing at all.
new c3b; printf '# R\n' > CLAUDE.md
printf '{"name":"p","agent":{"build":{"model":"anthropic/claude-opus-4"}}}\n' > opencode.json
cp opencode.json "$ROOT/oc.orig"
node $CLI init --yes >/dev/null 2>&1
node $CLI remove --all --yes >/dev/null 2>&1
if [ ! -f opencode.json ]; then
  bad "opencode.json was deleted — it is the user's whole project config"
else
  python3 -c "
import json, sys
a = json.load(open('$ROOT/oc.orig')); b = json.load(open('opencode.json'))
missing = [k for k, v in a.items() if k not in b or b[k] != v]
sys.exit(1 if missing else 0)" \
    && ok "every key the user wrote survived" || bad "keys were lost or changed"
  grep -q chrome-devtools opencode.json && bad "our servers survived uninstall" \
                                        || ok "our servers are gone"
fi

say "CLAIM 3c — a config we take nothing out of is not rewritten"
# Written *after* init and holding only the user's own server, so the strip has
# nothing of ours to remove. Any difference is gratuitous reformatting of a file
# the tool merely looked at. (Seeding it before `init` instead means a server
# gets merged in, and then byte-identity cannot hold — CLAIM 3b covers that
# case by asserting the user's keys survive.)
new c3c; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
printf '{"mcpServers":{"mine":{"command":"node"}}}\n' > .mcp.json
cp .mcp.json "$ROOT/oc2.orig"
node $CLI remove --all --yes >/dev/null 2>&1
if [ -f .mcp.json ]; then
  cmp -s "$ROOT/oc2.orig" .mcp.json && ok "left byte-identical" \
    || { bad "reformatted a file it removed nothing from"; diff "$ROOT/oc2.orig" .mcp.json | head -4; }
else
  bad "deleted a config holding only the user's own server"
fi

say "CLAIM 12g — no command answers a broken project with a stack trace"
new c12g; printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
chmod 000 .opencastle/manifest.json
for cmd in "" "doctor" "sync --check"; do
  out=$(node $CLI $cmd 2>&1 | plain)
  echo "$out" | grep -qE 'at async|Node\.js v' \
    && bad "'opencastle $cmd' printed a stack trace" \
    || ok "'opencastle ${cmd:-(bare)}' failed cleanly"
done
chmod 644 .opencastle/manifest.json

say "CLAIM 4b — init does not rewrite .opencastle/ either"
new c4b; echo '{"name":"p","dependencies":{"@supabase/supabase-js":"^2"}}' > package.json
printf '# R\n' > CLAUDE.md
node $CLI init --yes >/dev/null 2>&1
find .opencastle -name '*.md' -type f -exec sh -c 'printf "\nSENTINEL\n" >> "$1"' _ {} \;
b=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
node $CLI init --yes >/dev/null 2>&1
a=$(grep -rl SENTINEL .opencastle | wc -l | tr -d ' ')
[ "$b" = "$a" ] && ok "init kept all $a hand edits" || bad "init lost $((b-a)) of $b"

echo
echo "════ $PASS passed, $FAIL failed ════"
cd /; rm -rf "$ROOT"
exit $([ $FAIL -eq 0 ] && echo 0 || echo 1)
